/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class apple_laf_JRSUIConstants_NothingToScroll */

#ifndef _Included_apple_laf_JRSUIConstants_NothingToScroll
#define _Included_apple_laf_JRSUIConstants_NothingToScroll
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_NothingToScroll_SHIFT
#define apple_laf_JRSUIConstants_NothingToScroll_SHIFT 37L
#undef apple_laf_JRSUIConstants_NothingToScroll_SIZE
#define apple_laf_JRSUIConstants_NothingToScroll_SIZE 1L
#undef apple_laf_JRSUIConstants_NothingToScroll_MASK
#define apple_laf_JRSUIConstants_NothingToScroll_MASK $LL(137438953472)
#undef apple_laf_JRSUIConstants_NothingToScroll__no
#define apple_laf_JRSUIConstants_NothingToScroll__no 0L
#undef apple_laf_JRSUIConstants_NothingToScroll__yes
#define apple_laf_JRSUIConstants_NothingToScroll__yes 1L
#ifdef __cplusplus
}
#endif
#endif
