/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class apple_laf_JRSUIConstants_ArrowsOnly */

#ifndef _Included_apple_laf_JRSUIConstants_ArrowsOnly
#define _Included_apple_laf_JRSUIConstants_ArrowsOnly
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_ArrowsOnly_SHIFT
#define apple_laf_JRSUIConstants_ArrowsOnly_SHIFT 33L
#undef apple_laf_JRSUIConstants_ArrowsOnly_SIZE
#define apple_laf_JRSUIConstants_ArrowsOnly_SIZE 1L
#undef apple_laf_JRSUIConstants_ArrowsOnly_MASK
#define apple_laf_JRSUIConstants_ArrowsOnly_MASK $LL(8589934592)
#undef apple_laf_JRSUIConstants_ArrowsOnly__no
#define apple_laf_JRSUIConstants_ArrowsOnly__no 0L
#undef apple_laf_JRSUIConstants_ArrowsOnly__yes
#define apple_laf_JRSUIConstants_ArrowsOnly__yes 1L
#ifdef __cplusplus
}
#endif
#endif
