/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class com_apple_laf_ScreenMenu */

#ifndef _Included_com_apple_laf_ScreenMenu
#define _Included_com_apple_laf_ScreenMenu
#ifdef __cplusplus
extern "C" {
#endif
#undef com_apple_laf_ScreenMenu_serialVersionUID
#define com_apple_laf_ScreenMenu_serialVersionUID $LL(-4536902356223894379)
#undef com_apple_laf_ScreenMenu_serialVersionUID
#define com_apple_laf_ScreenMenu_serialVersionUID $LL(-21757335363267194)
#undef com_apple_laf_ScreenMenu_serialVersionUID
#define com_apple_laf_ScreenMenu_serialVersionUID $LL(-8809584163345499784)
/*
 * Class:     com_apple_laf_ScreenMenu
 * Method:    addMenuListeners
 * Signature: (Lcom/apple/laf/ScreenMenu;J)J
 */
JNIEXPORT jlong JNICALL Java_com_apple_laf_ScreenMenu_addMenuListeners
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_apple_laf_ScreenMenu
 * Method:    removeMenuListeners
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_apple_laf_ScreenMenu_removeMenuListeners
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
