/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_metal_MTLLayer */

#ifndef _Included_sun_java2d_metal_MTLLayer
#define _Included_sun_java2d_metal_MTLLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_java2d_metal_MTLLayer
 * Method:    nativeCreateLayer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_java2d_metal_MTLLayer_nativeCreateLayer
  (JNIEnv *, jobject);

/*
 * Class:     sun_java2d_metal_MTLLayer
 * Method:    nativeSetScale
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_metal_MTLLayer_nativeSetScale
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     sun_java2d_metal_MTLLayer
 * Method:    nativeSetInsets
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_metal_MTLLayer_nativeSetInsets
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     sun_java2d_metal_MTLLayer
 * Method:    validate
 * Signature: (JLsun/java2d/metal/MTLSurfaceData;)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_metal_MTLLayer_validate
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     sun_java2d_metal_MTLLayer
 * Method:    blitTexture
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_metal_MTLLayer_blitTexture
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
