/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_lwawt_macosx_CTrayIcon */

#ifndef _Included_sun_lwawt_macosx_CTrayIcon
#define _Included_sun_lwawt_macosx_CTrayIcon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_lwawt_macosx_CTrayIcon
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_lwawt_macosx_CTrayIcon_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     sun_lwawt_macosx_CTrayIcon
 * Method:    nativeSetToolTip
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_lwawt_macosx_CTrayIcon_nativeSetToolTip
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     sun_lwawt_macosx_CTrayIcon
 * Method:    setNativeImage
 * Signature: (JJZZ)V
 */
JNIEXPORT void JNICALL Java_sun_lwawt_macosx_CTrayIcon_setNativeImage
  (JNIEnv *, jobject, jlong, jlong, jboolean, jboolean);

/*
 * Class:     sun_lwawt_macosx_CTrayIcon
 * Method:    nativeShowNotification
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_sun_lwawt_macosx_CTrayIcon_nativeShowNotification
  (JNIEnv *, jobject, jlong, jstring, jstring, jlong);

/*
 * Class:     sun_lwawt_macosx_CTrayIcon
 * Method:    nativeGetIconLocation
 * Signature: (J)Ljava/awt/geom/Point2D;
 */
JNIEXPORT jobject JNICALL Java_sun_lwawt_macosx_CTrayIcon_nativeGetIconLocation
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
