/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_metal_MTLGraphicsConfig */

#ifndef _Included_sun_java2d_metal_MTLGraphicsConfig
#define _Included_sun_java2d_metal_MTLGraphicsConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_java2d_metal_MTLGraphicsConfig
 * Method:    isMetalFrameworkAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_java2d_metal_MTLGraphicsConfig_isMetalFrameworkAvailable
  (JNIEnv *, jclass);

/*
 * Class:     sun_java2d_metal_MTLGraphicsConfig
 * Method:    tryLoadMetalLibrary
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_java2d_metal_MTLGraphicsConfig_tryLoadMetalLibrary
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     sun_java2d_metal_MTLGraphicsConfig
 * Method:    getMTLConfigInfo
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sun_java2d_metal_MTLGraphicsConfig_getMTLConfigInfo
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     sun_java2d_metal_MTLGraphicsConfig
 * Method:    nativeGetMaxTextureSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_java2d_metal_MTLGraphicsConfig_nativeGetMaxTextureSize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
