/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_metal_MTLMaskFill */

#ifndef _Included_sun_java2d_metal_MTLMaskFill
#define _Included_sun_java2d_metal_MTLMaskFill
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_java2d_metal_MTLMaskFill_TRACELOG
#define sun_java2d_metal_MTLMaskFill_TRACELOG 1L
#undef sun_java2d_metal_MTLMaskFill_TRACETIMESTAMP
#define sun_java2d_metal_MTLMaskFill_TRACETIMESTAMP 2L
#undef sun_java2d_metal_MTLMaskFill_TRACECOUNTS
#define sun_java2d_metal_MTLMaskFill_TRACECOUNTS 4L
/*
 * Class:     sun_java2d_metal_MTLMaskFill
 * Method:    maskFill
 * Signature: (IIIIIII[B)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_metal_MTLMaskFill_maskFill
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
