/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_PlatformGraphicsInfo */

#ifndef _Included_sun_awt_PlatformGraphicsInfo
#define _Included_sun_awt_PlatformGraphicsInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_PlatformGraphicsInfo
 * Method:    isInAquaSession
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_PlatformGraphicsInfo_isInAquaSession
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
