/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_metal_MTLRenderQueue */

#ifndef _Included_sun_java2d_metal_MTLRenderQueue
#define _Included_sun_java2d_metal_MTLRenderQueue
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_java2d_metal_MTLRenderQueue_BUFFER_SIZE
#define sun_java2d_metal_MTLRenderQueue_BUFFER_SIZE 32000L
/*
 * Class:     sun_java2d_metal_MTLRenderQueue
 * Method:    flushBuffer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_metal_MTLRenderQueue_flushBuffer
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
