/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_opengl_CGLGraphicsConfig */

#ifndef _Included_sun_java2d_opengl_CGLGraphicsConfig
#define _Included_sun_java2d_opengl_CGLGraphicsConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_java2d_opengl_CGLGraphicsConfig
 * Method:    initCGL
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_java2d_opengl_CGLGraphicsConfig_initCGL
  (JNIEnv *, jclass);

/*
 * Class:     sun_java2d_opengl_CGLGraphicsConfig
 * Method:    getCGLConfigInfo
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_java2d_opengl_CGLGraphicsConfig_getCGLConfigInfo
  (JNIEnv *, jclass);

/*
 * Class:     sun_java2d_opengl_CGLGraphicsConfig
 * Method:    getOGLCapabilities
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sun_java2d_opengl_CGLGraphicsConfig_getOGLCapabilities
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_java2d_opengl_CGLGraphicsConfig
 * Method:    nativeGetMaxTextureSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_java2d_opengl_CGLGraphicsConfig_nativeGetMaxTextureSize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
