#include <sun/awt/X11/XConstants.h>

#include <jcpp.h>

#undef ALL_BUTTONS_MASK
#undef CWX
#undef CWY
#undef MAX_BUTTONS
#undef X_PROTOCOL
#undef X_PROTOCOL_REVISION

using $ClassInfo = ::java::lang::ClassInfo;
using $FieldInfo = ::java::lang::FieldInfo;
using $MethodInfo = ::java::lang::MethodInfo;

namespace sun {
	namespace awt {
		namespace X11 {

$FieldInfo _XConstants_FieldInfo_[] = {
	{"X_PROTOCOL", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, X_PROTOCOL)},
	{"X_PROTOCOL_REVISION", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, X_PROTOCOL_REVISION)},
	{"None", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, None)},
	{"ParentRelative", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ParentRelative)},
	{"CopyFromParent", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CopyFromParent)},
	{"PointerWindow", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PointerWindow)},
	{"InputFocus", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, InputFocus)},
	{"PointerRoot", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PointerRoot)},
	{"AnyPropertyType", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AnyPropertyType)},
	{"AnyKey", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AnyKey)},
	{"AnyButton", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AnyButton)},
	{"AllTemporary", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AllTemporary)},
	{"CurrentTime", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CurrentTime)},
	{"NoSymbol", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NoSymbol)},
	{"NoEventMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NoEventMask)},
	{"KeyPressMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KeyPressMask)},
	{"KeyReleaseMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KeyReleaseMask)},
	{"ButtonPressMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ButtonPressMask)},
	{"ButtonReleaseMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ButtonReleaseMask)},
	{"EnterWindowMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, EnterWindowMask)},
	{"LeaveWindowMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LeaveWindowMask)},
	{"PointerMotionMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PointerMotionMask)},
	{"PointerMotionHintMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PointerMotionHintMask)},
	{"Button1MotionMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Button1MotionMask)},
	{"Button2MotionMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Button2MotionMask)},
	{"Button3MotionMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Button3MotionMask)},
	{"Button4MotionMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Button4MotionMask)},
	{"Button5MotionMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Button5MotionMask)},
	{"ButtonMotionMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ButtonMotionMask)},
	{"KeymapStateMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KeymapStateMask)},
	{"ExposureMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ExposureMask)},
	{"VisibilityChangeMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, VisibilityChangeMask)},
	{"StructureNotifyMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, StructureNotifyMask)},
	{"ResizeRedirectMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ResizeRedirectMask)},
	{"SubstructureNotifyMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SubstructureNotifyMask)},
	{"SubstructureRedirectMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SubstructureRedirectMask)},
	{"FocusChangeMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FocusChangeMask)},
	{"PropertyChangeMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PropertyChangeMask)},
	{"ColormapChangeMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ColormapChangeMask)},
	{"OwnerGrabButtonMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, OwnerGrabButtonMask)},
	{"MAX_BUTTONS", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MAX_BUTTONS)},
	{"ALL_BUTTONS_MASK", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ALL_BUTTONS_MASK)},
	{"KeyPress", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KeyPress)},
	{"KeyRelease", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KeyRelease)},
	{"ButtonPress", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ButtonPress)},
	{"ButtonRelease", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ButtonRelease)},
	{"MotionNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MotionNotify)},
	{"EnterNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, EnterNotify)},
	{"LeaveNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LeaveNotify)},
	{"FocusIn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FocusIn)},
	{"FocusOut", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FocusOut)},
	{"KeymapNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KeymapNotify)},
	{"Expose", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Expose)},
	{"GraphicsExpose", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GraphicsExpose)},
	{"NoExpose", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NoExpose)},
	{"VisibilityNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, VisibilityNotify)},
	{"CreateNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CreateNotify)},
	{"DestroyNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DestroyNotify)},
	{"UnmapNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, UnmapNotify)},
	{"MapNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MapNotify)},
	{"MapRequest", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MapRequest)},
	{"ReparentNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ReparentNotify)},
	{"ConfigureNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ConfigureNotify)},
	{"ConfigureRequest", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ConfigureRequest)},
	{"GravityNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GravityNotify)},
	{"ResizeRequest", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ResizeRequest)},
	{"CirculateNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CirculateNotify)},
	{"CirculateRequest", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CirculateRequest)},
	{"PropertyNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PropertyNotify)},
	{"SelectionClear", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SelectionClear)},
	{"SelectionRequest", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SelectionRequest)},
	{"SelectionNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SelectionNotify)},
	{"ColormapNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ColormapNotify)},
	{"ClientMessage", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ClientMessage)},
	{"MappingNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MappingNotify)},
	{"LASTEvent", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LASTEvent)},
	{"ShiftMask", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ShiftMask)},
	{"LockMask", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LockMask)},
	{"ControlMask", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ControlMask)},
	{"Mod1Mask", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Mod1Mask)},
	{"Mod2Mask", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Mod2Mask)},
	{"Mod3Mask", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Mod3Mask)},
	{"Mod4Mask", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Mod4Mask)},
	{"Mod5Mask", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Mod5Mask)},
	{"ShiftMapIndex", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ShiftMapIndex)},
	{"LockMapIndex", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LockMapIndex)},
	{"ControlMapIndex", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ControlMapIndex)},
	{"Mod1MapIndex", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Mod1MapIndex)},
	{"Mod2MapIndex", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Mod2MapIndex)},
	{"Mod3MapIndex", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Mod3MapIndex)},
	{"Mod4MapIndex", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Mod4MapIndex)},
	{"Mod5MapIndex", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Mod5MapIndex)},
	{"AnyModifier", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AnyModifier)},
	{"buttons", "[I", nullptr, $PUBLIC | $STATIC | $FINAL, $staticField(XConstants, buttons)},
	{"MouseWheelUp", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $staticField(XConstants, MouseWheelUp)},
	{"MouseWheelDown", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $staticField(XConstants, MouseWheelDown)},
	{"NotifyNormal", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyNormal)},
	{"NotifyGrab", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyGrab)},
	{"NotifyUngrab", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyUngrab)},
	{"NotifyWhileGrabbed", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyWhileGrabbed)},
	{"NotifyHint", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyHint)},
	{"NotifyAncestor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyAncestor)},
	{"NotifyVirtual", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyVirtual)},
	{"NotifyInferior", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyInferior)},
	{"NotifyNonlinear", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyNonlinear)},
	{"NotifyNonlinearVirtual", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyNonlinearVirtual)},
	{"NotifyPointer", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyPointer)},
	{"NotifyPointerRoot", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyPointerRoot)},
	{"NotifyDetailNone", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotifyDetailNone)},
	{"VisibilityUnobscured", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, VisibilityUnobscured)},
	{"VisibilityPartiallyObscured", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, VisibilityPartiallyObscured)},
	{"VisibilityFullyObscured", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, VisibilityFullyObscured)},
	{"PlaceOnTop", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PlaceOnTop)},
	{"PlaceOnBottom", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PlaceOnBottom)},
	{"FamilyInternet", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FamilyInternet)},
	{"FamilyDECnet", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FamilyDECnet)},
	{"FamilyChaos", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FamilyChaos)},
	{"PropertyNewValue", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PropertyNewValue)},
	{"PropertyDelete", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PropertyDelete)},
	{"ColormapUninstalled", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ColormapUninstalled)},
	{"ColormapInstalled", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ColormapInstalled)},
	{"GrabModeSync", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GrabModeSync)},
	{"GrabModeAsync", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GrabModeAsync)},
	{"GrabSuccess", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GrabSuccess)},
	{"AlreadyGrabbed", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AlreadyGrabbed)},
	{"GrabInvalidTime", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GrabInvalidTime)},
	{"GrabNotViewable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GrabNotViewable)},
	{"GrabFrozen", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GrabFrozen)},
	{"AsyncPointer", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AsyncPointer)},
	{"SyncPointer", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SyncPointer)},
	{"ReplayPointer", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ReplayPointer)},
	{"AsyncKeyboard", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AsyncKeyboard)},
	{"SyncKeyboard", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SyncKeyboard)},
	{"ReplayKeyboard", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ReplayKeyboard)},
	{"AsyncBoth", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AsyncBoth)},
	{"SyncBoth", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SyncBoth)},
	{"RevertToNone", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, RevertToNone)},
	{"RevertToPointerRoot", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, RevertToPointerRoot)},
	{"RevertToParent", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, RevertToParent)},
	{"QueuedAlready", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, QueuedAlready)},
	{"QueuedAfterReading", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, QueuedAfterReading)},
	{"QueuedAfterFlush", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, QueuedAfterFlush)},
	{"Success", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Success)},
	{"BadRequest", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadRequest)},
	{"BadValue", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadValue)},
	{"BadWindow", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadWindow)},
	{"BadPixmap", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadPixmap)},
	{"BadAtom", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadAtom)},
	{"BadCursor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadCursor)},
	{"BadFont", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadFont)},
	{"BadMatch", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadMatch)},
	{"BadDrawable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadDrawable)},
	{"BadAccess", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadAccess)},
	{"BadAlloc", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadAlloc)},
	{"BadColor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadColor)},
	{"BadGC", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadGC)},
	{"BadIDChoice", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadIDChoice)},
	{"BadName", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadName)},
	{"BadLength", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadLength)},
	{"BadImplementation", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BadImplementation)},
	{"FirstExtensionError", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FirstExtensionError)},
	{"LastExtensionError", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LastExtensionError)},
	{"InputOutput", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, InputOutput)},
	{"InputOnly", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, InputOnly)},
	{"CWBackPixmap", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWBackPixmap)},
	{"CWBackPixel", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWBackPixel)},
	{"CWBorderPixmap", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWBorderPixmap)},
	{"CWBorderPixel", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWBorderPixel)},
	{"CWBitGravity", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWBitGravity)},
	{"CWWinGravity", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWWinGravity)},
	{"CWBackingStore", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWBackingStore)},
	{"CWBackingPlanes", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWBackingPlanes)},
	{"CWBackingPixel", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWBackingPixel)},
	{"CWOverrideRedirect", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWOverrideRedirect)},
	{"CWSaveUnder", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWSaveUnder)},
	{"CWEventMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWEventMask)},
	{"CWDontPropagate", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWDontPropagate)},
	{"CWColormap", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWColormap)},
	{"CWCursor", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWCursor)},
	{"CWX", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWX)},
	{"CWY", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWY)},
	{"CWWidth", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWWidth)},
	{"CWHeight", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWHeight)},
	{"CWBorderWidth", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWBorderWidth)},
	{"CWSibling", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWSibling)},
	{"CWStackMode", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CWStackMode)},
	{"ForgetGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ForgetGravity)},
	{"NorthWestGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NorthWestGravity)},
	{"NorthGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NorthGravity)},
	{"NorthEastGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NorthEastGravity)},
	{"WestGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, WestGravity)},
	{"CenterGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CenterGravity)},
	{"EastGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, EastGravity)},
	{"SouthWestGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SouthWestGravity)},
	{"SouthGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SouthGravity)},
	{"SouthEastGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SouthEastGravity)},
	{"StaticGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, StaticGravity)},
	{"UnmapGravity", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, UnmapGravity)},
	{"NotUseful", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, NotUseful)},
	{"WhenMapped", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, WhenMapped)},
	{"Always", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Always)},
	{"IsUnmapped", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, IsUnmapped)},
	{"IsUnviewable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, IsUnviewable)},
	{"IsViewable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, IsViewable)},
	{"SetModeInsert", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SetModeInsert)},
	{"SetModeDelete", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, SetModeDelete)},
	{"DestroyAll", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DestroyAll)},
	{"RetainPermanent", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, RetainPermanent)},
	{"RetainTemporary", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, RetainTemporary)},
	{"Above", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Above)},
	{"Below", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Below)},
	{"TopIf", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, TopIf)},
	{"BottomIf", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, BottomIf)},
	{"Opposite", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Opposite)},
	{"RaiseLowest", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, RaiseLowest)},
	{"LowerHighest", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LowerHighest)},
	{"PropModeReplace", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PropModeReplace)},
	{"PropModePrepend", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PropModePrepend)},
	{"PropModeAppend", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PropModeAppend)},
	{"GXclear", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXclear)},
	{"GXand", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXand)},
	{"GXandReverse", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXandReverse)},
	{"GXcopy", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXcopy)},
	{"GXandInverted", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXandInverted)},
	{"GXnoop", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXnoop)},
	{"GXxor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXxor)},
	{"GXor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXor)},
	{"GXnor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXnor)},
	{"GXequiv", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXequiv)},
	{"GXinvert", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXinvert)},
	{"GXorReverse", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXorReverse)},
	{"GXcopyInverted", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXcopyInverted)},
	{"GXorInverted", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXorInverted)},
	{"GXnand", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXnand)},
	{"GXset", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GXset)},
	{"LineSolid", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LineSolid)},
	{"LineOnOffDash", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LineOnOffDash)},
	{"LineDoubleDash", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LineDoubleDash)},
	{"CapNotLast", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CapNotLast)},
	{"CapButt", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CapButt)},
	{"CapRound", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CapRound)},
	{"CapProjecting", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CapProjecting)},
	{"JoinMiter", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, JoinMiter)},
	{"JoinRound", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, JoinRound)},
	{"JoinBevel", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, JoinBevel)},
	{"FillSolid", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FillSolid)},
	{"FillTiled", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FillTiled)},
	{"FillStippled", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FillStippled)},
	{"FillOpaqueStippled", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FillOpaqueStippled)},
	{"EvenOddRule", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, EvenOddRule)},
	{"WindingRule", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, WindingRule)},
	{"ClipByChildren", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ClipByChildren)},
	{"IncludeInferiors", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, IncludeInferiors)},
	{"Unsorted", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Unsorted)},
	{"YSorted", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, YSorted)},
	{"YXSorted", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, YXSorted)},
	{"YXBanded", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, YXBanded)},
	{"CoordModeOrigin", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CoordModeOrigin)},
	{"CoordModePrevious", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CoordModePrevious)},
	{"Complex", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Complex)},
	{"Nonconvex", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Nonconvex)},
	{"Convex", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, Convex)},
	{"ArcChord", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ArcChord)},
	{"ArcPieSlice", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ArcPieSlice)},
	{"GCFunction", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCFunction)},
	{"GCPlaneMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCPlaneMask)},
	{"GCForeground", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCForeground)},
	{"GCBackground", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCBackground)},
	{"GCLineWidth", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCLineWidth)},
	{"GCLineStyle", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCLineStyle)},
	{"GCCapStyle", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCCapStyle)},
	{"GCJoinStyle", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCJoinStyle)},
	{"GCFillStyle", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCFillStyle)},
	{"GCFillRule", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCFillRule)},
	{"GCTile", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCTile)},
	{"GCStipple", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCStipple)},
	{"GCTileStipXOrigin", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCTileStipXOrigin)},
	{"GCTileStipYOrigin", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCTileStipYOrigin)},
	{"GCFont", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCFont)},
	{"GCSubwindowMode", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCSubwindowMode)},
	{"GCGraphicsExposures", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCGraphicsExposures)},
	{"GCClipXOrigin", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCClipXOrigin)},
	{"GCClipYOrigin", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCClipYOrigin)},
	{"GCClipMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCClipMask)},
	{"GCDashOffset", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCDashOffset)},
	{"GCDashList", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCDashList)},
	{"GCArcMode", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCArcMode)},
	{"GCLastBit", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GCLastBit)},
	{"FontLeftToRight", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FontLeftToRight)},
	{"FontRightToLeft", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FontRightToLeft)},
	{"FontChange", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, FontChange)},
	{"XYBitmap", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XYBitmap)},
	{"XYPixmap", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XYPixmap)},
	{"ZPixmap", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ZPixmap)},
	{"AllocNone", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AllocNone)},
	{"AllocAll", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AllocAll)},
	{"DoRed", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DoRed)},
	{"DoGreen", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DoGreen)},
	{"DoBlue", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DoBlue)},
	{"CursorShape", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, CursorShape)},
	{"TileShape", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, TileShape)},
	{"StippleShape", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, StippleShape)},
	{"AutoRepeatModeOff", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AutoRepeatModeOff)},
	{"AutoRepeatModeOn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AutoRepeatModeOn)},
	{"AutoRepeatModeDefault", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AutoRepeatModeDefault)},
	{"LedModeOff", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LedModeOff)},
	{"LedModeOn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LedModeOn)},
	{"KBKeyClickPercent", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KBKeyClickPercent)},
	{"KBBellPercent", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KBBellPercent)},
	{"KBBellPitch", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KBBellPitch)},
	{"KBBellDuration", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KBBellDuration)},
	{"KBLed", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KBLed)},
	{"KBLedMode", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KBLedMode)},
	{"KBKey", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KBKey)},
	{"KBAutoRepeatMode", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, KBAutoRepeatMode)},
	{"MappingSuccess", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MappingSuccess)},
	{"MappingBusy", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MappingBusy)},
	{"MappingFailed", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MappingFailed)},
	{"MappingModifier", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MappingModifier)},
	{"MappingKeyboard", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MappingKeyboard)},
	{"MappingPointer", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MappingPointer)},
	{"DontPreferBlanking", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DontPreferBlanking)},
	{"PreferBlanking", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PreferBlanking)},
	{"DefaultBlanking", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DefaultBlanking)},
	{"DisableScreenSaver", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DisableScreenSaver)},
	{"DisableScreenInterval", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DisableScreenInterval)},
	{"DontAllowExposures", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DontAllowExposures)},
	{"AllowExposures", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, AllowExposures)},
	{"DefaultExposures", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DefaultExposures)},
	{"ScreenSaverReset", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ScreenSaverReset)},
	{"ScreenSaverActive", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, ScreenSaverActive)},
	{"HostInsert", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, HostInsert)},
	{"HostDelete", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, HostDelete)},
	{"EnableAccess", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, EnableAccess)},
	{"DisableAccess", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DisableAccess)},
	{"StaticGray", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, StaticGray)},
	{"GrayScale", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, GrayScale)},
	{"StaticColor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, StaticColor)},
	{"PseudoColor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, PseudoColor)},
	{"TrueColor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, TrueColor)},
	{"DirectColor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, DirectColor)},
	{"LSBFirst", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, LSBFirst)},
	{"MSBFirst", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, MSBFirst)},
	{"XkbUseCoreKbd", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbUseCoreKbd)},
	{"XkbNewKeyboardNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbNewKeyboardNotify)},
	{"XkbMapNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbMapNotify)},
	{"XkbStateNotify", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbStateNotify)},
	{"XkbNewKeyboardNotifyMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbNewKeyboardNotifyMask)},
	{"XkbMapNotifyMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbMapNotifyMask)},
	{"XkbStateNotifyMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbStateNotifyMask)},
	{"XkbGroupStateMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbGroupStateMask)},
	{"XkbKeyTypesMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbKeyTypesMask)},
	{"XkbKeySymsMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbKeySymsMask)},
	{"XkbModifierMapMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbModifierMapMask)},
	{"XkbVirtualModsMask", "J", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(XConstants, XkbVirtualModsMask)},
	{}
};

$MethodInfo _XConstants_MethodInfo_[] = {
	{"<init>", "()V", nullptr, $PRIVATE, $method(XConstants, init$, void)},
	{}
};

$ClassInfo _XConstants_ClassInfo_ = {
	$PUBLIC | $FINAL | $ACC_SUPER,
	"sun.awt.X11.XConstants",
	"java.lang.Object",
	nullptr,
	_XConstants_FieldInfo_,
	_XConstants_MethodInfo_
};

$Object* allocate$XConstants($Class* clazz) {
	return $of($alloc(XConstants));
}

$ints* XConstants::buttons = nullptr;
int32_t XConstants::MouseWheelUp = 0;
int32_t XConstants::MouseWheelDown = 0;

void XConstants::init$() {
}

void clinit$XConstants($Class* class$) {
	$assignStatic(XConstants::buttons, $new($ints, {
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		16,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		24
	}));
	XConstants::MouseWheelUp = $nc(XConstants::buttons)->get(3);
	XConstants::MouseWheelDown = $nc(XConstants::buttons)->get(4);
}

XConstants::XConstants() {
}

$Class* XConstants::load$($String* name, bool initialize) {
	$loadClass(XConstants, name, initialize, &_XConstants_ClassInfo_, clinit$XConstants, allocate$XConstants);
	return class$;
}

$Class* XConstants::class$ = nullptr;

		} // X11
	} // awt
} // sun