/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WLightweightFramePeer */

#ifndef _Included_sun_awt_windows_WLightweightFramePeer
#define _Included_sun_awt_windows_WLightweightFramePeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WLightweightFramePeer_BANDING_DIVISOR
#define sun_awt_windows_WLightweightFramePeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WLightweightFramePeer
 * Method:    overrideNativeHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WLightweightFramePeer_overrideNativeHandle
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
