/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WTextFieldPeer */

#ifndef _Included_sun_awt_windows_WTextFieldPeer
#define _Included_sun_awt_windows_WTextFieldPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WTextFieldPeer_BANDING_DIVISOR
#define sun_awt_windows_WTextFieldPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WTextFieldPeer
 * Method:    setEchoChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTextFieldPeer_setEchoChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     sun_awt_windows_WTextFieldPeer
 * Method:    create
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTextFieldPeer_create
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
