/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_Win32GraphicsEnvironment */

#ifndef _Included_sun_awt_Win32GraphicsEnvironment
#define _Included_sun_awt_Win32GraphicsEnvironment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_Win32GraphicsEnvironment
 * Method:    initDisplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_Win32GraphicsEnvironment_initDisplay
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_Win32GraphicsEnvironment
 * Method:    getNumScreens
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_Win32GraphicsEnvironment_getNumScreens
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_Win32GraphicsEnvironment
 * Method:    getDefaultScreen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_Win32GraphicsEnvironment_getDefaultScreen
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_Win32GraphicsEnvironment
 * Method:    getXResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_Win32GraphicsEnvironment_getXResolution
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_Win32GraphicsEnvironment
 * Method:    getYResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_Win32GraphicsEnvironment_getYResolution
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_Win32GraphicsEnvironment
 * Method:    isVistaOS
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_Win32GraphicsEnvironment_isVistaOS
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
