/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WDataTransferer */

#ifndef _Included_sun_awt_windows_WDataTransferer
#define _Included_sun_awt_windows_WDataTransferer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WDataTransferer_CF_TEXT
#define sun_awt_windows_WDataTransferer_CF_TEXT 1L
#undef sun_awt_windows_WDataTransferer_CF_METAFILEPICT
#define sun_awt_windows_WDataTransferer_CF_METAFILEPICT 3L
#undef sun_awt_windows_WDataTransferer_CF_DIB
#define sun_awt_windows_WDataTransferer_CF_DIB 8L
#undef sun_awt_windows_WDataTransferer_CF_ENHMETAFILE
#define sun_awt_windows_WDataTransferer_CF_ENHMETAFILE 14L
#undef sun_awt_windows_WDataTransferer_CF_HDROP
#define sun_awt_windows_WDataTransferer_CF_HDROP 15L
#undef sun_awt_windows_WDataTransferer_CF_LOCALE
#define sun_awt_windows_WDataTransferer_CF_LOCALE 16L
/*
 * Class:     sun_awt_windows_WDataTransferer
 * Method:    registerClipboardFormat
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_windows_WDataTransferer_registerClipboardFormat
  (JNIEnv *, jclass, jstring);

/*
 * Class:     sun_awt_windows_WDataTransferer
 * Method:    getClipboardFormatName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_windows_WDataTransferer_getClipboardFormatName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_awt_windows_WDataTransferer
 * Method:    imageDataToPlatformImageBytes
 * Signature: ([BIIJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_sun_awt_windows_WDataTransferer_imageDataToPlatformImageBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);

/*
 * Class:     sun_awt_windows_WDataTransferer
 * Method:    platformImageBytesToImageData
 * Signature: ([BJ)[I
 */
JNIEXPORT jintArray JNICALL Java_sun_awt_windows_WDataTransferer_platformImageBytesToImageData
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     sun_awt_windows_WDataTransferer
 * Method:    dragQueryFile
 * Signature: ([B)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_sun_awt_windows_WDataTransferer_dragQueryFile
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
