/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WDefaultFontCharset */

#ifndef _Included_sun_awt_windows_WDefaultFontCharset
#define _Included_sun_awt_windows_WDefaultFontCharset
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WDefaultFontCharset
 * Method:    canConvert
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WDefaultFontCharset_canConvert
  (JNIEnv *, jobject, jchar);

/*
 * Class:     sun_awt_windows_WDefaultFontCharset
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDefaultFontCharset_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
