/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WTrayIconPeer */

#ifndef _Included_sun_awt_windows_WTrayIconPeer
#define _Included_sun_awt_windows_WTrayIconPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WTrayIconPeer_TRAY_ICON_WIDTH
#define sun_awt_windows_WTrayIconPeer_TRAY_ICON_WIDTH 16L
#undef sun_awt_windows_WTrayIconPeer_TRAY_ICON_HEIGHT
#define sun_awt_windows_WTrayIconPeer_TRAY_ICON_HEIGHT 16L
#undef sun_awt_windows_WTrayIconPeer_TRAY_ICON_MASK_SIZE
#define sun_awt_windows_WTrayIconPeer_TRAY_ICON_MASK_SIZE 32L
/*
 * Class:     sun_awt_windows_WTrayIconPeer
 * Method:    setToolTip
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTrayIconPeer_setToolTip
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_awt_windows_WTrayIconPeer
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTrayIconPeer_create
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WTrayIconPeer
 * Method:    _dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTrayIconPeer__1dispose
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WTrayIconPeer
 * Method:    updateNativeIcon
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTrayIconPeer_updateNativeIcon
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sun_awt_windows_WTrayIconPeer
 * Method:    setNativeIcon
 * Signature: ([I[BIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTrayIconPeer_setNativeIcon
  (JNIEnv *, jobject, jintArray, jbyteArray, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WTrayIconPeer
 * Method:    _displayMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTrayIconPeer__1displayMessage
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
