/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WDialogPeer */

#ifndef _Included_sun_awt_windows_WDialogPeer
#define _Included_sun_awt_windows_WDialogPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WDialogPeer_BANDING_DIVISOR
#define sun_awt_windows_WDialogPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WDialogPeer
 * Method:    createAwtDialog
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDialogPeer_createAwtDialog
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WDialogPeer
 * Method:    showModal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDialogPeer_showModal
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WDialogPeer
 * Method:    endModal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDialogPeer_endModal
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WDialogPeer
 * Method:    pSetIMMOption
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDialogPeer_pSetIMMOption
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
