/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class sun_awt_shell_Win32ShellFolder2 */

#ifndef _Included_sun_awt_shell_Win32ShellFolder2
#define _Included_sun_awt_shell_Win32ShellFolder2
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_shell_Win32ShellFolder2_serialVersionUID
#define sun_awt_shell_Win32ShellFolder2_serialVersionUID $LL(301077366599181567)
#undef sun_awt_shell_Win32ShellFolder2_SMALL_ICON_SIZE
#define sun_awt_shell_Win32ShellFolder2_SMALL_ICON_SIZE 16L
#undef sun_awt_shell_Win32ShellFolder2_LARGE_ICON_SIZE
#define sun_awt_shell_Win32ShellFolder2_LARGE_ICON_SIZE 32L
#undef sun_awt_shell_Win32ShellFolder2_MIN_QUALITY_ICON
#define sun_awt_shell_Win32ShellFolder2_MIN_QUALITY_ICON 16L
#undef sun_awt_shell_Win32ShellFolder2_MAX_QUALITY_ICON
#define sun_awt_shell_Win32ShellFolder2_MAX_QUALITY_ICON 256L
#undef sun_awt_shell_Win32ShellFolder2_FILE_ICON_ID
#define sun_awt_shell_Win32ShellFolder2_FILE_ICON_ID 1L
#undef sun_awt_shell_Win32ShellFolder2_FOLDER_ICON_ID
#define sun_awt_shell_Win32ShellFolder2_FOLDER_ICON_ID 4L
#undef sun_awt_shell_Win32ShellFolder2_DESKTOP
#define sun_awt_shell_Win32ShellFolder2_DESKTOP 0L
#undef sun_awt_shell_Win32ShellFolder2_INTERNET
#define sun_awt_shell_Win32ShellFolder2_INTERNET 1L
#undef sun_awt_shell_Win32ShellFolder2_PROGRAMS
#define sun_awt_shell_Win32ShellFolder2_PROGRAMS 2L
#undef sun_awt_shell_Win32ShellFolder2_CONTROLS
#define sun_awt_shell_Win32ShellFolder2_CONTROLS 3L
#undef sun_awt_shell_Win32ShellFolder2_PRINTERS
#define sun_awt_shell_Win32ShellFolder2_PRINTERS 4L
#undef sun_awt_shell_Win32ShellFolder2_PERSONAL
#define sun_awt_shell_Win32ShellFolder2_PERSONAL 5L
#undef sun_awt_shell_Win32ShellFolder2_FAVORITES
#define sun_awt_shell_Win32ShellFolder2_FAVORITES 6L
#undef sun_awt_shell_Win32ShellFolder2_STARTUP
#define sun_awt_shell_Win32ShellFolder2_STARTUP 7L
#undef sun_awt_shell_Win32ShellFolder2_RECENT
#define sun_awt_shell_Win32ShellFolder2_RECENT 8L
#undef sun_awt_shell_Win32ShellFolder2_SENDTO
#define sun_awt_shell_Win32ShellFolder2_SENDTO 9L
#undef sun_awt_shell_Win32ShellFolder2_BITBUCKET
#define sun_awt_shell_Win32ShellFolder2_BITBUCKET 10L
#undef sun_awt_shell_Win32ShellFolder2_STARTMENU
#define sun_awt_shell_Win32ShellFolder2_STARTMENU 11L
#undef sun_awt_shell_Win32ShellFolder2_DESKTOPDIRECTORY
#define sun_awt_shell_Win32ShellFolder2_DESKTOPDIRECTORY 16L
#undef sun_awt_shell_Win32ShellFolder2_DRIVES
#define sun_awt_shell_Win32ShellFolder2_DRIVES 17L
#undef sun_awt_shell_Win32ShellFolder2_NETWORK
#define sun_awt_shell_Win32ShellFolder2_NETWORK 18L
#undef sun_awt_shell_Win32ShellFolder2_NETHOOD
#define sun_awt_shell_Win32ShellFolder2_NETHOOD 19L
#undef sun_awt_shell_Win32ShellFolder2_FONTS
#define sun_awt_shell_Win32ShellFolder2_FONTS 20L
#undef sun_awt_shell_Win32ShellFolder2_TEMPLATES
#define sun_awt_shell_Win32ShellFolder2_TEMPLATES 21L
#undef sun_awt_shell_Win32ShellFolder2_COMMON_STARTMENU
#define sun_awt_shell_Win32ShellFolder2_COMMON_STARTMENU 22L
#undef sun_awt_shell_Win32ShellFolder2_COMMON_PROGRAMS
#define sun_awt_shell_Win32ShellFolder2_COMMON_PROGRAMS 23L
#undef sun_awt_shell_Win32ShellFolder2_COMMON_STARTUP
#define sun_awt_shell_Win32ShellFolder2_COMMON_STARTUP 24L
#undef sun_awt_shell_Win32ShellFolder2_COMMON_DESKTOPDIRECTORY
#define sun_awt_shell_Win32ShellFolder2_COMMON_DESKTOPDIRECTORY 25L
#undef sun_awt_shell_Win32ShellFolder2_APPDATA
#define sun_awt_shell_Win32ShellFolder2_APPDATA 26L
#undef sun_awt_shell_Win32ShellFolder2_PRINTHOOD
#define sun_awt_shell_Win32ShellFolder2_PRINTHOOD 27L
#undef sun_awt_shell_Win32ShellFolder2_ALTSTARTUP
#define sun_awt_shell_Win32ShellFolder2_ALTSTARTUP 29L
#undef sun_awt_shell_Win32ShellFolder2_COMMON_ALTSTARTUP
#define sun_awt_shell_Win32ShellFolder2_COMMON_ALTSTARTUP 30L
#undef sun_awt_shell_Win32ShellFolder2_COMMON_FAVORITES
#define sun_awt_shell_Win32ShellFolder2_COMMON_FAVORITES 31L
#undef sun_awt_shell_Win32ShellFolder2_INTERNET_CACHE
#define sun_awt_shell_Win32ShellFolder2_INTERNET_CACHE 32L
#undef sun_awt_shell_Win32ShellFolder2_COOKIES
#define sun_awt_shell_Win32ShellFolder2_COOKIES 33L
#undef sun_awt_shell_Win32ShellFolder2_HISTORY
#define sun_awt_shell_Win32ShellFolder2_HISTORY 34L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_CANCOPY
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_CANCOPY 1L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_CANMOVE
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_CANMOVE 2L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_CANLINK
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_CANLINK 4L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_CANRENAME
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_CANRENAME 16L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_CANDELETE
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_CANDELETE 32L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_HASPROPSHEET
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_HASPROPSHEET 64L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_DROPTARGET
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_DROPTARGET 256L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_LINK
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_LINK 65536L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_SHARE
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_SHARE 131072L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_READONLY
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_READONLY 262144L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_GHOSTED
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_GHOSTED 524288L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_HIDDEN
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_HIDDEN 524288L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_FILESYSANCESTOR
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_FILESYSANCESTOR 268435456L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_FOLDER
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_FOLDER 536870912L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_FILESYSTEM
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_FILESYSTEM 1073741824L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_HASSUBFOLDER
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_HASSUBFOLDER -2147483648L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_VALIDATE
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_VALIDATE 16777216L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_REMOVABLE
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_REMOVABLE 33554432L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_COMPRESSED
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_COMPRESSED 67108864L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_BROWSABLE
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_BROWSABLE 134217728L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_NONENUMERATED
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_NONENUMERATED 1048576L
#undef sun_awt_shell_Win32ShellFolder2_ATTRIB_NEWCONTENT
#define sun_awt_shell_Win32ShellFolder2_ATTRIB_NEWCONTENT 2097152L
#undef sun_awt_shell_Win32ShellFolder2_SHGDN_NORMAL
#define sun_awt_shell_Win32ShellFolder2_SHGDN_NORMAL 0L
#undef sun_awt_shell_Win32ShellFolder2_SHGDN_INFOLDER
#define sun_awt_shell_Win32ShellFolder2_SHGDN_INFOLDER 1L
#undef sun_awt_shell_Win32ShellFolder2_SHGDN_INCLUDE_NONFILESYS
#define sun_awt_shell_Win32ShellFolder2_SHGDN_INCLUDE_NONFILESYS 8192L
#undef sun_awt_shell_Win32ShellFolder2_SHGDN_FORADDRESSBAR
#define sun_awt_shell_Win32ShellFolder2_SHGDN_FORADDRESSBAR 16384L
#undef sun_awt_shell_Win32ShellFolder2_SHGDN_FORPARSING
#define sun_awt_shell_Win32ShellFolder2_SHGDN_FORPARSING 32768L
#undef sun_awt_shell_Win32ShellFolder2_LVCFMT_LEFT
#define sun_awt_shell_Win32ShellFolder2_LVCFMT_LEFT 0L
#undef sun_awt_shell_Win32ShellFolder2_LVCFMT_RIGHT
#define sun_awt_shell_Win32ShellFolder2_LVCFMT_RIGHT 1L
#undef sun_awt_shell_Win32ShellFolder2_LVCFMT_CENTER
#define sun_awt_shell_Win32ShellFolder2_LVCFMT_CENTER 2L
/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_shell_Win32ShellFolder2_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    initDesktop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_shell_Win32ShellFolder2_initDesktop
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    initSpecial
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_sun_awt_shell_Win32ShellFolder2_initSpecial
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getNextPIDLEntry
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_getNextPIDLEntry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    copyFirstPIDLEntry
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_copyFirstPIDLEntry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    combinePIDLs
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_combinePIDLs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    releasePIDL
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_shell_Win32ShellFolder2_releasePIDL
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    releaseIShellFolder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_shell_Win32ShellFolder2_releaseIShellFolder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    compareIDs
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_shell_Win32ShellFolder2_compareIDs
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getAttributes0
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_shell_Win32ShellFolder2_getAttributes0
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getFileSystemPath0
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_shell_Win32ShellFolder2_getFileSystemPath0
  (JNIEnv *, jclass, jint);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getEnumObjects
 * Signature: (JZZ)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_getEnumObjects
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getNextChild
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_getNextChild
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    releaseEnumObjects
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_shell_Win32ShellFolder2_releaseEnumObjects
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    bindToObject
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_bindToObject
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getLinkLocation
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_getLinkLocation
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    parseDisplayName0
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_parseDisplayName0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getDisplayNameOf
 * Signature: (JJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_shell_Win32ShellFolder2_getDisplayNameOf
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    loadKnownFolders
 * Signature: ()[Lsun/awt/shell/Win32ShellFolder2/KnownFolderDefinition;
 */
JNIEXPORT jobjectArray JNICALL Java_sun_awt_shell_Win32ShellFolder2_loadKnownFolders
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getFolderType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_shell_Win32ShellFolder2_getFolderType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getExecutableType
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_shell_Win32ShellFolder2_getExecutableType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getIShellIcon
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_getIShellIcon
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getIconIndex
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_shell_Win32ShellFolder2_getIconIndex
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getIcon
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_getIcon
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    extractIcon
 * Signature: (JJIZ)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_extractIcon
  (JNIEnv *, jclass, jlong, jlong, jint, jboolean);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    hiResIconAvailable
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_shell_Win32ShellFolder2_hiResIconAvailable
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getSystemIcon
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_getSystemIcon
  (JNIEnv *, jclass, jint);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getIconResource
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_shell_Win32ShellFolder2_getIconResource
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getIconBits
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_sun_awt_shell_Win32ShellFolder2_getIconBits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    disposeIcon
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_shell_Win32ShellFolder2_disposeIcon
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    getStandardViewButton0
 * Signature: (IZ)[I
 */
JNIEXPORT jintArray JNICALL Java_sun_awt_shell_Win32ShellFolder2_getStandardViewButton0
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    doGetColumnInfo
 * Signature: (J)[Lsun/awt/shell/ShellFolderColumnInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_sun_awt_shell_Win32ShellFolder2_doGetColumnInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    doGetColumnValue
 * Signature: (JJI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_shell_Win32ShellFolder2_doGetColumnValue
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     sun_awt_shell_Win32ShellFolder2
 * Method:    compareIDsByColumn
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_shell_Win32ShellFolder2_compareIDsByColumn
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
