/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_d3d_D3DTextRenderer */

#ifndef _Included_sun_java2d_d3d_D3DTextRenderer
#define _Included_sun_java2d_d3d_D3DTextRenderer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_java2d_d3d_D3DTextRenderer_BYTES_PER_GLYPH_IMAGE
#define sun_java2d_d3d_D3DTextRenderer_BYTES_PER_GLYPH_IMAGE 8L
#undef sun_java2d_d3d_D3DTextRenderer_BYTES_PER_GLYPH_POSITION
#define sun_java2d_d3d_D3DTextRenderer_BYTES_PER_GLYPH_POSITION 8L
#undef sun_java2d_d3d_D3DTextRenderer_OFFSET_CONTRAST
#define sun_java2d_d3d_D3DTextRenderer_OFFSET_CONTRAST 8L
#undef sun_java2d_d3d_D3DTextRenderer_OFFSET_RGBORDER
#define sun_java2d_d3d_D3DTextRenderer_OFFSET_RGBORDER 2L
#undef sun_java2d_d3d_D3DTextRenderer_OFFSET_SUBPIXPOS
#define sun_java2d_d3d_D3DTextRenderer_OFFSET_SUBPIXPOS 1L
#undef sun_java2d_d3d_D3DTextRenderer_OFFSET_POSITIONS
#define sun_java2d_d3d_D3DTextRenderer_OFFSET_POSITIONS 0L
/*
 * Class:     sun_java2d_d3d_D3DTextRenderer
 * Method:    drawGlyphList
 * Signature: (IZZZIFF[J[F)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_d3d_D3DTextRenderer_drawGlyphList
  (JNIEnv *, jobject, jint, jboolean, jboolean, jboolean, jint, jfloat, jfloat, jlongArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
