/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_print_Win32PrintJob */

#ifndef _Included_sun_print_Win32PrintJob
#define _Included_sun_print_Win32PrintJob
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_print_Win32PrintJob_PRINTBUFFERLEN
#define sun_print_Win32PrintJob_PRINTBUFFERLEN 8192L
/*
 * Class:     sun_print_Win32PrintJob
 * Method:    startPrintRawData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_print_Win32PrintJob_startPrintRawData
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sun_print_Win32PrintJob
 * Method:    printRawData
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_print_Win32PrintJob_printRawData
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     sun_print_Win32PrintJob
 * Method:    endPrintRawData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_print_Win32PrintJob_endPrintRawData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
