/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WEmbeddedFramePeer */

#ifndef _Included_sun_awt_windows_WEmbeddedFramePeer
#define _Included_sun_awt_windows_WEmbeddedFramePeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WEmbeddedFramePeer_BANDING_DIVISOR
#define sun_awt_windows_WEmbeddedFramePeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WEmbeddedFramePeer
 * Method:    create
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WEmbeddedFramePeer_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WEmbeddedFramePeer
 * Method:    getBoundsPrivate
 * Signature: ()Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_windows_WEmbeddedFramePeer_getBoundsPrivate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
