/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WDesktopProperties */

#ifndef _Included_sun_awt_windows_WDesktopProperties
#define _Included_sun_awt_windows_WDesktopProperties
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WDesktopProperties
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDesktopProperties_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WDesktopProperties
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDesktopProperties_init
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WDesktopProperties
 * Method:    getWindowsParameters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDesktopProperties_getWindowsParameters
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WDesktopProperties
 * Method:    playWindowsSound
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDesktopProperties_playWindowsSound
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
