/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WDropTargetContextPeerFileStream */

#ifndef _Included_sun_awt_windows_WDropTargetContextPeerFileStream
#define _Included_sun_awt_windows_WDropTargetContextPeerFileStream
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WDropTargetContextPeerFileStream_MAX_SKIP_BUFFER_SIZE
#define sun_awt_windows_WDropTargetContextPeerFileStream_MAX_SKIP_BUFFER_SIZE 2048L
#undef sun_awt_windows_WDropTargetContextPeerFileStream_DEFAULT_BUFFER_SIZE
#define sun_awt_windows_WDropTargetContextPeerFileStream_DEFAULT_BUFFER_SIZE 8192L
#undef sun_awt_windows_WDropTargetContextPeerFileStream_MAX_BUFFER_SIZE
#define sun_awt_windows_WDropTargetContextPeerFileStream_MAX_BUFFER_SIZE 2147483639L
#undef sun_awt_windows_WDropTargetContextPeerFileStream_DEFAULT_BUFFER_SIZE
#define sun_awt_windows_WDropTargetContextPeerFileStream_DEFAULT_BUFFER_SIZE 8192L
/*
 * Class:     sun_awt_windows_WDropTargetContextPeerFileStream
 * Method:    freeStgMedium
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDropTargetContextPeerFileStream_freeStgMedium
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
