/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WPageDialogPeer */

#ifndef _Included_sun_awt_windows_WPageDialogPeer
#define _Included_sun_awt_windows_WPageDialogPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WPageDialogPeer_BANDING_DIVISOR
#define sun_awt_windows_WPageDialogPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WPageDialogPeer
 * Method:    _show
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WPageDialogPeer__1show
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
