/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WInputMethodDescriptor */

#ifndef _Included_sun_awt_windows_WInputMethodDescriptor
#define _Included_sun_awt_windows_WInputMethodDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WInputMethodDescriptor
 * Method:    getNativeAvailableLocales
 * Signature: ()[Ljava/util/Locale;
 */
JNIEXPORT jobjectArray JNICALL Java_sun_awt_windows_WInputMethodDescriptor_getNativeAvailableLocales
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
