/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class sun_awt_windows_WPageDialog */

#ifndef _Included_sun_awt_windows_WPageDialog
#define _Included_sun_awt_windows_WPageDialog
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WPageDialog_FOCUS_TRAVERSABLE_UNKNOWN
#define sun_awt_windows_WPageDialog_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef sun_awt_windows_WPageDialog_FOCUS_TRAVERSABLE_DEFAULT
#define sun_awt_windows_WPageDialog_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef sun_awt_windows_WPageDialog_FOCUS_TRAVERSABLE_SET
#define sun_awt_windows_WPageDialog_FOCUS_TRAVERSABLE_SET 2L
#undef sun_awt_windows_WPageDialog_TOP_ALIGNMENT
#define sun_awt_windows_WPageDialog_TOP_ALIGNMENT 0.0f
#undef sun_awt_windows_WPageDialog_CENTER_ALIGNMENT
#define sun_awt_windows_WPageDialog_CENTER_ALIGNMENT 0.5f
#undef sun_awt_windows_WPageDialog_BOTTOM_ALIGNMENT
#define sun_awt_windows_WPageDialog_BOTTOM_ALIGNMENT 1.0f
#undef sun_awt_windows_WPageDialog_LEFT_ALIGNMENT
#define sun_awt_windows_WPageDialog_LEFT_ALIGNMENT 0.0f
#undef sun_awt_windows_WPageDialog_RIGHT_ALIGNMENT
#define sun_awt_windows_WPageDialog_RIGHT_ALIGNMENT 1.0f
#undef sun_awt_windows_WPageDialog_serialVersionUID
#define sun_awt_windows_WPageDialog_serialVersionUID $LL(-7644114512714619750)
#undef sun_awt_windows_WPageDialog_serialVersionUID
#define sun_awt_windows_WPageDialog_serialVersionUID $LL(4613797578919906343)
#undef sun_awt_windows_WPageDialog_INCLUDE_SELF
#define sun_awt_windows_WPageDialog_INCLUDE_SELF 1L
#undef sun_awt_windows_WPageDialog_SEARCH_HEAVYWEIGHTS
#define sun_awt_windows_WPageDialog_SEARCH_HEAVYWEIGHTS 1L
#undef sun_awt_windows_WPageDialog_OPENED
#define sun_awt_windows_WPageDialog_OPENED 1L
#undef sun_awt_windows_WPageDialog_serialVersionUID
#define sun_awt_windows_WPageDialog_serialVersionUID $LL(4497834738069338734)
#undef sun_awt_windows_WPageDialog_serialVersionUID
#define sun_awt_windows_WPageDialog_serialVersionUID $LL(5920926903803293709)
/*
 * Class:     sun_awt_windows_WPageDialog
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPageDialog_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
