/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_windows_GDIBlitLoops */

#ifndef _Included_sun_java2d_windows_GDIBlitLoops
#define _Included_sun_java2d_windows_GDIBlitLoops
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_java2d_windows_GDIBlitLoops_TRACELOG
#define sun_java2d_windows_GDIBlitLoops_TRACELOG 1L
#undef sun_java2d_windows_GDIBlitLoops_TRACETIMESTAMP
#define sun_java2d_windows_GDIBlitLoops_TRACETIMESTAMP 2L
#undef sun_java2d_windows_GDIBlitLoops_TRACECOUNTS
#define sun_java2d_windows_GDIBlitLoops_TRACECOUNTS 4L
/*
 * Class:     sun_java2d_windows_GDIBlitLoops
 * Method:    nativeBlit
 * Signature: (Lsun/java2d/SurfaceData;Lsun/java2d/SurfaceData;Lsun/java2d/pipe/Region;IIIIIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIBlitLoops_nativeBlit
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
