/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_windows_GDIRenderer */

#ifndef _Included_sun_java2d_windows_GDIRenderer
#define _Included_sun_java2d_windows_GDIRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doDrawLine
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;IIIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doDrawLine
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doDrawRect
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;IIIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doDrawRect
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doDrawRoundRect
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;IIIIIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doDrawRoundRect
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doDrawOval
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;IIIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doDrawOval
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doDrawArc
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;IIIIIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doDrawArc
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doDrawPoly
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;III[I[IIZ)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doDrawPoly
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jintArray, jintArray, jint, jboolean);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doFillRect
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;IIIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doFillRect
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doFillRoundRect
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;IIIIIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doFillRoundRect
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doFillOval
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;IIIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doFillOval
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doFillArc
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;IIIIIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doFillArc
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doFillPoly
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;III[I[II)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doFillPoly
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    doShape
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;Lsun/java2d/pipe/Region;Ljava/awt/Composite;IIILjava/awt/geom/Path2D/Float;Z)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_doShape
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint, jint, jobject, jboolean);

/*
 * Class:     sun_java2d_windows_GDIRenderer
 * Method:    devCopyArea
 * Signature: (Lsun/java2d/windows/GDIWindowSurfaceData;IIIIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIRenderer_devCopyArea
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
