/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WPopupMenuPeer */

#ifndef _Included_sun_awt_windows_WPopupMenuPeer
#define _Included_sun_awt_windows_WPopupMenuPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WPopupMenuPeer
 * Method:    createMenu
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPopupMenuPeer_createMenu
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WPopupMenuPeer
 * Method:    _show
 * Signature: (Ljava/awt/Event;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPopupMenuPeer__1show
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
