/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WRobotPeer */

#ifndef _Included_sun_awt_windows_WRobotPeer
#define _Included_sun_awt_windows_WRobotPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WRobotPeer
 * Method:    mouseMoveImpl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WRobotPeer_mouseMoveImpl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     sun_awt_windows_WRobotPeer
 * Method:    mousePress
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WRobotPeer_mousePress
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WRobotPeer
 * Method:    mouseRelease
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WRobotPeer_mouseRelease
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WRobotPeer
 * Method:    mouseWheel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WRobotPeer_mouseWheel
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WRobotPeer
 * Method:    keyPress
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WRobotPeer_keyPress
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WRobotPeer
 * Method:    keyRelease
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WRobotPeer_keyRelease
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WRobotPeer
 * Method:    getRGBPixels
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WRobotPeer_getRGBPixels
  (JNIEnv *, jobject, jint, jint, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
