/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_d3d_D3DBlitLoops */

#ifndef _Included_sun_java2d_d3d_D3DBlitLoops
#define _Included_sun_java2d_d3d_D3DBlitLoops
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_java2d_d3d_D3DBlitLoops_OFFSET_SRCTYPE
#define sun_java2d_d3d_D3DBlitLoops_OFFSET_SRCTYPE 16L
#undef sun_java2d_d3d_D3DBlitLoops_OFFSET_HINT
#define sun_java2d_d3d_D3DBlitLoops_OFFSET_HINT 8L
#undef sun_java2d_d3d_D3DBlitLoops_OFFSET_TEXTURE
#define sun_java2d_d3d_D3DBlitLoops_OFFSET_TEXTURE 3L
#undef sun_java2d_d3d_D3DBlitLoops_OFFSET_RTT
#define sun_java2d_d3d_D3DBlitLoops_OFFSET_RTT 2L
#undef sun_java2d_d3d_D3DBlitLoops_OFFSET_XFORM
#define sun_java2d_d3d_D3DBlitLoops_OFFSET_XFORM 1L
#undef sun_java2d_d3d_D3DBlitLoops_OFFSET_ISOBLIT
#define sun_java2d_d3d_D3DBlitLoops_OFFSET_ISOBLIT 0L
#ifdef __cplusplus
}
#endif
#endif
