/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WDropTargetContextPeerIStream */

#ifndef _Included_sun_awt_windows_WDropTargetContextPeerIStream
#define _Included_sun_awt_windows_WDropTargetContextPeerIStream
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WDropTargetContextPeerIStream_MAX_SKIP_BUFFER_SIZE
#define sun_awt_windows_WDropTargetContextPeerIStream_MAX_SKIP_BUFFER_SIZE 2048L
#undef sun_awt_windows_WDropTargetContextPeerIStream_DEFAULT_BUFFER_SIZE
#define sun_awt_windows_WDropTargetContextPeerIStream_DEFAULT_BUFFER_SIZE 8192L
#undef sun_awt_windows_WDropTargetContextPeerIStream_MAX_BUFFER_SIZE
#define sun_awt_windows_WDropTargetContextPeerIStream_MAX_BUFFER_SIZE 2147483639L
/*
 * Class:     sun_awt_windows_WDropTargetContextPeerIStream
 * Method:    Available
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WDropTargetContextPeerIStream_Available
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WDropTargetContextPeerIStream
 * Method:    Read
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WDropTargetContextPeerIStream_Read
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WDropTargetContextPeerIStream
 * Method:    ReadBytes
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WDropTargetContextPeerIStream_ReadBytes
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     sun_awt_windows_WDropTargetContextPeerIStream
 * Method:    Close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDropTargetContextPeerIStream_Close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
