/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class sun_awt_windows_WCustomCursor */

#ifndef _Included_sun_awt_windows_WCustomCursor
#define _Included_sun_awt_windows_WCustomCursor
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WCustomCursor_DEFAULT_CURSOR
#define sun_awt_windows_WCustomCursor_DEFAULT_CURSOR 0L
#undef sun_awt_windows_WCustomCursor_CROSSHAIR_CURSOR
#define sun_awt_windows_WCustomCursor_CROSSHAIR_CURSOR 1L
#undef sun_awt_windows_WCustomCursor_TEXT_CURSOR
#define sun_awt_windows_WCustomCursor_TEXT_CURSOR 2L
#undef sun_awt_windows_WCustomCursor_WAIT_CURSOR
#define sun_awt_windows_WCustomCursor_WAIT_CURSOR 3L
#undef sun_awt_windows_WCustomCursor_SW_RESIZE_CURSOR
#define sun_awt_windows_WCustomCursor_SW_RESIZE_CURSOR 4L
#undef sun_awt_windows_WCustomCursor_SE_RESIZE_CURSOR
#define sun_awt_windows_WCustomCursor_SE_RESIZE_CURSOR 5L
#undef sun_awt_windows_WCustomCursor_NW_RESIZE_CURSOR
#define sun_awt_windows_WCustomCursor_NW_RESIZE_CURSOR 6L
#undef sun_awt_windows_WCustomCursor_NE_RESIZE_CURSOR
#define sun_awt_windows_WCustomCursor_NE_RESIZE_CURSOR 7L
#undef sun_awt_windows_WCustomCursor_N_RESIZE_CURSOR
#define sun_awt_windows_WCustomCursor_N_RESIZE_CURSOR 8L
#undef sun_awt_windows_WCustomCursor_S_RESIZE_CURSOR
#define sun_awt_windows_WCustomCursor_S_RESIZE_CURSOR 9L
#undef sun_awt_windows_WCustomCursor_W_RESIZE_CURSOR
#define sun_awt_windows_WCustomCursor_W_RESIZE_CURSOR 10L
#undef sun_awt_windows_WCustomCursor_E_RESIZE_CURSOR
#define sun_awt_windows_WCustomCursor_E_RESIZE_CURSOR 11L
#undef sun_awt_windows_WCustomCursor_HAND_CURSOR
#define sun_awt_windows_WCustomCursor_HAND_CURSOR 12L
#undef sun_awt_windows_WCustomCursor_MOVE_CURSOR
#define sun_awt_windows_WCustomCursor_MOVE_CURSOR 13L
#undef sun_awt_windows_WCustomCursor_CUSTOM_CURSOR
#define sun_awt_windows_WCustomCursor_CUSTOM_CURSOR -1L
#undef sun_awt_windows_WCustomCursor_serialVersionUID
#define sun_awt_windows_WCustomCursor_serialVersionUID $LL(8028237497568985504)
/*
 * Class:     sun_awt_windows_WCustomCursor
 * Method:    createCursorIndirect
 * Signature: ([I[BIIIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WCustomCursor_createCursorIndirect
  (JNIEnv *, jobject, jintArray, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WCustomCursor
 * Method:    getCursorWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WCustomCursor_getCursorWidth
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WCustomCursor
 * Method:    getCursorHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WCustomCursor_getCursorHeight
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
