/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WFramePeer */

#ifndef _Included_sun_awt_windows_WFramePeer
#define _Included_sun_awt_windows_WFramePeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WFramePeer_BANDING_DIVISOR
#define sun_awt_windows_WFramePeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WFramePeer
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFramePeer_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WFramePeer
 * Method:    setState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFramePeer_setState
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WFramePeer
 * Method:    getState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WFramePeer_getState
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WFramePeer
 * Method:    setMaximizedBounds
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFramePeer_setMaximizedBounds
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WFramePeer
 * Method:    clearMaximizedBounds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFramePeer_clearMaximizedBounds
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WFramePeer
 * Method:    setMenuBar0
 * Signature: (Lsun/awt/windows/WMenuBarPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFramePeer_setMenuBar0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WFramePeer
 * Method:    createAwtFrame
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFramePeer_createAwtFrame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WFramePeer
 * Method:    getSysMenuHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WFramePeer_getSysMenuHeight
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WFramePeer
 * Method:    pSetIMMOption
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFramePeer_pSetIMMOption
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_awt_windows_WFramePeer
 * Method:    synthesizeWmActivate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFramePeer_synthesizeWmActivate
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
