/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WDesktopPeer */

#ifndef _Included_sun_awt_windows_WDesktopPeer
#define _Included_sun_awt_windows_WDesktopPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WDesktopPeer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDesktopPeer_init
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WDesktopPeer
 * Method:    ShellExecute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_windows_WDesktopPeer_ShellExecute
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     sun_awt_windows_WDesktopPeer
 * Method:    setSuddenTerminationEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDesktopPeer_setSuddenTerminationEnabled
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     sun_awt_windows_WDesktopPeer
 * Method:    moveToTrash
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WDesktopPeer_moveToTrash
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
