/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_d3d_D3DRenderQueue */

#ifndef _Included_sun_java2d_d3d_D3DRenderQueue
#define _Included_sun_java2d_d3d_D3DRenderQueue
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_java2d_d3d_D3DRenderQueue_BUFFER_SIZE
#define sun_java2d_d3d_D3DRenderQueue_BUFFER_SIZE 32000L
/*
 * Class:     sun_java2d_d3d_D3DRenderQueue
 * Method:    flushBuffer
 * Signature: (JILjava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_d3d_D3DRenderQueue_flushBuffer
  (JNIEnv *, jobject, jlong, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
