/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_windows_WindowsFlags */

#ifndef _Included_sun_java2d_windows_WindowsFlags
#define _Included_sun_java2d_windows_WindowsFlags
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_java2d_windows_WindowsFlags
 * Method:    initNativeFlags
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_java2d_windows_WindowsFlags_initNativeFlags
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
