/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WListPeer */

#ifndef _Included_sun_awt_windows_WListPeer
#define _Included_sun_awt_windows_WListPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WListPeer_BANDING_DIVISOR
#define sun_awt_windows_WListPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WListPeer
 * Method:    addItems
 * Signature: ([Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WListPeer_addItems
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     sun_awt_windows_WListPeer
 * Method:    delItems
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WListPeer_delItems
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     sun_awt_windows_WListPeer
 * Method:    select
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WListPeer_select
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WListPeer
 * Method:    deselect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WListPeer_deselect
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WListPeer
 * Method:    makeVisible
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WListPeer_makeVisible
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WListPeer
 * Method:    setMultipleSelections
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WListPeer_setMultipleSelections
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sun_awt_windows_WListPeer
 * Method:    getMaxWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WListPeer_getMaxWidth
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WListPeer
 * Method:    create
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WListPeer_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WListPeer
 * Method:    updateMaxItemWidth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WListPeer_updateMaxItemWidth
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WListPeer
 * Method:    isSelected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WListPeer_isSelected
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
