/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WObjectPeer */

#ifndef _Included_sun_awt_windows_WObjectPeer
#define _Included_sun_awt_windows_WObjectPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WObjectPeer
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WObjectPeer_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
