/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_d3d_D3DMaskFill */

#ifndef _Included_sun_java2d_d3d_D3DMaskFill
#define _Included_sun_java2d_d3d_D3DMaskFill
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_java2d_d3d_D3DMaskFill_TRACELOG
#define sun_java2d_d3d_D3DMaskFill_TRACELOG 1L
#undef sun_java2d_d3d_D3DMaskFill_TRACETIMESTAMP
#define sun_java2d_d3d_D3DMaskFill_TRACETIMESTAMP 2L
#undef sun_java2d_d3d_D3DMaskFill_TRACECOUNTS
#define sun_java2d_d3d_D3DMaskFill_TRACECOUNTS 4L
/*
 * Class:     sun_java2d_d3d_D3DMaskFill
 * Method:    maskFill
 * Signature: (IIIIIII[B)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_d3d_D3DMaskFill_maskFill
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
