/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_print_PrintServiceLookupProvider */

#ifndef _Included_sun_print_PrintServiceLookupProvider
#define _Included_sun_print_PrintServiceLookupProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_print_PrintServiceLookupProvider
 * Method:    getDefaultPrinterName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_print_PrintServiceLookupProvider_getDefaultPrinterName
  (JNIEnv *, jobject);

/*
 * Class:     sun_print_PrintServiceLookupProvider
 * Method:    getAllPrinterNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_sun_print_PrintServiceLookupProvider_getAllPrinterNames
  (JNIEnv *, jobject);

/*
 * Class:     sun_print_PrintServiceLookupProvider
 * Method:    notifyLocalPrinterChange
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_print_PrintServiceLookupProvider_notifyLocalPrinterChange
  (JNIEnv *, jobject);

/*
 * Class:     sun_print_PrintServiceLookupProvider
 * Method:    notifyRemotePrinterChange
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_print_PrintServiceLookupProvider_notifyRemotePrinterChange
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
