/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WTaskbarPeer */

#ifndef _Included_sun_awt_windows_WTaskbarPeer
#define _Included_sun_awt_windows_WTaskbarPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WTaskbarPeer
 * Method:    nativeInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WTaskbarPeer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WTaskbarPeer
 * Method:    setProgressValue
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTaskbarPeer_setProgressValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     sun_awt_windows_WTaskbarPeer
 * Method:    setProgressState
 * Signature: (JLjava/awt/Taskbar/State;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTaskbarPeer_setProgressState
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     sun_awt_windows_WTaskbarPeer
 * Method:    setOverlayIcon
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTaskbarPeer_setOverlayIcon
  (JNIEnv *, jobject, jlong, jintArray, jint, jint);

/*
 * Class:     sun_awt_windows_WTaskbarPeer
 * Method:    flashWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTaskbarPeer_flashWindow
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
