/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WMenuItemPeer */

#ifndef _Included_sun_awt_windows_WMenuItemPeer
#define _Included_sun_awt_windows_WMenuItemPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WMenuItemPeer
 * Method:    _dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuItemPeer__1dispose
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WMenuItemPeer
 * Method:    _setLabel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuItemPeer__1setLabel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_awt_windows_WMenuItemPeer
 * Method:    create
 * Signature: (Lsun/awt/windows/WMenuPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuItemPeer_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WMenuItemPeer
 * Method:    enable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuItemPeer_enable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sun_awt_windows_WMenuItemPeer
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuItemPeer_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WMenuItemPeer
 * Method:    _setFont
 * Signature: (Ljava/awt/Font;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuItemPeer__1setFont
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
