/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WScrollPanePeer */

#ifndef _Included_sun_awt_windows_WScrollPanePeer
#define _Included_sun_awt_windows_WScrollPanePeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WScrollPanePeer_BANDING_DIVISOR
#define sun_awt_windows_WScrollPanePeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WScrollPanePeer
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WScrollPanePeer_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WScrollPanePeer
 * Method:    create
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WScrollPanePeer_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WScrollPanePeer
 * Method:    getOffset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WScrollPanePeer_getOffset
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WScrollPanePeer
 * Method:    setInsets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WScrollPanePeer_setInsets
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WScrollPanePeer
 * Method:    setScrollPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WScrollPanePeer_setScrollPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     sun_awt_windows_WScrollPanePeer
 * Method:    _getHScrollbarHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WScrollPanePeer__1getHScrollbarHeight
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WScrollPanePeer
 * Method:    _getVScrollbarWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WScrollPanePeer__1getVScrollbarWidth
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WScrollPanePeer
 * Method:    setSpans
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WScrollPanePeer_setSpans
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
