/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WTextAreaPeer */

#ifndef _Included_sun_awt_windows_WTextAreaPeer
#define _Included_sun_awt_windows_WTextAreaPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WTextAreaPeer_BANDING_DIVISOR
#define sun_awt_windows_WTextAreaPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WTextAreaPeer
 * Method:    replaceRange
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTextAreaPeer_replaceRange
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     sun_awt_windows_WTextAreaPeer
 * Method:    create
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WTextAreaPeer_create
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
