/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WFileDialogPeer */

#ifndef _Included_sun_awt_windows_WFileDialogPeer
#define _Included_sun_awt_windows_WFileDialogPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WFileDialogPeer_BANDING_DIVISOR
#define sun_awt_windows_WFileDialogPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WFileDialogPeer
 * Method:    setFilterString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFileDialogPeer_setFilterString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     sun_awt_windows_WFileDialogPeer
 * Method:    _dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFileDialogPeer__1dispose
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WFileDialogPeer
 * Method:    _show
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFileDialogPeer__1show
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WFileDialogPeer
 * Method:    _hide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFileDialogPeer__1hide
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WFileDialogPeer
 * Method:    toFront
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFileDialogPeer_toFront
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WFileDialogPeer
 * Method:    toBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFileDialogPeer_toBack
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WFileDialogPeer
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFileDialogPeer_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WFileDialogPeer
 * Method:    getLocationOnScreen
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_windows_WFileDialogPeer_getLocationOnScreen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
