/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_print_Win32PrintService */

#ifndef _Included_sun_print_Win32PrintService
#define _Included_sun_print_Win32PrintService
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_print_Win32PrintService_DMRES_MEDIUM
#define sun_print_Win32PrintService_DMRES_MEDIUM -3L
#undef sun_print_Win32PrintService_DMRES_HIGH
#define sun_print_Win32PrintService_DMRES_HIGH -4L
#undef sun_print_Win32PrintService_DMORIENT_LANDSCAPE
#define sun_print_Win32PrintService_DMORIENT_LANDSCAPE 2L
#undef sun_print_Win32PrintService_DMDUP_VERTICAL
#define sun_print_Win32PrintService_DMDUP_VERTICAL 2L
#undef sun_print_Win32PrintService_DMDUP_HORIZONTAL
#define sun_print_Win32PrintService_DMDUP_HORIZONTAL 3L
#undef sun_print_Win32PrintService_DMCOLLATE_TRUE
#define sun_print_Win32PrintService_DMCOLLATE_TRUE 1L
#undef sun_print_Win32PrintService_DMCOLOR_MONOCHROME
#define sun_print_Win32PrintService_DMCOLOR_MONOCHROME 1L
#undef sun_print_Win32PrintService_DMCOLOR_COLOR
#define sun_print_Win32PrintService_DMCOLOR_COLOR 2L
#undef sun_print_Win32PrintService_DMPAPER_A2
#define sun_print_Win32PrintService_DMPAPER_A2 66L
#undef sun_print_Win32PrintService_DMPAPER_A6
#define sun_print_Win32PrintService_DMPAPER_A6 70L
#undef sun_print_Win32PrintService_DMPAPER_B6_JIS
#define sun_print_Win32PrintService_DMPAPER_B6_JIS 88L
#undef sun_print_Win32PrintService_DEVCAP_COLOR
#define sun_print_Win32PrintService_DEVCAP_COLOR 1L
#undef sun_print_Win32PrintService_DEVCAP_DUPLEX
#define sun_print_Win32PrintService_DEVCAP_DUPLEX 2L
#undef sun_print_Win32PrintService_DEVCAP_COLLATE
#define sun_print_Win32PrintService_DEVCAP_COLLATE 4L
#undef sun_print_Win32PrintService_DEVCAP_QUALITY
#define sun_print_Win32PrintService_DEVCAP_QUALITY 8L
#undef sun_print_Win32PrintService_DEVCAP_POSTSCRIPT
#define sun_print_Win32PrintService_DEVCAP_POSTSCRIPT 16L
/*
 * Class:     sun_print_Win32PrintService
 * Method:    getAllMediaIDs
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_sun_print_Win32PrintService_getAllMediaIDs
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sun_print_Win32PrintService
 * Method:    getAllMediaSizes
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_sun_print_Win32PrintService_getAllMediaSizes
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sun_print_Win32PrintService
 * Method:    getAllMediaTrays
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_sun_print_Win32PrintService_getAllMediaTrays
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sun_print_Win32PrintService
 * Method:    getMediaPrintableArea
 * Signature: (Ljava/lang/String;I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_sun_print_Win32PrintService_getMediaPrintableArea
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     sun_print_Win32PrintService
 * Method:    getAllMediaNames
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_sun_print_Win32PrintService_getAllMediaNames
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sun_print_Win32PrintService
 * Method:    getAllMediaTrayNames
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_sun_print_Win32PrintService_getAllMediaTrayNames
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sun_print_Win32PrintService
 * Method:    getCopiesSupported
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sun_print_Win32PrintService_getCopiesSupported
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sun_print_Win32PrintService
 * Method:    getAllResolutions
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_sun_print_Win32PrintService_getAllResolutions
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sun_print_Win32PrintService
 * Method:    getCapabilities
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sun_print_Win32PrintService_getCapabilities
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sun_print_Win32PrintService
 * Method:    getDefaultSettings
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_sun_print_Win32PrintService_getDefaultSettings
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sun_print_Win32PrintService
 * Method:    getJobStatus
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_sun_print_Win32PrintService_getJobStatus
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     sun_print_Win32PrintService
 * Method:    getPrinterPort
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_print_Win32PrintService_getPrinterPort
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
