/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_Win32GraphicsConfig */

#ifndef _Included_sun_awt_Win32GraphicsConfig
#define _Included_sun_awt_Win32GraphicsConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_Win32GraphicsConfig
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_Win32GraphicsConfig_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_Win32GraphicsConfig
 * Method:    getBounds
 * Signature: (I)Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_Win32GraphicsConfig_getBounds
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
