/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WKeyboardFocusManagerPeer */

#ifndef _Included_sun_awt_windows_WKeyboardFocusManagerPeer
#define _Included_sun_awt_windows_WKeyboardFocusManagerPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WKeyboardFocusManagerPeer_SNFH_FAILURE
#define sun_awt_windows_WKeyboardFocusManagerPeer_SNFH_FAILURE 0L
#undef sun_awt_windows_WKeyboardFocusManagerPeer_SNFH_SUCCESS_HANDLED
#define sun_awt_windows_WKeyboardFocusManagerPeer_SNFH_SUCCESS_HANDLED 1L
#undef sun_awt_windows_WKeyboardFocusManagerPeer_SNFH_SUCCESS_PROCEED
#define sun_awt_windows_WKeyboardFocusManagerPeer_SNFH_SUCCESS_PROCEED 2L
/*
 * Class:     sun_awt_windows_WKeyboardFocusManagerPeer
 * Method:    setNativeFocusOwner
 * Signature: (Ljava/awt/peer/ComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WKeyboardFocusManagerPeer_setNativeFocusOwner
  (JNIEnv *, jclass, jobject);

/*
 * Class:     sun_awt_windows_WKeyboardFocusManagerPeer
 * Method:    getNativeFocusOwner
 * Signature: ()Ljava/awt/Component;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_windows_WKeyboardFocusManagerPeer_getNativeFocusOwner
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WKeyboardFocusManagerPeer
 * Method:    getNativeFocusedWindow
 * Signature: ()Ljava/awt/Window;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_windows_WKeyboardFocusManagerPeer_getNativeFocusedWindow
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
