/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WMenuPeer */

#ifndef _Included_sun_awt_windows_WMenuPeer
#define _Included_sun_awt_windows_WMenuPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WMenuPeer
 * Method:    delItem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuPeer_delItem
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WMenuPeer
 * Method:    createMenu
 * Signature: (Lsun/awt/windows/WMenuBarPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuPeer_createMenu
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WMenuPeer
 * Method:    createSubMenu
 * Signature: (Lsun/awt/windows/WMenuPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuPeer_createSubMenu
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
