/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_windows_GDIWindowSurfaceData */

#ifndef _Included_sun_java2d_windows_GDIWindowSurfaceData
#define _Included_sun_java2d_windows_GDIWindowSurfaceData
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_java2d_windows_GDIWindowSurfaceData_LOOP_UNKNOWN
#define sun_java2d_windows_GDIWindowSurfaceData_LOOP_UNKNOWN 0L
#undef sun_java2d_windows_GDIWindowSurfaceData_LOOP_FOUND
#define sun_java2d_windows_GDIWindowSurfaceData_LOOP_FOUND 1L
#undef sun_java2d_windows_GDIWindowSurfaceData_LOOP_NOTFOUND
#define sun_java2d_windows_GDIWindowSurfaceData_LOOP_NOTFOUND 2L
/*
 * Class:     sun_java2d_windows_GDIWindowSurfaceData
 * Method:    initIDs
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIWindowSurfaceData_initIDs
  (JNIEnv *, jclass, jclass);

/*
 * Class:     sun_java2d_windows_GDIWindowSurfaceData
 * Method:    initOps
 * Signature: (Lsun/awt/windows/WComponentPeer;IIIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIWindowSurfaceData_initOps
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     sun_java2d_windows_GDIWindowSurfaceData
 * Method:    invalidateSD
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_java2d_windows_GDIWindowSurfaceData_invalidateSD
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
