/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WToolkitThreadBlockedHandler */

#ifndef _Included_sun_awt_windows_WToolkitThreadBlockedHandler
#define _Included_sun_awt_windows_WToolkitThreadBlockedHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WToolkitThreadBlockedHandler
 * Method:    startSecondaryEventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkitThreadBlockedHandler_startSecondaryEventLoop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
