/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WPrintDialogPeer */

#ifndef _Included_sun_awt_windows_WPrintDialogPeer
#define _Included_sun_awt_windows_WPrintDialogPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WPrintDialogPeer_BANDING_DIVISOR
#define sun_awt_windows_WPrintDialogPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WPrintDialogPeer
 * Method:    _show
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WPrintDialogPeer__1show
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WPrintDialogPeer
 * Method:    toFront
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrintDialogPeer_toFront
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WPrintDialogPeer
 * Method:    toBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrintDialogPeer_toBack
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WPrintDialogPeer
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrintDialogPeer_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
