/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class sun_awt_windows_WPrinterJob */

#ifndef _Included_sun_awt_windows_WPrinterJob
#define _Included_sun_awt_windows_WPrinterJob
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WPrinterJob_PRINTER
#define sun_awt_windows_WPrinterJob_PRINTER 0L
#undef sun_awt_windows_WPrinterJob_FILE
#define sun_awt_windows_WPrinterJob_FILE 1L
#undef sun_awt_windows_WPrinterJob_STREAM
#define sun_awt_windows_WPrinterJob_STREAM 2L
#undef sun_awt_windows_WPrinterJob_MAX_UNKNOWN_PAGES
#define sun_awt_windows_WPrinterJob_MAX_UNKNOWN_PAGES 9999L
#undef sun_awt_windows_WPrinterJob_PD_ALLPAGES
#define sun_awt_windows_WPrinterJob_PD_ALLPAGES 0L
#undef sun_awt_windows_WPrinterJob_PD_SELECTION
#define sun_awt_windows_WPrinterJob_PD_SELECTION 1L
#undef sun_awt_windows_WPrinterJob_PD_PAGENUMS
#define sun_awt_windows_WPrinterJob_PD_PAGENUMS 2L
#undef sun_awt_windows_WPrinterJob_PD_NOSELECTION
#define sun_awt_windows_WPrinterJob_PD_NOSELECTION 4L
#undef sun_awt_windows_WPrinterJob_MAX_BAND_SIZE
#define sun_awt_windows_WPrinterJob_MAX_BAND_SIZE 4194304L
#undef sun_awt_windows_WPrinterJob_DPI
#define sun_awt_windows_WPrinterJob_DPI 72.0f
#undef sun_awt_windows_WPrinterJob_PS_ENDCAP_ROUND
#define sun_awt_windows_WPrinterJob_PS_ENDCAP_ROUND $LL(0)
#undef sun_awt_windows_WPrinterJob_PS_ENDCAP_SQUARE
#define sun_awt_windows_WPrinterJob_PS_ENDCAP_SQUARE $LL(256)
#undef sun_awt_windows_WPrinterJob_PS_ENDCAP_FLAT
#define sun_awt_windows_WPrinterJob_PS_ENDCAP_FLAT $LL(512)
#undef sun_awt_windows_WPrinterJob_PS_JOIN_ROUND
#define sun_awt_windows_WPrinterJob_PS_JOIN_ROUND $LL(0)
#undef sun_awt_windows_WPrinterJob_PS_JOIN_BEVEL
#define sun_awt_windows_WPrinterJob_PS_JOIN_BEVEL $LL(4096)
#undef sun_awt_windows_WPrinterJob_PS_JOIN_MITER
#define sun_awt_windows_WPrinterJob_PS_JOIN_MITER $LL(8192)
#undef sun_awt_windows_WPrinterJob_POLYFILL_ALTERNATE
#define sun_awt_windows_WPrinterJob_POLYFILL_ALTERNATE 1L
#undef sun_awt_windows_WPrinterJob_POLYFILL_WINDING
#define sun_awt_windows_WPrinterJob_POLYFILL_WINDING 2L
#undef sun_awt_windows_WPrinterJob_MAX_WCOLOR
#define sun_awt_windows_WPrinterJob_MAX_WCOLOR 255L
#undef sun_awt_windows_WPrinterJob_SET_DUP_VERTICAL
#define sun_awt_windows_WPrinterJob_SET_DUP_VERTICAL 16L
#undef sun_awt_windows_WPrinterJob_SET_DUP_HORIZONTAL
#define sun_awt_windows_WPrinterJob_SET_DUP_HORIZONTAL 32L
#undef sun_awt_windows_WPrinterJob_SET_RES_HIGH
#define sun_awt_windows_WPrinterJob_SET_RES_HIGH 64L
#undef sun_awt_windows_WPrinterJob_SET_RES_LOW
#define sun_awt_windows_WPrinterJob_SET_RES_LOW 128L
#undef sun_awt_windows_WPrinterJob_SET_COLOR
#define sun_awt_windows_WPrinterJob_SET_COLOR 512L
#undef sun_awt_windows_WPrinterJob_SET_ORIENTATION
#define sun_awt_windows_WPrinterJob_SET_ORIENTATION 16384L
#undef sun_awt_windows_WPrinterJob_SET_COLLATED
#define sun_awt_windows_WPrinterJob_SET_COLLATED 32768L
#undef sun_awt_windows_WPrinterJob_PD_COLLATE
#define sun_awt_windows_WPrinterJob_PD_COLLATE 16L
#undef sun_awt_windows_WPrinterJob_PD_PRINTTOFILE
#define sun_awt_windows_WPrinterJob_PD_PRINTTOFILE 32L
#undef sun_awt_windows_WPrinterJob_DM_ORIENTATION
#define sun_awt_windows_WPrinterJob_DM_ORIENTATION 1L
#undef sun_awt_windows_WPrinterJob_DM_PAPERSIZE
#define sun_awt_windows_WPrinterJob_DM_PAPERSIZE 2L
#undef sun_awt_windows_WPrinterJob_DM_COPIES
#define sun_awt_windows_WPrinterJob_DM_COPIES 256L
#undef sun_awt_windows_WPrinterJob_DM_DEFAULTSOURCE
#define sun_awt_windows_WPrinterJob_DM_DEFAULTSOURCE 512L
#undef sun_awt_windows_WPrinterJob_DM_PRINTQUALITY
#define sun_awt_windows_WPrinterJob_DM_PRINTQUALITY 1024L
#undef sun_awt_windows_WPrinterJob_DM_COLOR
#define sun_awt_windows_WPrinterJob_DM_COLOR 2048L
#undef sun_awt_windows_WPrinterJob_DM_DUPLEX
#define sun_awt_windows_WPrinterJob_DM_DUPLEX 4096L
#undef sun_awt_windows_WPrinterJob_DM_YRESOLUTION
#define sun_awt_windows_WPrinterJob_DM_YRESOLUTION 8192L
#undef sun_awt_windows_WPrinterJob_DM_COLLATE
#define sun_awt_windows_WPrinterJob_DM_COLLATE 32768L
#undef sun_awt_windows_WPrinterJob_DMCOLLATE_FALSE
#define sun_awt_windows_WPrinterJob_DMCOLLATE_FALSE 0L
#undef sun_awt_windows_WPrinterJob_DMCOLLATE_TRUE
#define sun_awt_windows_WPrinterJob_DMCOLLATE_TRUE 1L
#undef sun_awt_windows_WPrinterJob_DMORIENT_PORTRAIT
#define sun_awt_windows_WPrinterJob_DMORIENT_PORTRAIT 1L
#undef sun_awt_windows_WPrinterJob_DMORIENT_LANDSCAPE
#define sun_awt_windows_WPrinterJob_DMORIENT_LANDSCAPE 2L
#undef sun_awt_windows_WPrinterJob_DMCOLOR_MONOCHROME
#define sun_awt_windows_WPrinterJob_DMCOLOR_MONOCHROME 1L
#undef sun_awt_windows_WPrinterJob_DMCOLOR_COLOR
#define sun_awt_windows_WPrinterJob_DMCOLOR_COLOR 2L
#undef sun_awt_windows_WPrinterJob_DMRES_DRAFT
#define sun_awt_windows_WPrinterJob_DMRES_DRAFT -1L
#undef sun_awt_windows_WPrinterJob_DMRES_LOW
#define sun_awt_windows_WPrinterJob_DMRES_LOW -2L
#undef sun_awt_windows_WPrinterJob_DMRES_MEDIUM
#define sun_awt_windows_WPrinterJob_DMRES_MEDIUM -3L
#undef sun_awt_windows_WPrinterJob_DMRES_HIGH
#define sun_awt_windows_WPrinterJob_DMRES_HIGH -4L
#undef sun_awt_windows_WPrinterJob_DMDUP_SIMPLEX
#define sun_awt_windows_WPrinterJob_DMDUP_SIMPLEX 1L
#undef sun_awt_windows_WPrinterJob_DMDUP_VERTICAL
#define sun_awt_windows_WPrinterJob_DMDUP_VERTICAL 2L
#undef sun_awt_windows_WPrinterJob_DMDUP_HORIZONTAL
#define sun_awt_windows_WPrinterJob_DMDUP_HORIZONTAL 3L
#undef sun_awt_windows_WPrinterJob_MAX_UNKNOWN_PAGES
#define sun_awt_windows_WPrinterJob_MAX_UNKNOWN_PAGES 9999L
/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    setNativePrintService
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_setNativePrintService
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    getNativePrintService
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_windows_WPrinterJob_getNativePrintService
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    getDefaultPage
 * Signature: (Ljava/awt/print/PageFormat;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_getDefaultPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    validatePaper
 * Signature: (Ljava/awt/print/Paper;Ljava/awt/print/Paper;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_validatePaper
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    setNativeCopies
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_setNativeCopies
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    jobSetup
 * Signature: (Ljava/awt/print/Pageable;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WPrinterJob_jobSetup
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    initPrinter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_initPrinter
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    _startDoc
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WPrinterJob__1startDoc
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    endDoc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_endDoc
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    abortDoc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_abortDoc
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    deleteDC
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_deleteDC
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    deviceStartPage
 * Signature: (Ljava/awt/print/PageFormat;Ljava/awt/print/Printable;IZ)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_deviceStartPage
  (JNIEnv *, jobject, jobject, jobject, jint, jboolean);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    deviceEndPage
 * Signature: (Ljava/awt/print/PageFormat;Ljava/awt/print/Printable;I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_deviceEndPage
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    printBand
 * Signature: ([BIIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_printBand
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    beginPath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_beginPath
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    endPath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_endPath
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    closeFigure
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_closeFigure
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    fillPath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_fillPath
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    moveTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_moveTo
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    lineTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_lineTo
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    polyBezierTo
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_polyBezierTo
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    setPolyFillMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_setPolyFillMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    setAdvancedGraphicsMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WPrinterJob_setAdvancedGraphicsMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    setGraphicsMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_setGraphicsMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    scale
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_scale
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    getWorldTransform
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_getWorldTransform
  (JNIEnv *, jobject, jlong, jdoubleArray);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    setWorldTransform
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_setWorldTransform
  (JNIEnv *, jobject, jlong, jdoubleArray);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    selectSolidBrush
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_selectSolidBrush
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    getPenX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WPrinterJob_getPenX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    getPenY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WPrinterJob_getPenY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    selectClipPath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_selectClipPath
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    frameRect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_frameRect
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    fillRect
 * Signature: (JFFFFIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_fillRect
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    selectPen
 * Signature: (JFIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_selectPen
  (JNIEnv *, jobject, jlong, jfloat, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    selectStylePen
 * Signature: (JJJFIII)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WPrinterJob_selectStylePen
  (JNIEnv *, jobject, jlong, jlong, jlong, jfloat, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    setFont
 * Signature: (JLjava/lang/String;FZZIF)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WPrinterJob_setFont
  (JNIEnv *, jobject, jlong, jstring, jfloat, jboolean, jboolean, jint, jfloat);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    setTextColor
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_setTextColor
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    textOut
 * Signature: (JLjava/lang/String;IZFF[F)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_textOut
  (JNIEnv *, jobject, jlong, jstring, jint, jboolean, jfloat, jfloat, jfloatArray);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    getGDIAdvance
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WPrinterJob_getGDIAdvance
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    drawDIBImage
 * Signature: (J[BFFFFFFFFI[B)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_drawDIBImage
  (JNIEnv *, jobject, jlong, jbyteArray, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jbyteArray);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    showDocProperties
 * Signature: (JLjavax/print/attribute/PrintRequestAttributeSet;ISSSSSSSSS)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WPrinterJob_showDocProperties
  (JNIEnv *, jobject, jlong, jobject, jint, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort, jshort);

/*
 * Class:     sun_awt_windows_WPrinterJob
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPrinterJob_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
