/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_d3d_D3DPaints_MultiGradient */

#ifndef _Included_sun_java2d_d3d_D3DPaints_MultiGradient
#define _Included_sun_java2d_d3d_D3DPaints_MultiGradient
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_java2d_d3d_D3DPaints_MultiGradient_MULTI_MAX_FRACTIONS_D3D
#define sun_java2d_d3d_D3DPaints_MultiGradient_MULTI_MAX_FRACTIONS_D3D 8L
#ifdef __cplusplus
}
#endif
#endif
