/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WButtonPeer */

#ifndef _Included_sun_awt_windows_WButtonPeer
#define _Included_sun_awt_windows_WButtonPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WButtonPeer_BANDING_DIVISOR
#define sun_awt_windows_WButtonPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WButtonPeer
 * Method:    setLabel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WButtonPeer_setLabel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_awt_windows_WButtonPeer
 * Method:    create
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WButtonPeer_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WButtonPeer
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WButtonPeer_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
