/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WMouseInfoPeer */

#ifndef _Included_sun_awt_windows_WMouseInfoPeer
#define _Included_sun_awt_windows_WMouseInfoPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WMouseInfoPeer
 * Method:    fillPointWithCoords
 * Signature: (Ljava/awt/Point;)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WMouseInfoPeer_fillPointWithCoords
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WMouseInfoPeer
 * Method:    isWindowUnderMouse
 * Signature: (Ljava/awt/Window;)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WMouseInfoPeer_isWindowUnderMouse
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
