/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WGlobalCursorManager */

#ifndef _Included_sun_awt_windows_WGlobalCursorManager
#define _Included_sun_awt_windows_WGlobalCursorManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WGlobalCursorManager
 * Method:    setCursor
 * Signature: (Ljava/awt/Component;Ljava/awt/Cursor;Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WGlobalCursorManager_setCursor
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     sun_awt_windows_WGlobalCursorManager
 * Method:    getCursorPos
 * Signature: (Ljava/awt/Point;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WGlobalCursorManager_getCursorPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WGlobalCursorManager
 * Method:    findHeavyweightUnderCursor
 * Signature: (Z)Ljava/awt/Component;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_windows_WGlobalCursorManager_findHeavyweightUnderCursor
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sun_awt_windows_WGlobalCursorManager
 * Method:    getLocationOnScreen
 * Signature: (Ljava/awt/Component;)Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_windows_WGlobalCursorManager_getLocationOnScreen
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
