/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WDropTargetContextPeer */

#ifndef _Included_sun_awt_windows_WDropTargetContextPeer
#define _Included_sun_awt_windows_WDropTargetContextPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WDropTargetContextPeer_DISPATCH_SYNC
#define sun_awt_windows_WDropTargetContextPeer_DISPATCH_SYNC 1L
#undef sun_awt_windows_WDropTargetContextPeer_STATUS_NONE
#define sun_awt_windows_WDropTargetContextPeer_STATUS_NONE 0L
#undef sun_awt_windows_WDropTargetContextPeer_STATUS_WAIT
#define sun_awt_windows_WDropTargetContextPeer_STATUS_WAIT 1L
#undef sun_awt_windows_WDropTargetContextPeer_STATUS_ACCEPT
#define sun_awt_windows_WDropTargetContextPeer_STATUS_ACCEPT 2L
#undef sun_awt_windows_WDropTargetContextPeer_STATUS_REJECT
#define sun_awt_windows_WDropTargetContextPeer_STATUS_REJECT -1L
/*
 * Class:     sun_awt_windows_WDropTargetContextPeer
 * Method:    getData
 * Signature: (JJ)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_windows_WDropTargetContextPeer_getData
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     sun_awt_windows_WDropTargetContextPeer
 * Method:    dropDone
 * Signature: (JZI)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WDropTargetContextPeer_dropDone
  (JNIEnv *, jobject, jlong, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
