/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WComponentPeer */

#ifndef _Included_sun_awt_windows_WComponentPeer
#define _Included_sun_awt_windows_WComponentPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WComponentPeer_BANDING_DIVISOR
#define sun_awt_windows_WComponentPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    isObscured
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WComponentPeer_isObscured
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    pShow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_pShow
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    hide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_hide
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    enable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_enable
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    disable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_disable
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    getLocationOnScreen
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_windows_WComponentPeer_getLocationOnScreen
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    reshapeNoCheck
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_reshapeNoCheck
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    updateWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_updateWindow
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    createPrintedPixels
 * Signature: (IIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_sun_awt_windows_WComponentPeer_createPrintedPixels
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    reshape
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_reshape
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    nativeHandleEvent
 * Signature: (Ljava/awt/AWTEvent;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_nativeHandleEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    setFocus
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_setFocus
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    _dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer__1dispose
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    _setForeground
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer__1setForeground
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    _setBackground
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer__1setBackground
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    _setFont
 * Signature: (Ljava/awt/Font;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer__1setFont
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_start
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    beginValidate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_beginValidate
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    endValidate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_endValidate
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    addNativeDropTarget
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sun_awt_windows_WComponentPeer_addNativeDropTarget
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    removeNativeDropTarget
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_removeNativeDropTarget
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    nativeHandlesWheelScrolling
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WComponentPeer_nativeHandlesWheelScrolling
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    pSetParent
 * Signature: (Ljava/awt/peer/ComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_pSetParent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    setRectangularShape
 * Signature: (IIIILsun/java2d/pipe/Region;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_setRectangularShape
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     sun_awt_windows_WComponentPeer
 * Method:    setZOrder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WComponentPeer_setZOrder
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
