/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_java2d_d3d_D3DSurfaceData */

#ifndef _Included_sun_java2d_d3d_D3DSurfaceData
#define _Included_sun_java2d_d3d_D3DSurfaceData
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_java2d_d3d_D3DSurfaceData_LOOP_UNKNOWN
#define sun_java2d_d3d_D3DSurfaceData_LOOP_UNKNOWN 0L
#undef sun_java2d_d3d_D3DSurfaceData_LOOP_FOUND
#define sun_java2d_d3d_D3DSurfaceData_LOOP_FOUND 1L
#undef sun_java2d_d3d_D3DSurfaceData_LOOP_NOTFOUND
#define sun_java2d_d3d_D3DSurfaceData_LOOP_NOTFOUND 2L
#undef sun_java2d_d3d_D3DSurfaceData_D3D_DEVICE_RESOURCE
#define sun_java2d_d3d_D3DSurfaceData_D3D_DEVICE_RESOURCE 100L
#undef sun_java2d_d3d_D3DSurfaceData_ST_INT_ARGB
#define sun_java2d_d3d_D3DSurfaceData_ST_INT_ARGB 0L
#undef sun_java2d_d3d_D3DSurfaceData_ST_INT_ARGB_PRE
#define sun_java2d_d3d_D3DSurfaceData_ST_INT_ARGB_PRE 1L
#undef sun_java2d_d3d_D3DSurfaceData_ST_INT_ARGB_BM
#define sun_java2d_d3d_D3DSurfaceData_ST_INT_ARGB_BM 2L
#undef sun_java2d_d3d_D3DSurfaceData_ST_INT_RGB
#define sun_java2d_d3d_D3DSurfaceData_ST_INT_RGB 3L
#undef sun_java2d_d3d_D3DSurfaceData_ST_INT_BGR
#define sun_java2d_d3d_D3DSurfaceData_ST_INT_BGR 4L
#undef sun_java2d_d3d_D3DSurfaceData_ST_USHORT_565_RGB
#define sun_java2d_d3d_D3DSurfaceData_ST_USHORT_565_RGB 5L
#undef sun_java2d_d3d_D3DSurfaceData_ST_USHORT_555_RGB
#define sun_java2d_d3d_D3DSurfaceData_ST_USHORT_555_RGB 6L
#undef sun_java2d_d3d_D3DSurfaceData_ST_BYTE_INDEXED
#define sun_java2d_d3d_D3DSurfaceData_ST_BYTE_INDEXED 7L
#undef sun_java2d_d3d_D3DSurfaceData_ST_BYTE_INDEXED_BM
#define sun_java2d_d3d_D3DSurfaceData_ST_BYTE_INDEXED_BM 8L
#undef sun_java2d_d3d_D3DSurfaceData_ST_3BYTE_BGR
#define sun_java2d_d3d_D3DSurfaceData_ST_3BYTE_BGR 9L
#undef sun_java2d_d3d_D3DSurfaceData_SWAP_DISCARD
#define sun_java2d_d3d_D3DSurfaceData_SWAP_DISCARD 1L
#undef sun_java2d_d3d_D3DSurfaceData_SWAP_FLIP
#define sun_java2d_d3d_D3DSurfaceData_SWAP_FLIP 2L
#undef sun_java2d_d3d_D3DSurfaceData_SWAP_COPY
#define sun_java2d_d3d_D3DSurfaceData_SWAP_COPY 3L
/*
 * Class:     sun_java2d_d3d_D3DSurfaceData
 * Method:    initTexture
 * Signature: (JZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_java2d_d3d_D3DSurfaceData_initTexture
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     sun_java2d_d3d_D3DSurfaceData
 * Method:    initFlipBackbuffer
 * Signature: (JJIII)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_java2d_d3d_D3DSurfaceData_initFlipBackbuffer
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint);

/*
 * Class:     sun_java2d_d3d_D3DSurfaceData
 * Method:    initRTSurface
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_java2d_d3d_D3DSurfaceData_initRTSurface
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     sun_java2d_d3d_D3DSurfaceData
 * Method:    initOps
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_d3d_D3DSurfaceData_initOps
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     sun_java2d_d3d_D3DSurfaceData
 * Method:    dbGetPixelNative
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_sun_java2d_d3d_D3DSurfaceData_dbGetPixelNative
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     sun_java2d_d3d_D3DSurfaceData
 * Method:    dbSetPixelNative
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_sun_java2d_d3d_D3DSurfaceData_dbSetPixelNative
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     sun_java2d_d3d_D3DSurfaceData
 * Method:    getNativeResourceNative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_sun_java2d_d3d_D3DSurfaceData_getNativeResourceNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     sun_java2d_d3d_D3DSurfaceData
 * Method:    updateWindowAccelImpl
 * Signature: (JJII)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_java2d_d3d_D3DSurfaceData_updateWindowAccelImpl
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
