/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WPanelPeer */

#ifndef _Included_sun_awt_windows_WPanelPeer
#define _Included_sun_awt_windows_WPanelPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WPanelPeer_BANDING_DIVISOR
#define sun_awt_windows_WPanelPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WPanelPeer
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WPanelPeer_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
