/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class sun_awt_windows_WFontMetrics */

#ifndef _Included_sun_awt_windows_WFontMetrics
#define _Included_sun_awt_windows_WFontMetrics
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WFontMetrics_serialVersionUID
#define sun_awt_windows_WFontMetrics_serialVersionUID $LL(1681126225205050147)
/*
 * Class:     sun_awt_windows_WFontMetrics
 * Method:    stringWidth
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WFontMetrics_stringWidth
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_awt_windows_WFontMetrics
 * Method:    charsWidth
 * Signature: ([CII)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WFontMetrics_charsWidth
  (JNIEnv *, jobject, jcharArray, jint, jint);

/*
 * Class:     sun_awt_windows_WFontMetrics
 * Method:    bytesWidth
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WFontMetrics_bytesWidth
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     sun_awt_windows_WFontMetrics
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFontMetrics_init
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WFontMetrics
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFontMetrics_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
