/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WToolkit */

#ifndef _Included_sun_awt_windows_WToolkit
#define _Included_sun_awt_windows_WToolkit
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WToolkit_LONG_BITS
#define sun_awt_windows_WToolkit_LONG_BITS 64L
#undef sun_awt_windows_WToolkit_GRAB_EVENT_MASK
#define sun_awt_windows_WToolkit_GRAB_EVENT_MASK -2147483648L
#undef sun_awt_windows_WToolkit_MAX_BUTTONS_SUPPORTED
#define sun_awt_windows_WToolkit_MAX_BUTTONS_SUPPORTED 20L
#undef sun_awt_windows_WToolkit_DEFAULT_WAIT_TIME
#define sun_awt_windows_WToolkit_DEFAULT_WAIT_TIME 10000L
#undef sun_awt_windows_WToolkit_MAX_ITERS
#define sun_awt_windows_WToolkit_MAX_ITERS 100L
#undef sun_awt_windows_WToolkit_MIN_ITERS
#define sun_awt_windows_WToolkit_MIN_ITERS 1L
#undef sun_awt_windows_WToolkit_MINIMAL_DELAY
#define sun_awt_windows_WToolkit_MINIMAL_DELAY 5L
/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    getWindowsVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_windows_WToolkit_getWindowsVersion
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    embeddedInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WToolkit_embeddedInit
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    embeddedDispose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WToolkit_embeddedDispose
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    embeddedEventLoopIdleProcessing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_embeddedEventLoopIdleProcessing
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    postDispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_postDispose
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    startToolkitThread
 * Signature: (Ljava/lang/Runnable;Ljava/lang/ThreadGroup;)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WToolkit_startToolkitThread
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WToolkit_init
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    eventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_eventLoop
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    startSecondaryEventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_startSecondaryEventLoop
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    quitSecondaryEventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_quitSecondaryEventLoop
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    setDynamicLayoutNative
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_setDynamicLayoutNative
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    isDynamicLayoutSupportedNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WToolkit_isDynamicLayoutSupportedNative
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    makeColorModel
 * Signature: ()Ljava/awt/image/ColorModel;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_windows_WToolkit_makeColorModel
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    getScreenInsets
 * Signature: (I)Ljava/awt/Insets;
 */
JNIEXPORT jobject JNICALL Java_sun_awt_windows_WToolkit_getScreenInsets
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    nativeSync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_nativeSync
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    beep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_beep
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    getLockingKeyStateNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WToolkit_getLockingKeyStateNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    setLockingKeyStateNative
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_setLockingKeyStateNative
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    loadSystemColors
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_loadSystemColors
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    getMaximumCursorColors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WToolkit_getMaximumCursorColors
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    showTouchKeyboard
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_showTouchKeyboard
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    hideTouchKeyboard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_hideTouchKeyboard
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    syncNativeQueue
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WToolkit_syncNativeQueue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    setExtraMouseButtonsEnabledNative
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WToolkit_setExtraMouseButtonsEnabledNative
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     sun_awt_windows_WToolkit
 * Method:    getNumberOfButtonsImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_awt_windows_WToolkit_getNumberOfButtonsImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
