/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WMenuBarPeer */

#ifndef _Included_sun_awt_windows_WMenuBarPeer
#define _Included_sun_awt_windows_WMenuBarPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WMenuBarPeer
 * Method:    addMenu
 * Signature: (Ljava/awt/Menu;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuBarPeer_addMenu
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WMenuBarPeer
 * Method:    delMenu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuBarPeer_delMenu
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WMenuBarPeer
 * Method:    create
 * Signature: (Lsun/awt/windows/WFramePeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WMenuBarPeer_create
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
