/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WCheckboxMenuItemPeer */

#ifndef _Included_sun_awt_windows_WCheckboxMenuItemPeer
#define _Included_sun_awt_windows_WCheckboxMenuItemPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WCheckboxMenuItemPeer
 * Method:    setState
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WCheckboxMenuItemPeer_setState
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
