/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WChoicePeer */

#ifndef _Included_sun_awt_windows_WChoicePeer
#define _Included_sun_awt_windows_WChoicePeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WChoicePeer_BANDING_DIVISOR
#define sun_awt_windows_WChoicePeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WChoicePeer
 * Method:    select
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WChoicePeer_select
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WChoicePeer
 * Method:    removeAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WChoicePeer_removeAll
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WChoicePeer
 * Method:    remove
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WChoicePeer_remove
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WChoicePeer
 * Method:    addItems
 * Signature: ([Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WChoicePeer_addItems
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     sun_awt_windows_WChoicePeer
 * Method:    reshape
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WChoicePeer_reshape
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WChoicePeer
 * Method:    create
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WChoicePeer_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WChoicePeer
 * Method:    closeList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WChoicePeer_closeList
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
