/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WFontPeer */

#ifndef _Included_sun_awt_windows_WFontPeer
#define _Included_sun_awt_windows_WFontPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WFontPeer
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WFontPeer_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
