/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_Win32FontManager */

#ifndef _Included_sun_awt_Win32FontManager
#define _Included_sun_awt_Win32FontManager
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_Win32FontManager_FONTFORMAT_NONE
#define sun_awt_Win32FontManager_FONTFORMAT_NONE -1L
#undef sun_awt_Win32FontManager_FONTFORMAT_TRUETYPE
#define sun_awt_Win32FontManager_FONTFORMAT_TRUETYPE 0L
#undef sun_awt_Win32FontManager_FONTFORMAT_TYPE1
#define sun_awt_Win32FontManager_FONTFORMAT_TYPE1 1L
#undef sun_awt_Win32FontManager_FONTFORMAT_TTC
#define sun_awt_Win32FontManager_FONTFORMAT_TTC 2L
#undef sun_awt_Win32FontManager_FONTFORMAT_COMPOSITE
#define sun_awt_Win32FontManager_FONTFORMAT_COMPOSITE 3L
#undef sun_awt_Win32FontManager_FONTFORMAT_NATIVE
#define sun_awt_Win32FontManager_FONTFORMAT_NATIVE 4L
#undef sun_awt_Win32FontManager_CHANNELPOOLSIZE
#define sun_awt_Win32FontManager_CHANNELPOOLSIZE 20L
/*
 * Class:     sun_awt_Win32FontManager
 * Method:    getEUDCFontFile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_Win32FontManager_getEUDCFontFile
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_Win32FontManager
 * Method:    populateFontFileNameMap0
 * Signature: (Ljava/util/HashMap;Ljava/util/HashMap;Ljava/util/HashMap;Ljava/util/Locale;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_Win32FontManager_populateFontFileNameMap0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     sun_awt_Win32FontManager
 * Method:    getFontPath
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_Win32FontManager_getFontPath
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sun_awt_Win32FontManager
 * Method:    registerFontWithPlatform
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_Win32FontManager_registerFontWithPlatform
  (JNIEnv *, jclass, jstring);

/*
 * Class:     sun_awt_Win32FontManager
 * Method:    deRegisterFontWithPlatform
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_Win32FontManager_deRegisterFontWithPlatform
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
