/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class sun_awt_windows_WEmbeddedFrame */

#ifndef _Included_sun_awt_windows_WEmbeddedFrame
#define _Included_sun_awt_windows_WEmbeddedFrame
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WEmbeddedFrame_FOCUS_TRAVERSABLE_UNKNOWN
#define sun_awt_windows_WEmbeddedFrame_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef sun_awt_windows_WEmbeddedFrame_FOCUS_TRAVERSABLE_DEFAULT
#define sun_awt_windows_WEmbeddedFrame_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef sun_awt_windows_WEmbeddedFrame_FOCUS_TRAVERSABLE_SET
#define sun_awt_windows_WEmbeddedFrame_FOCUS_TRAVERSABLE_SET 2L
#undef sun_awt_windows_WEmbeddedFrame_TOP_ALIGNMENT
#define sun_awt_windows_WEmbeddedFrame_TOP_ALIGNMENT 0.0f
#undef sun_awt_windows_WEmbeddedFrame_CENTER_ALIGNMENT
#define sun_awt_windows_WEmbeddedFrame_CENTER_ALIGNMENT 0.5f
#undef sun_awt_windows_WEmbeddedFrame_BOTTOM_ALIGNMENT
#define sun_awt_windows_WEmbeddedFrame_BOTTOM_ALIGNMENT 1.0f
#undef sun_awt_windows_WEmbeddedFrame_LEFT_ALIGNMENT
#define sun_awt_windows_WEmbeddedFrame_LEFT_ALIGNMENT 0.0f
#undef sun_awt_windows_WEmbeddedFrame_RIGHT_ALIGNMENT
#define sun_awt_windows_WEmbeddedFrame_RIGHT_ALIGNMENT 1.0f
#undef sun_awt_windows_WEmbeddedFrame_serialVersionUID
#define sun_awt_windows_WEmbeddedFrame_serialVersionUID $LL(-7644114512714619750)
#undef sun_awt_windows_WEmbeddedFrame_serialVersionUID
#define sun_awt_windows_WEmbeddedFrame_serialVersionUID $LL(4613797578919906343)
#undef sun_awt_windows_WEmbeddedFrame_INCLUDE_SELF
#define sun_awt_windows_WEmbeddedFrame_INCLUDE_SELF 1L
#undef sun_awt_windows_WEmbeddedFrame_SEARCH_HEAVYWEIGHTS
#define sun_awt_windows_WEmbeddedFrame_SEARCH_HEAVYWEIGHTS 1L
#undef sun_awt_windows_WEmbeddedFrame_OPENED
#define sun_awt_windows_WEmbeddedFrame_OPENED 1L
#undef sun_awt_windows_WEmbeddedFrame_serialVersionUID
#define sun_awt_windows_WEmbeddedFrame_serialVersionUID $LL(4497834738069338734)
#undef sun_awt_windows_WEmbeddedFrame_DEFAULT_CURSOR
#define sun_awt_windows_WEmbeddedFrame_DEFAULT_CURSOR 0L
#undef sun_awt_windows_WEmbeddedFrame_CROSSHAIR_CURSOR
#define sun_awt_windows_WEmbeddedFrame_CROSSHAIR_CURSOR 1L
#undef sun_awt_windows_WEmbeddedFrame_TEXT_CURSOR
#define sun_awt_windows_WEmbeddedFrame_TEXT_CURSOR 2L
#undef sun_awt_windows_WEmbeddedFrame_WAIT_CURSOR
#define sun_awt_windows_WEmbeddedFrame_WAIT_CURSOR 3L
#undef sun_awt_windows_WEmbeddedFrame_SW_RESIZE_CURSOR
#define sun_awt_windows_WEmbeddedFrame_SW_RESIZE_CURSOR 4L
#undef sun_awt_windows_WEmbeddedFrame_SE_RESIZE_CURSOR
#define sun_awt_windows_WEmbeddedFrame_SE_RESIZE_CURSOR 5L
#undef sun_awt_windows_WEmbeddedFrame_NW_RESIZE_CURSOR
#define sun_awt_windows_WEmbeddedFrame_NW_RESIZE_CURSOR 6L
#undef sun_awt_windows_WEmbeddedFrame_NE_RESIZE_CURSOR
#define sun_awt_windows_WEmbeddedFrame_NE_RESIZE_CURSOR 7L
#undef sun_awt_windows_WEmbeddedFrame_N_RESIZE_CURSOR
#define sun_awt_windows_WEmbeddedFrame_N_RESIZE_CURSOR 8L
#undef sun_awt_windows_WEmbeddedFrame_S_RESIZE_CURSOR
#define sun_awt_windows_WEmbeddedFrame_S_RESIZE_CURSOR 9L
#undef sun_awt_windows_WEmbeddedFrame_W_RESIZE_CURSOR
#define sun_awt_windows_WEmbeddedFrame_W_RESIZE_CURSOR 10L
#undef sun_awt_windows_WEmbeddedFrame_E_RESIZE_CURSOR
#define sun_awt_windows_WEmbeddedFrame_E_RESIZE_CURSOR 11L
#undef sun_awt_windows_WEmbeddedFrame_HAND_CURSOR
#define sun_awt_windows_WEmbeddedFrame_HAND_CURSOR 12L
#undef sun_awt_windows_WEmbeddedFrame_MOVE_CURSOR
#define sun_awt_windows_WEmbeddedFrame_MOVE_CURSOR 13L
#undef sun_awt_windows_WEmbeddedFrame_NORMAL
#define sun_awt_windows_WEmbeddedFrame_NORMAL 0L
#undef sun_awt_windows_WEmbeddedFrame_ICONIFIED
#define sun_awt_windows_WEmbeddedFrame_ICONIFIED 1L
#undef sun_awt_windows_WEmbeddedFrame_MAXIMIZED_HORIZ
#define sun_awt_windows_WEmbeddedFrame_MAXIMIZED_HORIZ 2L
#undef sun_awt_windows_WEmbeddedFrame_MAXIMIZED_VERT
#define sun_awt_windows_WEmbeddedFrame_MAXIMIZED_VERT 4L
#undef sun_awt_windows_WEmbeddedFrame_MAXIMIZED_BOTH
#define sun_awt_windows_WEmbeddedFrame_MAXIMIZED_BOTH 6L
#undef sun_awt_windows_WEmbeddedFrame_serialVersionUID
#define sun_awt_windows_WEmbeddedFrame_serialVersionUID $LL(2673458971256075116)
#undef sun_awt_windows_WEmbeddedFrame_serialVersionUID
#define sun_awt_windows_WEmbeddedFrame_serialVersionUID $LL(2967042741780317130)
#undef sun_awt_windows_WEmbeddedFrame_FORWARD
#define sun_awt_windows_WEmbeddedFrame_FORWARD 1L
#undef sun_awt_windows_WEmbeddedFrame_BACKWARD
#define sun_awt_windows_WEmbeddedFrame_BACKWARD 0L
#undef sun_awt_windows_WEmbeddedFrame_MAX_BAND_SIZE
#define sun_awt_windows_WEmbeddedFrame_MAX_BAND_SIZE 30720L
/*
 * Class:     sun_awt_windows_WEmbeddedFrame
 * Method:    isPrinterDC
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_windows_WEmbeddedFrame_isPrinterDC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WEmbeddedFrame
 * Method:    printBand
 * Signature: (J[BIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WEmbeddedFrame_printBand
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     sun_awt_windows_WEmbeddedFrame
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WEmbeddedFrame_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WEmbeddedFrame
 * Method:    notifyModalBlockedImpl
 * Signature: (Lsun/awt/windows/WEmbeddedFramePeer;Lsun/awt/windows/WWindowPeer;Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WEmbeddedFrame_notifyModalBlockedImpl
  (JNIEnv *, jobject, jobject, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
