/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WClipboard */

#ifndef _Included_sun_awt_windows_WClipboard
#define _Included_sun_awt_windows_WClipboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_windows_WClipboard
 * Method:    openClipboard
 * Signature: (Lsun/awt/datatransfer/SunClipboard;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WClipboard_openClipboard
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WClipboard
 * Method:    closeClipboard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WClipboard_closeClipboard
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WClipboard
 * Method:    publishClipboardData
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WClipboard_publishClipboardData
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     sun_awt_windows_WClipboard
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WClipboard_init
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_windows_WClipboard
 * Method:    getClipboardFormats
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_sun_awt_windows_WClipboard_getClipboardFormats
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WClipboard
 * Method:    getClipboardData
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_sun_awt_windows_WClipboard_getClipboardData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sun_awt_windows_WClipboard
 * Method:    registerClipboardViewer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WClipboard_registerClipboardViewer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
