/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WCanvasPeer */

#ifndef _Included_sun_awt_windows_WCanvasPeer
#define _Included_sun_awt_windows_WCanvasPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WCanvasPeer_BANDING_DIVISOR
#define sun_awt_windows_WCanvasPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WCanvasPeer
 * Method:    create
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WCanvasPeer_create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sun_awt_windows_WCanvasPeer
 * Method:    setNativeBackgroundErase
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WCanvasPeer_setNativeBackgroundErase
  (JNIEnv *, jobject, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
