/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_shell_Win32ShellFolderManager2 */

#ifndef _Included_sun_awt_shell_Win32ShellFolderManager2
#define _Included_sun_awt_shell_Win32ShellFolderManager2
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_shell_Win32ShellFolderManager2_VIEW_LIST
#define sun_awt_shell_Win32ShellFolderManager2_VIEW_LIST 2L
#undef sun_awt_shell_Win32ShellFolderManager2_VIEW_DETAILS
#define sun_awt_shell_Win32ShellFolderManager2_VIEW_DETAILS 3L
#undef sun_awt_shell_Win32ShellFolderManager2_VIEW_PARENTFOLDER
#define sun_awt_shell_Win32ShellFolderManager2_VIEW_PARENTFOLDER 8L
#undef sun_awt_shell_Win32ShellFolderManager2_VIEW_NEWFOLDER
#define sun_awt_shell_Win32ShellFolderManager2_VIEW_NEWFOLDER 11L
/*
 * Class:     sun_awt_shell_Win32ShellFolderManager2
 * Method:    initializeCom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_shell_Win32ShellFolderManager2_initializeCom
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_shell_Win32ShellFolderManager2
 * Method:    uninitializeCom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_shell_Win32ShellFolderManager2_uninitializeCom
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
