/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_windows_WLabelPeer */

#ifndef _Included_sun_awt_windows_WLabelPeer
#define _Included_sun_awt_windows_WLabelPeer
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_windows_WLabelPeer_BANDING_DIVISOR
#define sun_awt_windows_WLabelPeer_BANDING_DIVISOR 4.0
/*
 * Class:     sun_awt_windows_WLabelPeer
 * Method:    lazyPaint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WLabelPeer_lazyPaint
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_windows_WLabelPeer
 * Method:    setText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WLabelPeer_setText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sun_awt_windows_WLabelPeer
 * Method:    setAlignment
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WLabelPeer_setAlignment
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_windows_WLabelPeer
 * Method:    create
 * Signature: (Lsun/awt/windows/WComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_windows_WLabelPeer_create
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
