#include <sun/swing/plaf/WindowsKeybindings.h>
#include <javax/swing/JTextField.h>
#include <javax/swing/UIDefaults$LazyInputMap.h>
#include <javax/swing/UIDefaults.h>
#include <javax/swing/text/DefaultEditorKit.h>
#include <jcpp.h>

using $ClassInfo = ::java::lang::ClassInfo;
using $MethodInfo = ::java::lang::MethodInfo;
using $JTextField = ::javax::swing::JTextField;
using $UIDefaults = ::javax::swing::UIDefaults;
using $UIDefaults$LazyInputMap = ::javax::swing::UIDefaults$LazyInputMap;
using $DefaultEditorKit = ::javax::swing::text::DefaultEditorKit;

namespace sun {
	namespace swing {
		namespace plaf {

void WindowsKeybindings::init$() {
}

void WindowsKeybindings::installKeybindings($UIDefaults* table) {
	$useLocalObjectStack();
	$init($DefaultEditorKit);
	$init($JTextField);
	$var($Object, fieldInputMap, $new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
		"control C"_s,
		$DefaultEditorKit::copyAction,
		"control V"_s,
		$DefaultEditorKit::pasteAction,
		"control X"_s,
		$DefaultEditorKit::cutAction,
		"COPY"_s,
		$DefaultEditorKit::copyAction,
		"PASTE"_s,
		$DefaultEditorKit::pasteAction,
		"CUT"_s,
		$DefaultEditorKit::cutAction,
		"control INSERT"_s,
		$DefaultEditorKit::copyAction,
		"shift INSERT"_s,
		$DefaultEditorKit::pasteAction,
		"shift DELETE"_s,
		$DefaultEditorKit::cutAction,
		"control A"_s,
		$DefaultEditorKit::selectAllAction,
		"control BACK_SLASH"_s,
		"unselect"_s,
		"shift LEFT"_s,
		$DefaultEditorKit::selectionBackwardAction,
		"shift RIGHT"_s,
		$DefaultEditorKit::selectionForwardAction,
		"control LEFT"_s,
		$DefaultEditorKit::previousWordAction,
		"control RIGHT"_s,
		$DefaultEditorKit::nextWordAction,
		"control shift LEFT"_s,
		$DefaultEditorKit::selectionPreviousWordAction,
		"control shift RIGHT"_s,
		$DefaultEditorKit::selectionNextWordAction,
		"HOME"_s,
		$DefaultEditorKit::beginLineAction,
		"END"_s,
		$DefaultEditorKit::endLineAction,
		"shift HOME"_s,
		$DefaultEditorKit::selectionBeginLineAction,
		"shift END"_s,
		$DefaultEditorKit::selectionEndLineAction,
		"BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"shift BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"ctrl H"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"DELETE"_s,
		$DefaultEditorKit::deleteNextCharAction,
		"ctrl DELETE"_s,
		$DefaultEditorKit::deleteNextWordAction,
		"ctrl BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevWordAction,
		"RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"KP_RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"KP_LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"ENTER"_s,
		$JTextField::notifyAction,
		"control shift O"_s,
		"toggle-componentOrientation"_s
	})));
	$var($Object, passwordInputMap, $new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
		"control C"_s,
		$DefaultEditorKit::copyAction,
		"control V"_s,
		$DefaultEditorKit::pasteAction,
		"control X"_s,
		$DefaultEditorKit::cutAction,
		"COPY"_s,
		$DefaultEditorKit::copyAction,
		"PASTE"_s,
		$DefaultEditorKit::pasteAction,
		"CUT"_s,
		$DefaultEditorKit::cutAction,
		"control INSERT"_s,
		$DefaultEditorKit::copyAction,
		"shift INSERT"_s,
		$DefaultEditorKit::pasteAction,
		"shift DELETE"_s,
		$DefaultEditorKit::cutAction,
		"control A"_s,
		$DefaultEditorKit::selectAllAction,
		"control BACK_SLASH"_s,
		"unselect"_s,
		"shift LEFT"_s,
		$DefaultEditorKit::selectionBackwardAction,
		"shift RIGHT"_s,
		$DefaultEditorKit::selectionForwardAction,
		"control LEFT"_s,
		$DefaultEditorKit::beginLineAction,
		"control RIGHT"_s,
		$DefaultEditorKit::endLineAction,
		"control shift LEFT"_s,
		$DefaultEditorKit::selectionBeginLineAction,
		"control shift RIGHT"_s,
		$DefaultEditorKit::selectionEndLineAction,
		"HOME"_s,
		$DefaultEditorKit::beginLineAction,
		"END"_s,
		$DefaultEditorKit::endLineAction,
		"shift HOME"_s,
		$DefaultEditorKit::selectionBeginLineAction,
		"shift END"_s,
		$DefaultEditorKit::selectionEndLineAction,
		"BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"shift BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"ctrl H"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"DELETE"_s,
		$DefaultEditorKit::deleteNextCharAction,
		"RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"KP_RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"KP_LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"ENTER"_s,
		$JTextField::notifyAction,
		"control shift O"_s,
		"toggle-componentOrientation"_s
	})));
	$var($Object, multilineInputMap, $new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
		"control C"_s,
		$DefaultEditorKit::copyAction,
		"control V"_s,
		$DefaultEditorKit::pasteAction,
		"control X"_s,
		$DefaultEditorKit::cutAction,
		"COPY"_s,
		$DefaultEditorKit::copyAction,
		"PASTE"_s,
		$DefaultEditorKit::pasteAction,
		"CUT"_s,
		$DefaultEditorKit::cutAction,
		"control INSERT"_s,
		$DefaultEditorKit::copyAction,
		"shift INSERT"_s,
		$DefaultEditorKit::pasteAction,
		"shift DELETE"_s,
		$DefaultEditorKit::cutAction,
		"shift LEFT"_s,
		$DefaultEditorKit::selectionBackwardAction,
		"shift RIGHT"_s,
		$DefaultEditorKit::selectionForwardAction,
		"control LEFT"_s,
		$DefaultEditorKit::previousWordAction,
		"control RIGHT"_s,
		$DefaultEditorKit::nextWordAction,
		"control shift LEFT"_s,
		$DefaultEditorKit::selectionPreviousWordAction,
		"control shift RIGHT"_s,
		$DefaultEditorKit::selectionNextWordAction,
		"control A"_s,
		$DefaultEditorKit::selectAllAction,
		"control BACK_SLASH"_s,
		"unselect"_s,
		"HOME"_s,
		$DefaultEditorKit::beginLineAction,
		"END"_s,
		$DefaultEditorKit::endLineAction,
		"shift HOME"_s,
		$DefaultEditorKit::selectionBeginLineAction,
		"shift END"_s,
		$DefaultEditorKit::selectionEndLineAction,
		"control HOME"_s,
		$DefaultEditorKit::beginAction,
		"control END"_s,
		$DefaultEditorKit::endAction,
		"control shift HOME"_s,
		$DefaultEditorKit::selectionBeginAction,
		"control shift END"_s,
		$DefaultEditorKit::selectionEndAction,
		"UP"_s,
		$DefaultEditorKit::upAction,
		"DOWN"_s,
		$DefaultEditorKit::downAction,
		"BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"shift BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"ctrl H"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"DELETE"_s,
		$DefaultEditorKit::deleteNextCharAction,
		"ctrl DELETE"_s,
		$DefaultEditorKit::deleteNextWordAction,
		"ctrl BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevWordAction,
		"RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"KP_RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"KP_LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"PAGE_UP"_s,
		$DefaultEditorKit::pageUpAction,
		"PAGE_DOWN"_s,
		$DefaultEditorKit::pageDownAction,
		"shift PAGE_UP"_s,
		"selection-page-up"_s,
		"shift PAGE_DOWN"_s,
		"selection-page-down"_s,
		"ctrl shift PAGE_UP"_s,
		"selection-page-left"_s,
		"ctrl shift PAGE_DOWN"_s,
		"selection-page-right"_s,
		"shift UP"_s,
		$DefaultEditorKit::selectionUpAction,
		"shift DOWN"_s,
		$DefaultEditorKit::selectionDownAction,
		"ENTER"_s,
		$DefaultEditorKit::insertBreakAction,
		"TAB"_s,
		$DefaultEditorKit::insertTabAction,
		"control T"_s,
		"next-link-action"_s,
		"control shift T"_s,
		"previous-link-action"_s,
		"control SPACE"_s,
		"activate-link-action"_s,
		"control shift O"_s,
		"toggle-componentOrientation"_s
	})));
	$var($ObjectArray, defaults, $new($ObjectArray, {
		"TextField.focusInputMap"_s,
		fieldInputMap,
		"PasswordField.focusInputMap"_s,
		passwordInputMap,
		"TextArea.focusInputMap"_s,
		multilineInputMap,
		"TextPane.focusInputMap"_s,
		multilineInputMap,
		"EditorPane.focusInputMap"_s,
		multilineInputMap,
		"Button.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"SPACE"_s,
			"pressed"_s,
			"released SPACE"_s,
			"released"_s
		})),
		"CheckBox.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"SPACE"_s,
			"pressed"_s,
			"released SPACE"_s,
			"released"_s
		})),
		"ComboBox.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ESCAPE"_s,
			"hidePopup"_s,
			"PAGE_UP"_s,
			"pageUpPassThrough"_s,
			"PAGE_DOWN"_s,
			"pageDownPassThrough"_s,
			"HOME"_s,
			"homePassThrough"_s,
			"END"_s,
			"endPassThrough"_s,
			"DOWN"_s,
			"selectNext2"_s,
			"KP_DOWN"_s,
			"selectNext2"_s,
			"UP"_s,
			"selectPrevious2"_s,
			"KP_UP"_s,
			"selectPrevious2"_s,
			"ENTER"_s,
			"enterPressed"_s,
			"F4"_s,
			"togglePopup"_s,
			"alt DOWN"_s,
			"togglePopup"_s,
			"alt KP_DOWN"_s,
			"togglePopup"_s,
			"alt UP"_s,
			"togglePopup"_s,
			"alt KP_UP"_s,
			"togglePopup"_s
		})),
		"Desktop.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ctrl F5"_s,
			"restore"_s,
			"ctrl F4"_s,
			"close"_s,
			"ctrl F7"_s,
			"move"_s,
			"ctrl F8"_s,
			"resize"_s,
			"RIGHT"_s,
			"right"_s,
			"KP_RIGHT"_s,
			"right"_s,
			"LEFT"_s,
			"left"_s,
			"KP_LEFT"_s,
			"left"_s,
			"UP"_s,
			"up"_s,
			"KP_UP"_s,
			"up"_s,
			"DOWN"_s,
			"down"_s,
			"KP_DOWN"_s,
			"down"_s,
			"ESCAPE"_s,
			"escape"_s,
			"ctrl F9"_s,
			"minimize"_s,
			"ctrl F10"_s,
			"maximize"_s,
			"ctrl F6"_s,
			"selectNextFrame"_s,
			"ctrl TAB"_s,
			"selectNextFrame"_s,
			"ctrl alt F6"_s,
			"selectNextFrame"_s,
			"shift ctrl alt F6"_s,
			"selectPreviousFrame"_s,
			"ctrl F12"_s,
			"navigateNext"_s,
			"shift ctrl F12"_s,
			"navigatePrevious"_s
		})),
		"FileChooser.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ESCAPE"_s,
			"cancelSelection"_s,
			"F2"_s,
			"editFileName"_s,
			"F5"_s,
			"refresh"_s,
			"BACK_SPACE"_s,
			"Go Up"_s,
			"ENTER"_s,
			"approveSelection"_s,
			"ctrl ENTER"_s,
			"approveSelection"_s
		})),
		"InternalFrame.windowBindings"_s,
		$$new($ObjectArray, {
			"shift ESCAPE"_s,
			"showSystemMenu"_s,
			"ctrl SPACE"_s,
			"showSystemMenu"_s,
			"ESCAPE"_s,
			"hideSystemMenu"_s
		}),
		"List.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ctrl C"_s,
			"copy"_s,
			"ctrl V"_s,
			"paste"_s,
			"ctrl X"_s,
			"cut"_s,
			"COPY"_s,
			"copy"_s,
			"PASTE"_s,
			"paste"_s,
			"CUT"_s,
			"cut"_s,
			"control INSERT"_s,
			"copy"_s,
			"shift INSERT"_s,
			"paste"_s,
			"shift DELETE"_s,
			"cut"_s,
			"UP"_s,
			"selectPreviousRow"_s,
			"KP_UP"_s,
			"selectPreviousRow"_s,
			"shift UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"shift KP_UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl shift UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl shift KP_UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl UP"_s,
			"selectPreviousRowChangeLead"_s,
			"ctrl KP_UP"_s,
			"selectPreviousRowChangeLead"_s,
			"DOWN"_s,
			"selectNextRow"_s,
			"KP_DOWN"_s,
			"selectNextRow"_s,
			"shift DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"shift KP_DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl shift DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl shift KP_DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl DOWN"_s,
			"selectNextRowChangeLead"_s,
			"ctrl KP_DOWN"_s,
			"selectNextRowChangeLead"_s,
			"LEFT"_s,
			"selectPreviousColumn"_s,
			"KP_LEFT"_s,
			"selectPreviousColumn"_s,
			"shift LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"shift KP_LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl shift LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl shift KP_LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl LEFT"_s,
			"selectPreviousColumnChangeLead"_s,
			"ctrl KP_LEFT"_s,
			"selectPreviousColumnChangeLead"_s,
			"RIGHT"_s,
			"selectNextColumn"_s,
			"KP_RIGHT"_s,
			"selectNextColumn"_s,
			"shift RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"shift KP_RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl shift RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl shift KP_RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl RIGHT"_s,
			"selectNextColumnChangeLead"_s,
			"ctrl KP_RIGHT"_s,
			"selectNextColumnChangeLead"_s,
			"HOME"_s,
			"selectFirstRow"_s,
			"shift HOME"_s,
			"selectFirstRowExtendSelection"_s,
			"ctrl shift HOME"_s,
			"selectFirstRowExtendSelection"_s,
			"ctrl HOME"_s,
			"selectFirstRowChangeLead"_s,
			"END"_s,
			"selectLastRow"_s,
			"shift END"_s,
			"selectLastRowExtendSelection"_s,
			"ctrl shift END"_s,
			"selectLastRowExtendSelection"_s,
			"ctrl END"_s,
			"selectLastRowChangeLead"_s,
			"PAGE_UP"_s,
			"scrollUp"_s,
			"shift PAGE_UP"_s,
			"scrollUpExtendSelection"_s,
			"ctrl shift PAGE_UP"_s,
			"scrollUpExtendSelection"_s,
			"ctrl PAGE_UP"_s,
			"scrollUpChangeLead"_s,
			"PAGE_DOWN"_s,
			"scrollDown"_s,
			"shift PAGE_DOWN"_s,
			"scrollDownExtendSelection"_s,
			"ctrl shift PAGE_DOWN"_s,
			"scrollDownExtendSelection"_s,
			"ctrl PAGE_DOWN"_s,
			"scrollDownChangeLead"_s,
			"ctrl A"_s,
			"selectAll"_s,
			"ctrl SLASH"_s,
			"selectAll"_s,
			"ctrl BACK_SLASH"_s,
			"clearSelection"_s,
			"SPACE"_s,
			"addToSelection"_s,
			"ctrl SPACE"_s,
			"toggleAndAnchor"_s,
			"shift SPACE"_s,
			"extendTo"_s,
			"ctrl shift SPACE"_s,
			"moveSelectionTo"_s
		})),
		"MenuBar.windowBindings"_s,
		$$new($ObjectArray, {
			"F10"_s,
			"takeFocus"_s
		}),
		"RadioButton.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"SPACE"_s,
			"pressed"_s,
			"released SPACE"_s,
			"released"_s
		})),
		"OptionPane.windowBindings"_s,
		$$new($ObjectArray, {
			"ESCAPE"_s,
			"close"_s
		}),
		"FormattedTextField.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ctrl C"_s,
			$DefaultEditorKit::copyAction,
			"ctrl V"_s,
			$DefaultEditorKit::pasteAction,
			"ctrl X"_s,
			$DefaultEditorKit::cutAction,
			"COPY"_s,
			$DefaultEditorKit::copyAction,
			"PASTE"_s,
			$DefaultEditorKit::pasteAction,
			"CUT"_s,
			$DefaultEditorKit::cutAction,
			"control INSERT"_s,
			$DefaultEditorKit::copyAction,
			"shift INSERT"_s,
			$DefaultEditorKit::pasteAction,
			"shift DELETE"_s,
			$DefaultEditorKit::cutAction,
			"shift LEFT"_s,
			$DefaultEditorKit::selectionBackwardAction,
			"shift KP_LEFT"_s,
			$DefaultEditorKit::selectionBackwardAction,
			"shift RIGHT"_s,
			$DefaultEditorKit::selectionForwardAction,
			"shift KP_RIGHT"_s,
			$DefaultEditorKit::selectionForwardAction,
			"ctrl LEFT"_s,
			$DefaultEditorKit::previousWordAction,
			"ctrl KP_LEFT"_s,
			$DefaultEditorKit::previousWordAction,
			"ctrl RIGHT"_s,
			$DefaultEditorKit::nextWordAction,
			"ctrl KP_RIGHT"_s,
			$DefaultEditorKit::nextWordAction,
			"ctrl shift LEFT"_s,
			$DefaultEditorKit::selectionPreviousWordAction,
			"ctrl shift KP_LEFT"_s,
			$DefaultEditorKit::selectionPreviousWordAction,
			"ctrl shift RIGHT"_s,
			$DefaultEditorKit::selectionNextWordAction,
			"ctrl shift KP_RIGHT"_s,
			$DefaultEditorKit::selectionNextWordAction,
			"ctrl A"_s,
			$DefaultEditorKit::selectAllAction,
			"HOME"_s,
			$DefaultEditorKit::beginLineAction,
			"END"_s,
			$DefaultEditorKit::endLineAction,
			"shift HOME"_s,
			$DefaultEditorKit::selectionBeginLineAction,
			"shift END"_s,
			$DefaultEditorKit::selectionEndLineAction,
			"BACK_SPACE"_s,
			$DefaultEditorKit::deletePrevCharAction,
			"shift BACK_SPACE"_s,
			$DefaultEditorKit::deletePrevCharAction,
			"ctrl H"_s,
			$DefaultEditorKit::deletePrevCharAction,
			"DELETE"_s,
			$DefaultEditorKit::deleteNextCharAction,
			"ctrl DELETE"_s,
			$DefaultEditorKit::deleteNextWordAction,
			"ctrl BACK_SPACE"_s,
			$DefaultEditorKit::deletePrevWordAction,
			"RIGHT"_s,
			$DefaultEditorKit::forwardAction,
			"LEFT"_s,
			$DefaultEditorKit::backwardAction,
			"KP_RIGHT"_s,
			$DefaultEditorKit::forwardAction,
			"KP_LEFT"_s,
			$DefaultEditorKit::backwardAction,
			"ENTER"_s,
			$JTextField::notifyAction,
			"ctrl BACK_SLASH"_s,
			"unselect"_s,
			"control shift O"_s,
			"toggle-componentOrientation"_s,
			"ESCAPE"_s,
			"reset-field-edit"_s,
			"UP"_s,
			"increment"_s,
			"KP_UP"_s,
			"increment"_s,
			"DOWN"_s,
			"decrement"_s,
			"KP_DOWN"_s,
			"decrement"_s
		})),
		"RootPane.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"shift F10"_s,
			"postPopup"_s,
			"CONTEXT_MENU"_s,
			"postPopup"_s
		})),
		"RootPane.defaultButtonWindowKeyBindings"_s,
		$$new($ObjectArray, {
			"ENTER"_s,
			"press"_s,
			"released ENTER"_s,
			"release"_s,
			"ctrl ENTER"_s,
			"press"_s,
			"ctrl released ENTER"_s,
			"release"_s
		}),
		"ScrollBar.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"RIGHT"_s,
			"positiveUnitIncrement"_s,
			"KP_RIGHT"_s,
			"positiveUnitIncrement"_s,
			"DOWN"_s,
			"positiveUnitIncrement"_s,
			"KP_DOWN"_s,
			"positiveUnitIncrement"_s,
			"PAGE_DOWN"_s,
			"positiveBlockIncrement"_s,
			"ctrl PAGE_DOWN"_s,
			"positiveBlockIncrement"_s,
			"LEFT"_s,
			"negativeUnitIncrement"_s,
			"KP_LEFT"_s,
			"negativeUnitIncrement"_s,
			"UP"_s,
			"negativeUnitIncrement"_s,
			"KP_UP"_s,
			"negativeUnitIncrement"_s,
			"PAGE_UP"_s,
			"negativeBlockIncrement"_s,
			"ctrl PAGE_UP"_s,
			"negativeBlockIncrement"_s,
			"HOME"_s,
			"minScroll"_s,
			"END"_s,
			"maxScroll"_s
		})),
		"ScrollPane.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"RIGHT"_s,
			"unitScrollRight"_s,
			"KP_RIGHT"_s,
			"unitScrollRight"_s,
			"DOWN"_s,
			"unitScrollDown"_s,
			"KP_DOWN"_s,
			"unitScrollDown"_s,
			"LEFT"_s,
			"unitScrollLeft"_s,
			"KP_LEFT"_s,
			"unitScrollLeft"_s,
			"UP"_s,
			"unitScrollUp"_s,
			"KP_UP"_s,
			"unitScrollUp"_s,
			"PAGE_UP"_s,
			"scrollUp"_s,
			"PAGE_DOWN"_s,
			"scrollDown"_s,
			"ctrl PAGE_UP"_s,
			"scrollLeft"_s,
			"ctrl PAGE_DOWN"_s,
			"scrollRight"_s,
			"ctrl HOME"_s,
			"scrollHome"_s,
			"ctrl END"_s,
			"scrollEnd"_s
		})),
		"Slider.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"RIGHT"_s,
			"positiveUnitIncrement"_s,
			"KP_RIGHT"_s,
			"positiveUnitIncrement"_s,
			"DOWN"_s,
			"negativeUnitIncrement"_s,
			"KP_DOWN"_s,
			"negativeUnitIncrement"_s,
			"PAGE_DOWN"_s,
			"negativeBlockIncrement"_s,
			"LEFT"_s,
			"negativeUnitIncrement"_s,
			"KP_LEFT"_s,
			"negativeUnitIncrement"_s,
			"UP"_s,
			"positiveUnitIncrement"_s,
			"KP_UP"_s,
			"positiveUnitIncrement"_s,
			"PAGE_UP"_s,
			"positiveBlockIncrement"_s,
			"HOME"_s,
			"minScroll"_s,
			"END"_s,
			"maxScroll"_s
		})),
		"Spinner.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"UP"_s,
			"increment"_s,
			"KP_UP"_s,
			"increment"_s,
			"DOWN"_s,
			"decrement"_s,
			"KP_DOWN"_s,
			"decrement"_s
		})),
		"SplitPane.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"UP"_s,
			"negativeIncrement"_s,
			"DOWN"_s,
			"positiveIncrement"_s,
			"LEFT"_s,
			"negativeIncrement"_s,
			"RIGHT"_s,
			"positiveIncrement"_s,
			"KP_UP"_s,
			"negativeIncrement"_s,
			"KP_DOWN"_s,
			"positiveIncrement"_s,
			"KP_LEFT"_s,
			"negativeIncrement"_s,
			"KP_RIGHT"_s,
			"positiveIncrement"_s,
			"HOME"_s,
			"selectMin"_s,
			"END"_s,
			"selectMax"_s,
			"F8"_s,
			"startResize"_s,
			"F6"_s,
			"toggleFocus"_s,
			"ctrl TAB"_s,
			"focusOutForward"_s,
			"ctrl shift TAB"_s,
			"focusOutBackward"_s
		})),
		"TabbedPane.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"RIGHT"_s,
			"navigateRight"_s,
			"KP_RIGHT"_s,
			"navigateRight"_s,
			"LEFT"_s,
			"navigateLeft"_s,
			"KP_LEFT"_s,
			"navigateLeft"_s,
			"UP"_s,
			"navigateUp"_s,
			"KP_UP"_s,
			"navigateUp"_s,
			"DOWN"_s,
			"navigateDown"_s,
			"KP_DOWN"_s,
			"navigateDown"_s,
			"ctrl DOWN"_s,
			"requestFocusForVisibleComponent"_s,
			"ctrl KP_DOWN"_s,
			"requestFocusForVisibleComponent"_s
		})),
		"TabbedPane.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ctrl TAB"_s,
			"navigateNext"_s,
			"ctrl shift TAB"_s,
			"navigatePrevious"_s,
			"ctrl PAGE_DOWN"_s,
			"navigatePageDown"_s,
			"ctrl PAGE_UP"_s,
			"navigatePageUp"_s,
			"ctrl UP"_s,
			"requestFocus"_s,
			"ctrl KP_UP"_s,
			"requestFocus"_s
		})),
		"TableHeader.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"SPACE"_s,
			"toggleSortOrder"_s,
			"LEFT"_s,
			"selectColumnToLeft"_s,
			"KP_LEFT"_s,
			"selectColumnToLeft"_s,
			"RIGHT"_s,
			"selectColumnToRight"_s,
			"KP_RIGHT"_s,
			"selectColumnToRight"_s,
			"alt LEFT"_s,
			"moveColumnLeft"_s,
			"alt KP_LEFT"_s,
			"moveColumnLeft"_s,
			"alt RIGHT"_s,
			"moveColumnRight"_s,
			"alt KP_RIGHT"_s,
			"moveColumnRight"_s,
			"alt shift LEFT"_s,
			"resizeLeft"_s,
			"alt shift KP_LEFT"_s,
			"resizeLeft"_s,
			"alt shift RIGHT"_s,
			"resizeRight"_s,
			"alt shift KP_RIGHT"_s,
			"resizeRight"_s,
			"ESCAPE"_s,
			"focusTable"_s
		})),
		"Table.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ctrl C"_s,
			"copy"_s,
			"ctrl V"_s,
			"paste"_s,
			"ctrl X"_s,
			"cut"_s,
			"COPY"_s,
			"copy"_s,
			"PASTE"_s,
			"paste"_s,
			"CUT"_s,
			"cut"_s,
			"control INSERT"_s,
			"copy"_s,
			"shift INSERT"_s,
			"paste"_s,
			"shift DELETE"_s,
			"cut"_s,
			"RIGHT"_s,
			"selectNextColumn"_s,
			"KP_RIGHT"_s,
			"selectNextColumn"_s,
			"shift RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"shift KP_RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl shift RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl shift KP_RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl RIGHT"_s,
			"selectNextColumnChangeLead"_s,
			"ctrl KP_RIGHT"_s,
			"selectNextColumnChangeLead"_s,
			"LEFT"_s,
			"selectPreviousColumn"_s,
			"KP_LEFT"_s,
			"selectPreviousColumn"_s,
			"shift LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"shift KP_LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl shift LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl shift KP_LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl LEFT"_s,
			"selectPreviousColumnChangeLead"_s,
			"ctrl KP_LEFT"_s,
			"selectPreviousColumnChangeLead"_s,
			"DOWN"_s,
			"selectNextRow"_s,
			"KP_DOWN"_s,
			"selectNextRow"_s,
			"shift DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"shift KP_DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl shift DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl shift KP_DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl DOWN"_s,
			"selectNextRowChangeLead"_s,
			"ctrl KP_DOWN"_s,
			"selectNextRowChangeLead"_s,
			"UP"_s,
			"selectPreviousRow"_s,
			"KP_UP"_s,
			"selectPreviousRow"_s,
			"shift UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"shift KP_UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl shift UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl shift KP_UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl UP"_s,
			"selectPreviousRowChangeLead"_s,
			"ctrl KP_UP"_s,
			"selectPreviousRowChangeLead"_s,
			"HOME"_s,
			"selectFirstColumn"_s,
			"shift HOME"_s,
			"selectFirstColumnExtendSelection"_s,
			"ctrl shift HOME"_s,
			"selectFirstRowExtendSelection"_s,
			"ctrl HOME"_s,
			"selectFirstRow"_s,
			"END"_s,
			"selectLastColumn"_s,
			"shift END"_s,
			"selectLastColumnExtendSelection"_s,
			"ctrl shift END"_s,
			"selectLastRowExtendSelection"_s,
			"ctrl END"_s,
			"selectLastRow"_s,
			"PAGE_UP"_s,
			"scrollUpChangeSelection"_s,
			"shift PAGE_UP"_s,
			"scrollUpExtendSelection"_s,
			"ctrl shift PAGE_UP"_s,
			"scrollLeftExtendSelection"_s,
			"ctrl PAGE_UP"_s,
			"scrollLeftChangeSelection"_s,
			"PAGE_DOWN"_s,
			"scrollDownChangeSelection"_s,
			"shift PAGE_DOWN"_s,
			"scrollDownExtendSelection"_s,
			"ctrl shift PAGE_DOWN"_s,
			"scrollRightExtendSelection"_s,
			"ctrl PAGE_DOWN"_s,
			"scrollRightChangeSelection"_s,
			"TAB"_s,
			"selectNextColumnCell"_s,
			"shift TAB"_s,
			"selectPreviousColumnCell"_s,
			"ENTER"_s,
			"selectNextRowCell"_s,
			"shift ENTER"_s,
			"selectPreviousRowCell"_s,
			"ctrl A"_s,
			"selectAll"_s,
			"ctrl SLASH"_s,
			"selectAll"_s,
			"ctrl BACK_SLASH"_s,
			"clearSelection"_s,
			"ESCAPE"_s,
			"cancel"_s,
			"F2"_s,
			"startEditing"_s,
			"SPACE"_s,
			"addToSelection"_s,
			"ctrl SPACE"_s,
			"toggleAndAnchor"_s,
			"shift SPACE"_s,
			"extendTo"_s,
			"ctrl shift SPACE"_s,
			"moveSelectionTo"_s,
			"F8"_s,
			"focusHeader"_s
		})),
		"ToggleButton.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"SPACE"_s,
			"pressed"_s,
			"released SPACE"_s,
			"released"_s
		})),
		"ToolBar.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"UP"_s,
			"navigateUp"_s,
			"KP_UP"_s,
			"navigateUp"_s,
			"DOWN"_s,
			"navigateDown"_s,
			"KP_DOWN"_s,
			"navigateDown"_s,
			"LEFT"_s,
			"navigateLeft"_s,
			"KP_LEFT"_s,
			"navigateLeft"_s,
			"RIGHT"_s,
			"navigateRight"_s,
			"KP_RIGHT"_s,
			"navigateRight"_s
		})),
		"Tree.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ADD"_s,
			"expand"_s,
			"SUBTRACT"_s,
			"collapse"_s,
			"ctrl C"_s,
			"copy"_s,
			"ctrl V"_s,
			"paste"_s,
			"ctrl X"_s,
			"cut"_s,
			"COPY"_s,
			"copy"_s,
			"PASTE"_s,
			"paste"_s,
			"CUT"_s,
			"cut"_s,
			"control INSERT"_s,
			"copy"_s,
			"shift INSERT"_s,
			"paste"_s,
			"shift DELETE"_s,
			"cut"_s,
			"UP"_s,
			"selectPrevious"_s,
			"KP_UP"_s,
			"selectPrevious"_s,
			"shift UP"_s,
			"selectPreviousExtendSelection"_s,
			"shift KP_UP"_s,
			"selectPreviousExtendSelection"_s,
			"ctrl shift UP"_s,
			"selectPreviousExtendSelection"_s,
			"ctrl shift KP_UP"_s,
			"selectPreviousExtendSelection"_s,
			"ctrl UP"_s,
			"selectPreviousChangeLead"_s,
			"ctrl KP_UP"_s,
			"selectPreviousChangeLead"_s,
			"DOWN"_s,
			"selectNext"_s,
			"KP_DOWN"_s,
			"selectNext"_s,
			"shift DOWN"_s,
			"selectNextExtendSelection"_s,
			"shift KP_DOWN"_s,
			"selectNextExtendSelection"_s,
			"ctrl shift DOWN"_s,
			"selectNextExtendSelection"_s,
			"ctrl shift KP_DOWN"_s,
			"selectNextExtendSelection"_s,
			"ctrl DOWN"_s,
			"selectNextChangeLead"_s,
			"ctrl KP_DOWN"_s,
			"selectNextChangeLead"_s,
			"RIGHT"_s,
			"selectChild"_s,
			"KP_RIGHT"_s,
			"selectChild"_s,
			"LEFT"_s,
			"selectParent"_s,
			"KP_LEFT"_s,
			"selectParent"_s,
			"PAGE_UP"_s,
			"scrollUpChangeSelection"_s,
			"shift PAGE_UP"_s,
			"scrollUpExtendSelection"_s,
			"ctrl shift PAGE_UP"_s,
			"scrollUpExtendSelection"_s,
			"ctrl PAGE_UP"_s,
			"scrollUpChangeLead"_s,
			"PAGE_DOWN"_s,
			"scrollDownChangeSelection"_s,
			"shift PAGE_DOWN"_s,
			"scrollDownExtendSelection"_s,
			"ctrl shift PAGE_DOWN"_s,
			"scrollDownExtendSelection"_s,
			"ctrl PAGE_DOWN"_s,
			"scrollDownChangeLead"_s,
			"HOME"_s,
			"selectFirst"_s,
			"shift HOME"_s,
			"selectFirstExtendSelection"_s,
			"ctrl shift HOME"_s,
			"selectFirstExtendSelection"_s,
			"ctrl HOME"_s,
			"selectFirstChangeLead"_s,
			"END"_s,
			"selectLast"_s,
			"shift END"_s,
			"selectLastExtendSelection"_s,
			"ctrl shift END"_s,
			"selectLastExtendSelection"_s,
			"ctrl END"_s,
			"selectLastChangeLead"_s,
			"F2"_s,
			"startEditing"_s,
			"ctrl A"_s,
			"selectAll"_s,
			"ctrl SLASH"_s,
			"selectAll"_s,
			"ctrl BACK_SLASH"_s,
			"clearSelection"_s,
			"ctrl LEFT"_s,
			"scrollLeft"_s,
			"ctrl KP_LEFT"_s,
			"scrollLeft"_s,
			"ctrl RIGHT"_s,
			"scrollRight"_s,
			"ctrl KP_RIGHT"_s,
			"scrollRight"_s,
			"SPACE"_s,
			"addToSelection"_s,
			"ctrl SPACE"_s,
			"toggleAndAnchor"_s,
			"shift SPACE"_s,
			"extendTo"_s,
			"ctrl shift SPACE"_s,
			"moveSelectionTo"_s
		})),
		"Tree.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ESCAPE"_s,
			"cancel"_s
		}))
	}));
	$nc(table)->putDefaults(defaults);
}

WindowsKeybindings::WindowsKeybindings() {
}

$Class* WindowsKeybindings::load$($String* name, bool initialize) {
	$MethodInfo methodInfos$$[] = {
		{"<init>", "()V", nullptr, $PUBLIC, $method(WindowsKeybindings, init$, void)},
		{"installKeybindings", "(Ljavax/swing/UIDefaults;)V", nullptr, $PUBLIC | $STATIC, $staticMethod(WindowsKeybindings, installKeybindings, void, $UIDefaults*)},
		{}
	};
	$ClassInfo classInfo$$ = {
		$PUBLIC | $ACC_SUPER,
		"sun.swing.plaf.WindowsKeybindings",
		"java.lang.Object",
		nullptr,
		nullptr,
		methodInfos$$
	};
	$loadClass(WindowsKeybindings, name, initialize, &classInfo$$, []($Class* clazz) -> $Object* {
		return $alloc(WindowsKeybindings);
	});
	return class$;
}

$Class* WindowsKeybindings::class$ = nullptr;

		} // plaf
	} // swing
} // sun