/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeThread */

#ifndef _Included_NativeThread
#define _Included_NativeThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeThread
 * Method:    getID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeThread_getID
  (JNIEnv *, jclass);

/*
 * Class:     NativeThread
 * Method:    signal
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_NativeThread_signal
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     NativeThread
 * Method:    getSIGPIPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_NativeThread_getSIGPIPE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
