/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_media_sound_Platform */

#ifndef _Included_com_sun_media_sound_Platform
#define _Included_com_sun_media_sound_Platform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_media_sound_Platform
 * Method:    nIsBigEndian
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_media_sound_Platform_nIsBigEndian
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
