/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_awt_MenuComponent */

#ifndef _Included_java_awt_MenuComponent
#define _Included_java_awt_MenuComponent
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_MenuComponent_serialVersionUID
#define java_awt_MenuComponent_serialVersionUID $LL(-4536902356223894379)
/*
 * Class:     java_awt_MenuComponent
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_awt_MenuComponent_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
