/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_awt_FontMetrics */

#ifndef _Included_java_awt_FontMetrics
#define _Included_java_awt_FontMetrics
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_FontMetrics_serialVersionUID
#define java_awt_FontMetrics_serialVersionUID $LL(1681126225205050147)
/*
 * Class:     java_awt_FontMetrics
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_awt_FontMetrics_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
