/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_awt_ScrollPaneAdjustable */

#ifndef _Included_java_awt_ScrollPaneAdjustable
#define _Included_java_awt_ScrollPaneAdjustable
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_ScrollPaneAdjustable_serialVersionUID
#define java_awt_ScrollPaneAdjustable_serialVersionUID $LL(-3359745691033257079)
/*
 * Class:     java_awt_ScrollPaneAdjustable
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_awt_ScrollPaneAdjustable_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
