/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_awt_Choice */

#ifndef _Included_java_awt_Choice
#define _Included_java_awt_Choice
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_Choice_FOCUS_TRAVERSABLE_UNKNOWN
#define java_awt_Choice_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef java_awt_Choice_FOCUS_TRAVERSABLE_DEFAULT
#define java_awt_Choice_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef java_awt_Choice_FOCUS_TRAVERSABLE_SET
#define java_awt_Choice_FOCUS_TRAVERSABLE_SET 2L
#undef java_awt_Choice_TOP_ALIGNMENT
#define java_awt_Choice_TOP_ALIGNMENT 0.0f
#undef java_awt_Choice_CENTER_ALIGNMENT
#define java_awt_Choice_CENTER_ALIGNMENT 0.5f
#undef java_awt_Choice_BOTTOM_ALIGNMENT
#define java_awt_Choice_BOTTOM_ALIGNMENT 1.0f
#undef java_awt_Choice_LEFT_ALIGNMENT
#define java_awt_Choice_LEFT_ALIGNMENT 0.0f
#undef java_awt_Choice_RIGHT_ALIGNMENT
#define java_awt_Choice_RIGHT_ALIGNMENT 1.0f
#undef java_awt_Choice_serialVersionUID
#define java_awt_Choice_serialVersionUID $LL(-7644114512714619750)
#undef java_awt_Choice_serialVersionUID
#define java_awt_Choice_serialVersionUID $LL(-4075310674757313071)
/*
 * Class:     java_awt_Choice
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_awt_Choice_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
