/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_awt_TextField */

#ifndef _Included_java_awt_TextField
#define _Included_java_awt_TextField
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_TextField_FOCUS_TRAVERSABLE_UNKNOWN
#define java_awt_TextField_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef java_awt_TextField_FOCUS_TRAVERSABLE_DEFAULT
#define java_awt_TextField_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef java_awt_TextField_FOCUS_TRAVERSABLE_SET
#define java_awt_TextField_FOCUS_TRAVERSABLE_SET 2L
#undef java_awt_TextField_TOP_ALIGNMENT
#define java_awt_TextField_TOP_ALIGNMENT 0.0f
#undef java_awt_TextField_CENTER_ALIGNMENT
#define java_awt_TextField_CENTER_ALIGNMENT 0.5f
#undef java_awt_TextField_BOTTOM_ALIGNMENT
#define java_awt_TextField_BOTTOM_ALIGNMENT 1.0f
#undef java_awt_TextField_LEFT_ALIGNMENT
#define java_awt_TextField_LEFT_ALIGNMENT 0.0f
#undef java_awt_TextField_RIGHT_ALIGNMENT
#define java_awt_TextField_RIGHT_ALIGNMENT 1.0f
#undef java_awt_TextField_serialVersionUID
#define java_awt_TextField_serialVersionUID $LL(-7644114512714619750)
#undef java_awt_TextField_serialVersionUID
#define java_awt_TextField_serialVersionUID $LL(-2214773872412987419)
#undef java_awt_TextField_serialVersionUID
#define java_awt_TextField_serialVersionUID $LL(-2966288784432217853)
/*
 * Class:     java_awt_TextField
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_awt_TextField_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
