/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_awt_AWTEvent */

#ifndef _Included_java_awt_AWTEvent
#define _Included_java_awt_AWTEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_AWTEvent_serialVersionUID
#define java_awt_AWTEvent_serialVersionUID $LL(5516075349620653480)
#undef java_awt_AWTEvent_COMPONENT_EVENT_MASK
#define java_awt_AWTEvent_COMPONENT_EVENT_MASK $LL(1)
#undef java_awt_AWTEvent_CONTAINER_EVENT_MASK
#define java_awt_AWTEvent_CONTAINER_EVENT_MASK $LL(2)
#undef java_awt_AWTEvent_FOCUS_EVENT_MASK
#define java_awt_AWTEvent_FOCUS_EVENT_MASK $LL(4)
#undef java_awt_AWTEvent_KEY_EVENT_MASK
#define java_awt_AWTEvent_KEY_EVENT_MASK $LL(8)
#undef java_awt_AWTEvent_MOUSE_EVENT_MASK
#define java_awt_AWTEvent_MOUSE_EVENT_MASK $LL(16)
#undef java_awt_AWTEvent_MOUSE_MOTION_EVENT_MASK
#define java_awt_AWTEvent_MOUSE_MOTION_EVENT_MASK $LL(32)
#undef java_awt_AWTEvent_WINDOW_EVENT_MASK
#define java_awt_AWTEvent_WINDOW_EVENT_MASK $LL(64)
#undef java_awt_AWTEvent_ACTION_EVENT_MASK
#define java_awt_AWTEvent_ACTION_EVENT_MASK $LL(128)
#undef java_awt_AWTEvent_ADJUSTMENT_EVENT_MASK
#define java_awt_AWTEvent_ADJUSTMENT_EVENT_MASK $LL(256)
#undef java_awt_AWTEvent_ITEM_EVENT_MASK
#define java_awt_AWTEvent_ITEM_EVENT_MASK $LL(512)
#undef java_awt_AWTEvent_TEXT_EVENT_MASK
#define java_awt_AWTEvent_TEXT_EVENT_MASK $LL(1024)
#undef java_awt_AWTEvent_INPUT_METHOD_EVENT_MASK
#define java_awt_AWTEvent_INPUT_METHOD_EVENT_MASK $LL(2048)
#undef java_awt_AWTEvent_INPUT_METHODS_ENABLED_MASK
#define java_awt_AWTEvent_INPUT_METHODS_ENABLED_MASK $LL(4096)
#undef java_awt_AWTEvent_PAINT_EVENT_MASK
#define java_awt_AWTEvent_PAINT_EVENT_MASK $LL(8192)
#undef java_awt_AWTEvent_INVOCATION_EVENT_MASK
#define java_awt_AWTEvent_INVOCATION_EVENT_MASK $LL(16384)
#undef java_awt_AWTEvent_HIERARCHY_EVENT_MASK
#define java_awt_AWTEvent_HIERARCHY_EVENT_MASK $LL(32768)
#undef java_awt_AWTEvent_HIERARCHY_BOUNDS_EVENT_MASK
#define java_awt_AWTEvent_HIERARCHY_BOUNDS_EVENT_MASK $LL(65536)
#undef java_awt_AWTEvent_MOUSE_WHEEL_EVENT_MASK
#define java_awt_AWTEvent_MOUSE_WHEEL_EVENT_MASK $LL(131072)
#undef java_awt_AWTEvent_WINDOW_STATE_EVENT_MASK
#define java_awt_AWTEvent_WINDOW_STATE_EVENT_MASK $LL(262144)
#undef java_awt_AWTEvent_WINDOW_FOCUS_EVENT_MASK
#define java_awt_AWTEvent_WINDOW_FOCUS_EVENT_MASK $LL(524288)
#undef java_awt_AWTEvent_RESERVED_ID_MAX
#define java_awt_AWTEvent_RESERVED_ID_MAX 1999L
#undef java_awt_AWTEvent_serialVersionUID
#define java_awt_AWTEvent_serialVersionUID $LL(-1825314779160409405)
/*
 * Class:     java_awt_AWTEvent
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_awt_AWTEvent_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     java_awt_AWTEvent
 * Method:    nativeSetSource
 * Signature: (Ljava/awt/peer/ComponentPeer;)V
 */
JNIEXPORT void JNICALL Java_java_awt_AWTEvent_nativeSetSource
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
