/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_awt_Menu */

#ifndef _Included_java_awt_Menu
#define _Included_java_awt_Menu
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_Menu_serialVersionUID
#define java_awt_Menu_serialVersionUID $LL(-4536902356223894379)
#undef java_awt_Menu_serialVersionUID
#define java_awt_Menu_serialVersionUID $LL(-21757335363267194)
#undef java_awt_Menu_serialVersionUID
#define java_awt_Menu_serialVersionUID $LL(-8809584163345499784)
/*
 * Class:     java_awt_Menu
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_awt_Menu_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
