/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_awt_Insets */

#ifndef _Included_java_awt_Insets
#define _Included_java_awt_Insets
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_Insets_serialVersionUID
#define java_awt_Insets_serialVersionUID $LL(-2272572637695466749)
/*
 * Class:     java_awt_Insets
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_awt_Insets_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
