/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_awt_FileDialog */

#ifndef _Included_java_awt_FileDialog
#define _Included_java_awt_FileDialog
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_FileDialog_FOCUS_TRAVERSABLE_UNKNOWN
#define java_awt_FileDialog_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef java_awt_FileDialog_FOCUS_TRAVERSABLE_DEFAULT
#define java_awt_FileDialog_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef java_awt_FileDialog_FOCUS_TRAVERSABLE_SET
#define java_awt_FileDialog_FOCUS_TRAVERSABLE_SET 2L
#undef java_awt_FileDialog_TOP_ALIGNMENT
#define java_awt_FileDialog_TOP_ALIGNMENT 0.0f
#undef java_awt_FileDialog_CENTER_ALIGNMENT
#define java_awt_FileDialog_CENTER_ALIGNMENT 0.5f
#undef java_awt_FileDialog_BOTTOM_ALIGNMENT
#define java_awt_FileDialog_BOTTOM_ALIGNMENT 1.0f
#undef java_awt_FileDialog_LEFT_ALIGNMENT
#define java_awt_FileDialog_LEFT_ALIGNMENT 0.0f
#undef java_awt_FileDialog_RIGHT_ALIGNMENT
#define java_awt_FileDialog_RIGHT_ALIGNMENT 1.0f
#undef java_awt_FileDialog_serialVersionUID
#define java_awt_FileDialog_serialVersionUID $LL(-7644114512714619750)
#undef java_awt_FileDialog_serialVersionUID
#define java_awt_FileDialog_serialVersionUID $LL(4613797578919906343)
#undef java_awt_FileDialog_INCLUDE_SELF
#define java_awt_FileDialog_INCLUDE_SELF 1L
#undef java_awt_FileDialog_SEARCH_HEAVYWEIGHTS
#define java_awt_FileDialog_SEARCH_HEAVYWEIGHTS 1L
#undef java_awt_FileDialog_OPENED
#define java_awt_FileDialog_OPENED 1L
#undef java_awt_FileDialog_serialVersionUID
#define java_awt_FileDialog_serialVersionUID $LL(4497834738069338734)
#undef java_awt_FileDialog_serialVersionUID
#define java_awt_FileDialog_serialVersionUID $LL(5920926903803293709)
#undef java_awt_FileDialog_LOAD
#define java_awt_FileDialog_LOAD 0L
#undef java_awt_FileDialog_SAVE
#define java_awt_FileDialog_SAVE 1L
#undef java_awt_FileDialog_serialVersionUID
#define java_awt_FileDialog_serialVersionUID $LL(5035145889651310422)
/*
 * Class:     java_awt_FileDialog
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_awt_FileDialog_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
