/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_awt_CheckboxMenuItem */

#ifndef _Included_java_awt_CheckboxMenuItem
#define _Included_java_awt_CheckboxMenuItem
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_CheckboxMenuItem_serialVersionUID
#define java_awt_CheckboxMenuItem_serialVersionUID $LL(-4536902356223894379)
#undef java_awt_CheckboxMenuItem_serialVersionUID
#define java_awt_CheckboxMenuItem_serialVersionUID $LL(-21757335363267194)
#undef java_awt_CheckboxMenuItem_serialVersionUID
#define java_awt_CheckboxMenuItem_serialVersionUID $LL(6190621106981774043)
/*
 * Class:     java_awt_CheckboxMenuItem
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_awt_CheckboxMenuItem_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
