/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef $LL
#ifdef _WIN32
#define $LL(x) x##i64
#else
#define $LL(x) x##LL
#endif
#endif

/* Header for class java_awt_MenuBar */

#ifndef _Included_java_awt_MenuBar
#define _Included_java_awt_MenuBar
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_MenuBar_serialVersionUID
#define java_awt_MenuBar_serialVersionUID $LL(-4536902356223894379)
#undef java_awt_MenuBar_serialVersionUID
#define java_awt_MenuBar_serialVersionUID $LL(-4930327919388951260)
/*
 * Class:     java_awt_MenuBar
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_awt_MenuBar_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
