/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_font_SunLayoutEngine */

#ifndef _Included_sun_font_SunLayoutEngine
#define _Included_sun_font_SunLayoutEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_font_SunLayoutEngine
 * Method:    shape
 * Signature: (Lsun/font/Font2D;Lsun/font/FontStrike;F[FJ[CLsun/font/GlyphLayout/GVData;IIIILjava/awt/geom/Point2D/Float;II)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_font_SunLayoutEngine_shape
  (JNIEnv *, jclass, jobject, jobject, jfloat, jfloatArray, jlong, jcharArray, jobject, jint, jint, jint, jint, jobject, jint, jint);

/*
 * Class:     sun_font_SunLayoutEngine
 * Method:    createFace
 * Signature: (Lsun/font/Font2D;J)J
 */
JNIEXPORT jlong JNICALL Java_sun_font_SunLayoutEngine_createFace
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     sun_font_SunLayoutEngine
 * Method:    disposeFace
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_font_SunLayoutEngine_disposeFace
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
