/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_font_ColorGlyphSurfaceData */

#ifndef _Included_sun_font_ColorGlyphSurfaceData
#define _Included_sun_font_ColorGlyphSurfaceData
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_font_ColorGlyphSurfaceData_LOOP_UNKNOWN
#define sun_font_ColorGlyphSurfaceData_LOOP_UNKNOWN 0L
#undef sun_font_ColorGlyphSurfaceData_LOOP_FOUND
#define sun_font_ColorGlyphSurfaceData_LOOP_FOUND 1L
#undef sun_font_ColorGlyphSurfaceData_LOOP_NOTFOUND
#define sun_font_ColorGlyphSurfaceData_LOOP_NOTFOUND 2L
/*
 * Class:     sun_font_ColorGlyphSurfaceData
 * Method:    initOps
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_font_ColorGlyphSurfaceData_initOps
  (JNIEnv *, jobject);

/*
 * Class:     sun_font_ColorGlyphSurfaceData
 * Method:    setCurrentGlyph
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sun_font_ColorGlyphSurfaceData_setCurrentGlyph
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
