/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_SunToolkit */

#ifndef _Included_sun_awt_SunToolkit
#define _Included_sun_awt_SunToolkit
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_SunToolkit_LONG_BITS
#define sun_awt_SunToolkit_LONG_BITS 64L
#undef sun_awt_SunToolkit_GRAB_EVENT_MASK
#define sun_awt_SunToolkit_GRAB_EVENT_MASK -2147483648L
#undef sun_awt_SunToolkit_MAX_BUTTONS_SUPPORTED
#define sun_awt_SunToolkit_MAX_BUTTONS_SUPPORTED 20L
#undef sun_awt_SunToolkit_DEFAULT_WAIT_TIME
#define sun_awt_SunToolkit_DEFAULT_WAIT_TIME 10000L
#undef sun_awt_SunToolkit_MAX_ITERS
#define sun_awt_SunToolkit_MAX_ITERS 100L
#undef sun_awt_SunToolkit_MIN_ITERS
#define sun_awt_SunToolkit_MIN_ITERS 1L
#undef sun_awt_SunToolkit_MINIMAL_DELAY
#define sun_awt_SunToolkit_MINIMAL_DELAY 5L
/*
 * Class:     sun_awt_SunToolkit
 * Method:    closeSplashScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_SunToolkit_closeSplashScreen
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
