#include <java/sql/DatabaseMetaData.h>

#include <java/sql/Connection.h>
#include <java/sql/ResultSet.h>
#include <java/sql/RowIdLifetime.h>
#include <jcpp.h>

using $ClassInfo = ::java::lang::ClassInfo;
using $FieldInfo = ::java::lang::FieldInfo;
using $MethodInfo = ::java::lang::MethodInfo;
using $Connection = ::java::sql::Connection;
using $ResultSet = ::java::sql::ResultSet;
using $RowIdLifetime = ::java::sql::RowIdLifetime;

namespace java {
	namespace sql {

$FieldInfo _DatabaseMetaData_FieldInfo_[] = {
	{"procedureResultUnknown", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureResultUnknown)},
	{"procedureNoResult", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureNoResult)},
	{"procedureReturnsResult", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureReturnsResult)},
	{"procedureColumnUnknown", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureColumnUnknown)},
	{"procedureColumnIn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureColumnIn)},
	{"procedureColumnInOut", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureColumnInOut)},
	{"procedureColumnOut", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureColumnOut)},
	{"procedureColumnReturn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureColumnReturn)},
	{"procedureColumnResult", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureColumnResult)},
	{"procedureNoNulls", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureNoNulls)},
	{"procedureNullable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureNullable)},
	{"procedureNullableUnknown", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, procedureNullableUnknown)},
	{"columnNoNulls", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, columnNoNulls)},
	{"columnNullable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, columnNullable)},
	{"columnNullableUnknown", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, columnNullableUnknown)},
	{"bestRowTemporary", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, bestRowTemporary)},
	{"bestRowTransaction", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, bestRowTransaction)},
	{"bestRowSession", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, bestRowSession)},
	{"bestRowUnknown", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, bestRowUnknown)},
	{"bestRowNotPseudo", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, bestRowNotPseudo)},
	{"bestRowPseudo", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, bestRowPseudo)},
	{"versionColumnUnknown", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, versionColumnUnknown)},
	{"versionColumnNotPseudo", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, versionColumnNotPseudo)},
	{"versionColumnPseudo", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, versionColumnPseudo)},
	{"importedKeyCascade", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, importedKeyCascade)},
	{"importedKeyRestrict", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, importedKeyRestrict)},
	{"importedKeySetNull", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, importedKeySetNull)},
	{"importedKeyNoAction", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, importedKeyNoAction)},
	{"importedKeySetDefault", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, importedKeySetDefault)},
	{"importedKeyInitiallyDeferred", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, importedKeyInitiallyDeferred)},
	{"importedKeyInitiallyImmediate", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, importedKeyInitiallyImmediate)},
	{"importedKeyNotDeferrable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, importedKeyNotDeferrable)},
	{"typeNoNulls", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, typeNoNulls)},
	{"typeNullable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, typeNullable)},
	{"typeNullableUnknown", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, typeNullableUnknown)},
	{"typePredNone", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, typePredNone)},
	{"typePredChar", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, typePredChar)},
	{"typePredBasic", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, typePredBasic)},
	{"typeSearchable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, typeSearchable)},
	{"tableIndexStatistic", "S", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, tableIndexStatistic)},
	{"tableIndexClustered", "S", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, tableIndexClustered)},
	{"tableIndexHashed", "S", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, tableIndexHashed)},
	{"tableIndexOther", "S", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, tableIndexOther)},
	{"attributeNoNulls", "S", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, attributeNoNulls)},
	{"attributeNullable", "S", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, attributeNullable)},
	{"attributeNullableUnknown", "S", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, attributeNullableUnknown)},
	{"sqlStateXOpen", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, sqlStateXOpen)},
	{"sqlStateSQL", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, sqlStateSQL)},
	{"sqlStateSQL99", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, sqlStateSQL99)},
	{"functionColumnUnknown", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionColumnUnknown)},
	{"functionColumnIn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionColumnIn)},
	{"functionColumnInOut", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionColumnInOut)},
	{"functionColumnOut", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionColumnOut)},
	{"functionReturn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionReturn)},
	{"functionColumnResult", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionColumnResult)},
	{"functionNoNulls", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionNoNulls)},
	{"functionNullable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionNullable)},
	{"functionNullableUnknown", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionNullableUnknown)},
	{"functionResultUnknown", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionResultUnknown)},
	{"functionNoTable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionNoTable)},
	{"functionReturnsTable", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(DatabaseMetaData, functionReturnsTable)},
	{}
};

$MethodInfo _DatabaseMetaData_MethodInfo_[] = {
	{"allProceduresAreCallable", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, allProceduresAreCallable, bool), "java.sql.SQLException"},
	{"allTablesAreSelectable", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, allTablesAreSelectable, bool), "java.sql.SQLException"},
	{"autoCommitFailureClosesAllResultSets", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, autoCommitFailureClosesAllResultSets, bool), "java.sql.SQLException"},
	{"dataDefinitionCausesTransactionCommit", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, dataDefinitionCausesTransactionCommit, bool), "java.sql.SQLException"},
	{"dataDefinitionIgnoredInTransactions", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, dataDefinitionIgnoredInTransactions, bool), "java.sql.SQLException"},
	{"deletesAreDetected", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, deletesAreDetected, bool, int32_t), "java.sql.SQLException"},
	{"doesMaxRowSizeIncludeBlobs", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, doesMaxRowSizeIncludeBlobs, bool), "java.sql.SQLException"},
	{"generatedKeyAlwaysReturned", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, generatedKeyAlwaysReturned, bool), "java.sql.SQLException"},
	{"getAttributes", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getAttributes, $ResultSet*, $String*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getBestRowIdentifier", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZ)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getBestRowIdentifier, $ResultSet*, $String*, $String*, $String*, int32_t, bool), "java.sql.SQLException"},
	{"getCatalogSeparator", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getCatalogSeparator, $String*), "java.sql.SQLException"},
	{"getCatalogTerm", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getCatalogTerm, $String*), "java.sql.SQLException"},
	{"getCatalogs", "()Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getCatalogs, $ResultSet*), "java.sql.SQLException"},
	{"getClientInfoProperties", "()Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getClientInfoProperties, $ResultSet*), "java.sql.SQLException"},
	{"getColumnPrivileges", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getColumnPrivileges, $ResultSet*, $String*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getColumns", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getColumns, $ResultSet*, $String*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getConnection", "()Ljava/sql/Connection;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getConnection, $Connection*), "java.sql.SQLException"},
	{"getCrossReference", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getCrossReference, $ResultSet*, $String*, $String*, $String*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getDatabaseMajorVersion", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getDatabaseMajorVersion, int32_t), "java.sql.SQLException"},
	{"getDatabaseMinorVersion", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getDatabaseMinorVersion, int32_t), "java.sql.SQLException"},
	{"getDatabaseProductName", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getDatabaseProductName, $String*), "java.sql.SQLException"},
	{"getDatabaseProductVersion", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getDatabaseProductVersion, $String*), "java.sql.SQLException"},
	{"getDefaultTransactionIsolation", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getDefaultTransactionIsolation, int32_t), "java.sql.SQLException"},
	{"getDriverMajorVersion", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getDriverMajorVersion, int32_t)},
	{"getDriverMinorVersion", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getDriverMinorVersion, int32_t)},
	{"getDriverName", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getDriverName, $String*), "java.sql.SQLException"},
	{"getDriverVersion", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getDriverVersion, $String*), "java.sql.SQLException"},
	{"getExportedKeys", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getExportedKeys, $ResultSet*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getExtraNameCharacters", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getExtraNameCharacters, $String*), "java.sql.SQLException"},
	{"getFunctionColumns", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getFunctionColumns, $ResultSet*, $String*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getFunctions", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getFunctions, $ResultSet*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getIdentifierQuoteString", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getIdentifierQuoteString, $String*), "java.sql.SQLException"},
	{"getImportedKeys", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getImportedKeys, $ResultSet*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getIndexInfo", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZ)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getIndexInfo, $ResultSet*, $String*, $String*, $String*, bool, bool), "java.sql.SQLException"},
	{"getJDBCMajorVersion", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getJDBCMajorVersion, int32_t), "java.sql.SQLException"},
	{"getJDBCMinorVersion", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getJDBCMinorVersion, int32_t), "java.sql.SQLException"},
	{"getMaxBinaryLiteralLength", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxBinaryLiteralLength, int32_t), "java.sql.SQLException"},
	{"getMaxCatalogNameLength", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxCatalogNameLength, int32_t), "java.sql.SQLException"},
	{"getMaxCharLiteralLength", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxCharLiteralLength, int32_t), "java.sql.SQLException"},
	{"getMaxColumnNameLength", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxColumnNameLength, int32_t), "java.sql.SQLException"},
	{"getMaxColumnsInGroupBy", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxColumnsInGroupBy, int32_t), "java.sql.SQLException"},
	{"getMaxColumnsInIndex", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxColumnsInIndex, int32_t), "java.sql.SQLException"},
	{"getMaxColumnsInOrderBy", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxColumnsInOrderBy, int32_t), "java.sql.SQLException"},
	{"getMaxColumnsInSelect", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxColumnsInSelect, int32_t), "java.sql.SQLException"},
	{"getMaxColumnsInTable", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxColumnsInTable, int32_t), "java.sql.SQLException"},
	{"getMaxConnections", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxConnections, int32_t), "java.sql.SQLException"},
	{"getMaxCursorNameLength", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxCursorNameLength, int32_t), "java.sql.SQLException"},
	{"getMaxIndexLength", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxIndexLength, int32_t), "java.sql.SQLException"},
	{"getMaxLogicalLobSize", "()J", nullptr, $PUBLIC, $virtualMethod(DatabaseMetaData, getMaxLogicalLobSize, int64_t), "java.sql.SQLException"},
	{"getMaxProcedureNameLength", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxProcedureNameLength, int32_t), "java.sql.SQLException"},
	{"getMaxRowSize", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxRowSize, int32_t), "java.sql.SQLException"},
	{"getMaxSchemaNameLength", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxSchemaNameLength, int32_t), "java.sql.SQLException"},
	{"getMaxStatementLength", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxStatementLength, int32_t), "java.sql.SQLException"},
	{"getMaxStatements", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxStatements, int32_t), "java.sql.SQLException"},
	{"getMaxTableNameLength", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxTableNameLength, int32_t), "java.sql.SQLException"},
	{"getMaxTablesInSelect", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxTablesInSelect, int32_t), "java.sql.SQLException"},
	{"getMaxUserNameLength", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getMaxUserNameLength, int32_t), "java.sql.SQLException"},
	{"getNumericFunctions", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getNumericFunctions, $String*), "java.sql.SQLException"},
	{"getPrimaryKeys", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getPrimaryKeys, $ResultSet*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getProcedureColumns", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getProcedureColumns, $ResultSet*, $String*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getProcedureTerm", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getProcedureTerm, $String*), "java.sql.SQLException"},
	{"getProcedures", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getProcedures, $ResultSet*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getPseudoColumns", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getPseudoColumns, $ResultSet*, $String*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getResultSetHoldability", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getResultSetHoldability, int32_t), "java.sql.SQLException"},
	{"getRowIdLifetime", "()Ljava/sql/RowIdLifetime;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getRowIdLifetime, $RowIdLifetime*), "java.sql.SQLException"},
	{"getSQLKeywords", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getSQLKeywords, $String*), "java.sql.SQLException"},
	{"getSQLStateType", "()I", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getSQLStateType, int32_t), "java.sql.SQLException"},
	{"getSchemaTerm", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getSchemaTerm, $String*), "java.sql.SQLException"},
	{"getSchemas", "()Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getSchemas, $ResultSet*), "java.sql.SQLException"},
	{"getSchemas", "(Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getSchemas, $ResultSet*, $String*, $String*), "java.sql.SQLException"},
	{"getSearchStringEscape", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getSearchStringEscape, $String*), "java.sql.SQLException"},
	{"getStringFunctions", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getStringFunctions, $String*), "java.sql.SQLException"},
	{"getSuperTables", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getSuperTables, $ResultSet*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getSuperTypes", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getSuperTypes, $ResultSet*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getSystemFunctions", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getSystemFunctions, $String*), "java.sql.SQLException"},
	{"getTablePrivileges", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getTablePrivileges, $ResultSet*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"getTableTypes", "()Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getTableTypes, $ResultSet*), "java.sql.SQLException"},
	{"getTables", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getTables, $ResultSet*, $String*, $String*, $String*, $StringArray*), "java.sql.SQLException"},
	{"getTimeDateFunctions", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getTimeDateFunctions, $String*), "java.sql.SQLException"},
	{"getTypeInfo", "()Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getTypeInfo, $ResultSet*), "java.sql.SQLException"},
	{"getUDTs", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[I)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getUDTs, $ResultSet*, $String*, $String*, $String*, $ints*), "java.sql.SQLException"},
	{"getURL", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getURL, $String*), "java.sql.SQLException"},
	{"getUserName", "()Ljava/lang/String;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getUserName, $String*), "java.sql.SQLException"},
	{"getVersionColumns", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/sql/ResultSet;", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, getVersionColumns, $ResultSet*, $String*, $String*, $String*), "java.sql.SQLException"},
	{"insertsAreDetected", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, insertsAreDetected, bool, int32_t), "java.sql.SQLException"},
	{"isCatalogAtStart", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, isCatalogAtStart, bool), "java.sql.SQLException"},
	{"isReadOnly", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, isReadOnly, bool), "java.sql.SQLException"},
	{"locatorsUpdateCopy", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, locatorsUpdateCopy, bool), "java.sql.SQLException"},
	{"nullPlusNonNullIsNull", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, nullPlusNonNullIsNull, bool), "java.sql.SQLException"},
	{"nullsAreSortedAtEnd", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, nullsAreSortedAtEnd, bool), "java.sql.SQLException"},
	{"nullsAreSortedAtStart", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, nullsAreSortedAtStart, bool), "java.sql.SQLException"},
	{"nullsAreSortedHigh", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, nullsAreSortedHigh, bool), "java.sql.SQLException"},
	{"nullsAreSortedLow", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, nullsAreSortedLow, bool), "java.sql.SQLException"},
	{"othersDeletesAreVisible", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, othersDeletesAreVisible, bool, int32_t), "java.sql.SQLException"},
	{"othersInsertsAreVisible", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, othersInsertsAreVisible, bool, int32_t), "java.sql.SQLException"},
	{"othersUpdatesAreVisible", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, othersUpdatesAreVisible, bool, int32_t), "java.sql.SQLException"},
	{"ownDeletesAreVisible", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, ownDeletesAreVisible, bool, int32_t), "java.sql.SQLException"},
	{"ownInsertsAreVisible", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, ownInsertsAreVisible, bool, int32_t), "java.sql.SQLException"},
	{"ownUpdatesAreVisible", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, ownUpdatesAreVisible, bool, int32_t), "java.sql.SQLException"},
	{"storesLowerCaseIdentifiers", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, storesLowerCaseIdentifiers, bool), "java.sql.SQLException"},
	{"storesLowerCaseQuotedIdentifiers", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, storesLowerCaseQuotedIdentifiers, bool), "java.sql.SQLException"},
	{"storesMixedCaseIdentifiers", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, storesMixedCaseIdentifiers, bool), "java.sql.SQLException"},
	{"storesMixedCaseQuotedIdentifiers", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, storesMixedCaseQuotedIdentifiers, bool), "java.sql.SQLException"},
	{"storesUpperCaseIdentifiers", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, storesUpperCaseIdentifiers, bool), "java.sql.SQLException"},
	{"storesUpperCaseQuotedIdentifiers", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, storesUpperCaseQuotedIdentifiers, bool), "java.sql.SQLException"},
	{"supportsANSI92EntryLevelSQL", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsANSI92EntryLevelSQL, bool), "java.sql.SQLException"},
	{"supportsANSI92FullSQL", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsANSI92FullSQL, bool), "java.sql.SQLException"},
	{"supportsANSI92IntermediateSQL", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsANSI92IntermediateSQL, bool), "java.sql.SQLException"},
	{"supportsAlterTableWithAddColumn", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsAlterTableWithAddColumn, bool), "java.sql.SQLException"},
	{"supportsAlterTableWithDropColumn", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsAlterTableWithDropColumn, bool), "java.sql.SQLException"},
	{"supportsBatchUpdates", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsBatchUpdates, bool), "java.sql.SQLException"},
	{"supportsCatalogsInDataManipulation", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsCatalogsInDataManipulation, bool), "java.sql.SQLException"},
	{"supportsCatalogsInIndexDefinitions", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsCatalogsInIndexDefinitions, bool), "java.sql.SQLException"},
	{"supportsCatalogsInPrivilegeDefinitions", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsCatalogsInPrivilegeDefinitions, bool), "java.sql.SQLException"},
	{"supportsCatalogsInProcedureCalls", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsCatalogsInProcedureCalls, bool), "java.sql.SQLException"},
	{"supportsCatalogsInTableDefinitions", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsCatalogsInTableDefinitions, bool), "java.sql.SQLException"},
	{"supportsColumnAliasing", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsColumnAliasing, bool), "java.sql.SQLException"},
	{"supportsConvert", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsConvert, bool), "java.sql.SQLException"},
	{"supportsConvert", "(II)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsConvert, bool, int32_t, int32_t), "java.sql.SQLException"},
	{"supportsCoreSQLGrammar", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsCoreSQLGrammar, bool), "java.sql.SQLException"},
	{"supportsCorrelatedSubqueries", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsCorrelatedSubqueries, bool), "java.sql.SQLException"},
	{"supportsDataDefinitionAndDataManipulationTransactions", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsDataDefinitionAndDataManipulationTransactions, bool), "java.sql.SQLException"},
	{"supportsDataManipulationTransactionsOnly", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsDataManipulationTransactionsOnly, bool), "java.sql.SQLException"},
	{"supportsDifferentTableCorrelationNames", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsDifferentTableCorrelationNames, bool), "java.sql.SQLException"},
	{"supportsExpressionsInOrderBy", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsExpressionsInOrderBy, bool), "java.sql.SQLException"},
	{"supportsExtendedSQLGrammar", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsExtendedSQLGrammar, bool), "java.sql.SQLException"},
	{"supportsFullOuterJoins", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsFullOuterJoins, bool), "java.sql.SQLException"},
	{"supportsGetGeneratedKeys", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsGetGeneratedKeys, bool), "java.sql.SQLException"},
	{"supportsGroupBy", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsGroupBy, bool), "java.sql.SQLException"},
	{"supportsGroupByBeyondSelect", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsGroupByBeyondSelect, bool), "java.sql.SQLException"},
	{"supportsGroupByUnrelated", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsGroupByUnrelated, bool), "java.sql.SQLException"},
	{"supportsIntegrityEnhancementFacility", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsIntegrityEnhancementFacility, bool), "java.sql.SQLException"},
	{"supportsLikeEscapeClause", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsLikeEscapeClause, bool), "java.sql.SQLException"},
	{"supportsLimitedOuterJoins", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsLimitedOuterJoins, bool), "java.sql.SQLException"},
	{"supportsMinimumSQLGrammar", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsMinimumSQLGrammar, bool), "java.sql.SQLException"},
	{"supportsMixedCaseIdentifiers", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsMixedCaseIdentifiers, bool), "java.sql.SQLException"},
	{"supportsMixedCaseQuotedIdentifiers", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsMixedCaseQuotedIdentifiers, bool), "java.sql.SQLException"},
	{"supportsMultipleOpenResults", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsMultipleOpenResults, bool), "java.sql.SQLException"},
	{"supportsMultipleResultSets", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsMultipleResultSets, bool), "java.sql.SQLException"},
	{"supportsMultipleTransactions", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsMultipleTransactions, bool), "java.sql.SQLException"},
	{"supportsNamedParameters", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsNamedParameters, bool), "java.sql.SQLException"},
	{"supportsNonNullableColumns", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsNonNullableColumns, bool), "java.sql.SQLException"},
	{"supportsOpenCursorsAcrossCommit", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsOpenCursorsAcrossCommit, bool), "java.sql.SQLException"},
	{"supportsOpenCursorsAcrossRollback", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsOpenCursorsAcrossRollback, bool), "java.sql.SQLException"},
	{"supportsOpenStatementsAcrossCommit", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsOpenStatementsAcrossCommit, bool), "java.sql.SQLException"},
	{"supportsOpenStatementsAcrossRollback", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsOpenStatementsAcrossRollback, bool), "java.sql.SQLException"},
	{"supportsOrderByUnrelated", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsOrderByUnrelated, bool), "java.sql.SQLException"},
	{"supportsOuterJoins", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsOuterJoins, bool), "java.sql.SQLException"},
	{"supportsPositionedDelete", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsPositionedDelete, bool), "java.sql.SQLException"},
	{"supportsPositionedUpdate", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsPositionedUpdate, bool), "java.sql.SQLException"},
	{"supportsRefCursors", "()Z", nullptr, $PUBLIC, $virtualMethod(DatabaseMetaData, supportsRefCursors, bool), "java.sql.SQLException"},
	{"supportsResultSetConcurrency", "(II)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsResultSetConcurrency, bool, int32_t, int32_t), "java.sql.SQLException"},
	{"supportsResultSetHoldability", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsResultSetHoldability, bool, int32_t), "java.sql.SQLException"},
	{"supportsResultSetType", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsResultSetType, bool, int32_t), "java.sql.SQLException"},
	{"supportsSavepoints", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsSavepoints, bool), "java.sql.SQLException"},
	{"supportsSchemasInDataManipulation", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsSchemasInDataManipulation, bool), "java.sql.SQLException"},
	{"supportsSchemasInIndexDefinitions", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsSchemasInIndexDefinitions, bool), "java.sql.SQLException"},
	{"supportsSchemasInPrivilegeDefinitions", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsSchemasInPrivilegeDefinitions, bool), "java.sql.SQLException"},
	{"supportsSchemasInProcedureCalls", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsSchemasInProcedureCalls, bool), "java.sql.SQLException"},
	{"supportsSchemasInTableDefinitions", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsSchemasInTableDefinitions, bool), "java.sql.SQLException"},
	{"supportsSelectForUpdate", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsSelectForUpdate, bool), "java.sql.SQLException"},
	{"supportsSharding", "()Z", nullptr, $PUBLIC, $virtualMethod(DatabaseMetaData, supportsSharding, bool), "java.sql.SQLException"},
	{"supportsStatementPooling", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsStatementPooling, bool), "java.sql.SQLException"},
	{"supportsStoredFunctionsUsingCallSyntax", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsStoredFunctionsUsingCallSyntax, bool), "java.sql.SQLException"},
	{"supportsStoredProcedures", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsStoredProcedures, bool), "java.sql.SQLException"},
	{"supportsSubqueriesInComparisons", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsSubqueriesInComparisons, bool), "java.sql.SQLException"},
	{"supportsSubqueriesInExists", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsSubqueriesInExists, bool), "java.sql.SQLException"},
	{"supportsSubqueriesInIns", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsSubqueriesInIns, bool), "java.sql.SQLException"},
	{"supportsSubqueriesInQuantifieds", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsSubqueriesInQuantifieds, bool), "java.sql.SQLException"},
	{"supportsTableCorrelationNames", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsTableCorrelationNames, bool), "java.sql.SQLException"},
	{"supportsTransactionIsolationLevel", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsTransactionIsolationLevel, bool, int32_t), "java.sql.SQLException"},
	{"supportsTransactions", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsTransactions, bool), "java.sql.SQLException"},
	{"supportsUnion", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsUnion, bool), "java.sql.SQLException"},
	{"supportsUnionAll", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, supportsUnionAll, bool), "java.sql.SQLException"},
	{"updatesAreDetected", "(I)Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, updatesAreDetected, bool, int32_t), "java.sql.SQLException"},
	{"usesLocalFilePerTable", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, usesLocalFilePerTable, bool), "java.sql.SQLException"},
	{"usesLocalFiles", "()Z", nullptr, $PUBLIC | $ABSTRACT, $virtualMethod(DatabaseMetaData, usesLocalFiles, bool), "java.sql.SQLException"},
	{}
};

$ClassInfo _DatabaseMetaData_ClassInfo_ = {
	$PUBLIC | $INTERFACE | $ABSTRACT,
	"java.sql.DatabaseMetaData",
	nullptr,
	"java.sql.Wrapper",
	_DatabaseMetaData_FieldInfo_,
	_DatabaseMetaData_MethodInfo_
};

$Object* allocate$DatabaseMetaData($Class* clazz) {
	return $of($alloc(DatabaseMetaData));
}

int64_t DatabaseMetaData::getMaxLogicalLobSize() {
	return 0;
}

bool DatabaseMetaData::supportsRefCursors() {
	return false;
}

bool DatabaseMetaData::supportsSharding() {
	return false;
}

$Class* DatabaseMetaData::load$($String* name, bool initialize) {
	$loadClass(DatabaseMetaData, name, initialize, &_DatabaseMetaData_ClassInfo_, allocate$DatabaseMetaData);
	return class$;
}

$Class* DatabaseMetaData::class$ = nullptr;

	} // sql
} // java