/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_X11InputMethodBase */

#ifndef _Included_sun_awt_X11InputMethodBase
#define _Included_sun_awt_X11InputMethodBase
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_X11InputMethodBase_XIMReverse
#define sun_awt_X11InputMethodBase_XIMReverse 1L
#undef sun_awt_X11InputMethodBase_XIMUnderline
#define sun_awt_X11InputMethodBase_XIMUnderline 2L
#undef sun_awt_X11InputMethodBase_XIMHighlight
#define sun_awt_X11InputMethodBase_XIMHighlight 4L
#undef sun_awt_X11InputMethodBase_XIMPrimary
#define sun_awt_X11InputMethodBase_XIMPrimary 32L
#undef sun_awt_X11InputMethodBase_XIMSecondary
#define sun_awt_X11InputMethodBase_XIMSecondary 64L
#undef sun_awt_X11InputMethodBase_XIMTertiary
#define sun_awt_X11InputMethodBase_XIMTertiary 128L
#undef sun_awt_X11InputMethodBase_XIMVisibleToForward
#define sun_awt_X11InputMethodBase_XIMVisibleToForward 256L
#undef sun_awt_X11InputMethodBase_XIMVisibleToBackward
#define sun_awt_X11InputMethodBase_XIMVisibleToBackward 512L
#undef sun_awt_X11InputMethodBase_XIMVisibleCenter
#define sun_awt_X11InputMethodBase_XIMVisibleCenter 1024L
#undef sun_awt_X11InputMethodBase_XIMVisibleMask
#define sun_awt_X11InputMethodBase_XIMVisibleMask 1792L
#undef sun_awt_X11InputMethodBase_INITIAL_SIZE
#define sun_awt_X11InputMethodBase_INITIAL_SIZE 64L
/*
 * Class:     sun_awt_X11InputMethodBase
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11InputMethodBase_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_X11InputMethodBase
 * Method:    turnoffStatusWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11InputMethodBase_turnoffStatusWindow
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_X11InputMethodBase
 * Method:    disposeXIC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11InputMethodBase_disposeXIC
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_X11InputMethodBase
 * Method:    resetXIC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_awt_X11InputMethodBase_resetXIC
  (JNIEnv *, jobject);

/*
 * Class:     sun_awt_X11InputMethodBase
 * Method:    setCompositionEnabledNative
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_X11InputMethodBase_setCompositionEnabledNative
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sun_awt_X11InputMethodBase
 * Method:    isCompositionEnabledNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_X11InputMethodBase_isCompositionEnabledNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
