/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_X11_XTaskbarPeer */

#ifndef _Included_sun_awt_X11_XTaskbarPeer
#define _Included_sun_awt_X11_XTaskbarPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_awt_X11_XTaskbarPeer
 * Method:    init
 * Signature: (Ljava/lang/String;IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_sun_awt_X11_XTaskbarPeer_init
  (JNIEnv *, jclass, jstring, jint, jboolean);

/*
 * Class:     sun_awt_X11_XTaskbarPeer
 * Method:    runloop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11_XTaskbarPeer_runloop
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_X11_XTaskbarPeer
 * Method:    setBadge
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11_XTaskbarPeer_setBadge
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     sun_awt_X11_XTaskbarPeer
 * Method:    updateProgress
 * Signature: (DZ)V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11_XTaskbarPeer_updateProgress
  (JNIEnv *, jobject, jdouble, jboolean);

/*
 * Class:     sun_awt_X11_XTaskbarPeer
 * Method:    setUrgent
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11_XTaskbarPeer_setUrgent
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sun_awt_X11_XTaskbarPeer
 * Method:    setNativeMenu
 * Signature: ([Ljava/awt/MenuItem;)V
 */
JNIEXPORT void JNICALL Java_sun_awt_X11_XTaskbarPeer_setNativeMenu
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
