#include <com/sun/tools/javac/jvm/ByteCodes.h>

#include <jcpp.h>

using $ClassInfo = ::java::lang::ClassInfo;
using $FieldInfo = ::java::lang::FieldInfo;

namespace com {
	namespace sun {
		namespace tools {
			namespace javac {
				namespace jvm {

$FieldInfo _ByteCodes_FieldInfo_[] = {
	{"illegal", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, illegal)},
	{"nop", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, nop)},
	{"aconst_null", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, aconst_null)},
	{"iconst_m1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iconst_m1)},
	{"iconst_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iconst_0)},
	{"iconst_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iconst_1)},
	{"iconst_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iconst_2)},
	{"iconst_3", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iconst_3)},
	{"iconst_4", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iconst_4)},
	{"iconst_5", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iconst_5)},
	{"lconst_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lconst_0)},
	{"lconst_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lconst_1)},
	{"fconst_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fconst_0)},
	{"fconst_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fconst_1)},
	{"fconst_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fconst_2)},
	{"dconst_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dconst_0)},
	{"dconst_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dconst_1)},
	{"bipush", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, bipush)},
	{"sipush", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, sipush)},
	{"ldc1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ldc1)},
	{"ldc2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ldc2)},
	{"ldc2w", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ldc2w)},
	{"iload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iload)},
	{"lload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lload)},
	{"fload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fload)},
	{"dload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dload)},
	{"aload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, aload)},
	{"iload_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iload_0)},
	{"iload_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iload_1)},
	{"iload_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iload_2)},
	{"iload_3", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iload_3)},
	{"lload_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lload_0)},
	{"lload_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lload_1)},
	{"lload_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lload_2)},
	{"lload_3", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lload_3)},
	{"fload_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fload_0)},
	{"fload_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fload_1)},
	{"fload_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fload_2)},
	{"fload_3", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fload_3)},
	{"dload_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dload_0)},
	{"dload_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dload_1)},
	{"dload_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dload_2)},
	{"dload_3", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dload_3)},
	{"aload_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, aload_0)},
	{"aload_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, aload_1)},
	{"aload_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, aload_2)},
	{"aload_3", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, aload_3)},
	{"iaload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iaload)},
	{"laload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, laload)},
	{"faload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, faload)},
	{"daload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, daload)},
	{"aaload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, aaload)},
	{"baload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, baload)},
	{"caload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, caload)},
	{"saload", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, saload)},
	{"istore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, istore)},
	{"lstore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lstore)},
	{"fstore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fstore)},
	{"dstore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dstore)},
	{"astore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, astore)},
	{"istore_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, istore_0)},
	{"istore_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, istore_1)},
	{"istore_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, istore_2)},
	{"istore_3", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, istore_3)},
	{"lstore_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lstore_0)},
	{"lstore_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lstore_1)},
	{"lstore_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lstore_2)},
	{"lstore_3", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lstore_3)},
	{"fstore_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fstore_0)},
	{"fstore_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fstore_1)},
	{"fstore_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fstore_2)},
	{"fstore_3", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fstore_3)},
	{"dstore_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dstore_0)},
	{"dstore_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dstore_1)},
	{"dstore_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dstore_2)},
	{"dstore_3", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dstore_3)},
	{"astore_0", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, astore_0)},
	{"astore_1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, astore_1)},
	{"astore_2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, astore_2)},
	{"astore_3", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, astore_3)},
	{"iastore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iastore)},
	{"lastore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lastore)},
	{"fastore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fastore)},
	{"dastore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dastore)},
	{"aastore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, aastore)},
	{"bastore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, bastore)},
	{"castore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, castore)},
	{"sastore", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, sastore)},
	{"pop", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, pop)},
	{"pop2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, pop2)},
	{"dup", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dup)},
	{"dup_x1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dup_x1)},
	{"dup_x2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dup_x2)},
	{"dup2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dup2)},
	{"dup2_x1", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dup2_x1)},
	{"dup2_x2", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dup2_x2)},
	{"swap", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, swap)},
	{"iadd", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iadd)},
	{"ladd", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ladd)},
	{"fadd", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fadd)},
	{"dadd", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dadd)},
	{"isub", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, isub)},
	{"lsub", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lsub)},
	{"fsub", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fsub)},
	{"dsub", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dsub)},
	{"imul", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, imul)},
	{"lmul", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lmul)},
	{"fmul", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fmul)},
	{"dmul", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dmul)},
	{"idiv", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, idiv)},
	{"ldiv", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ldiv)},
	{"fdiv", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fdiv)},
	{"ddiv", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ddiv)},
	{"imod", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, imod)},
	{"lmod", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lmod)},
	{"fmod", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fmod)},
	{"dmod", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dmod)},
	{"ineg", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ineg)},
	{"lneg", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lneg)},
	{"fneg", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fneg)},
	{"dneg", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dneg)},
	{"ishl", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ishl)},
	{"lshl", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lshl)},
	{"ishr", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ishr)},
	{"lshr", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lshr)},
	{"iushr", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iushr)},
	{"lushr", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lushr)},
	{"iand", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iand)},
	{"land", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, land)},
	{"ior", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ior)},
	{"lor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lor)},
	{"ixor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ixor)},
	{"lxor", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lxor)},
	{"iinc", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iinc)},
	{"i2l", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, i2l)},
	{"i2f", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, i2f)},
	{"i2d", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, i2d)},
	{"l2i", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, l2i)},
	{"l2f", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, l2f)},
	{"l2d", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, l2d)},
	{"f2i", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, f2i)},
	{"f2l", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, f2l)},
	{"f2d", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, f2d)},
	{"d2i", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, d2i)},
	{"d2l", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, d2l)},
	{"d2f", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, d2f)},
	{"int2byte", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, int2byte)},
	{"int2char", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, int2char)},
	{"int2short", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, int2short)},
	{"lcmp", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lcmp)},
	{"fcmpl", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fcmpl)},
	{"fcmpg", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, fcmpg)},
	{"dcmpl", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dcmpl)},
	{"dcmpg", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dcmpg)},
	{"ifeq", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ifeq)},
	{"ifne", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ifne)},
	{"iflt", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iflt)},
	{"ifge", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ifge)},
	{"ifgt", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ifgt)},
	{"ifle", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ifle)},
	{"if_icmpeq", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, if_icmpeq)},
	{"if_icmpne", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, if_icmpne)},
	{"if_icmplt", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, if_icmplt)},
	{"if_icmpge", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, if_icmpge)},
	{"if_icmpgt", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, if_icmpgt)},
	{"if_icmple", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, if_icmple)},
	{"if_acmpeq", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, if_acmpeq)},
	{"if_acmpne", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, if_acmpne)},
	{"goto_", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, goto_)},
	{"jsr", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, jsr)},
	{"ret", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ret)},
	{"tableswitch", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, tableswitch)},
	{"lookupswitch", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lookupswitch)},
	{"ireturn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ireturn)},
	{"lreturn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lreturn)},
	{"freturn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, freturn)},
	{"dreturn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dreturn)},
	{"areturn", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, areturn)},
	{"return_", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, return_)},
	{"getstatic", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, getstatic)},
	{"putstatic", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, putstatic)},
	{"getfield", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, getfield)},
	{"putfield", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, putfield)},
	{"invokevirtual", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, invokevirtual)},
	{"invokespecial", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, invokespecial)},
	{"invokestatic", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, invokestatic)},
	{"invokeinterface", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, invokeinterface)},
	{"invokedynamic", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, invokedynamic)},
	{"new_", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, new_)},
	{"newarray", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, newarray)},
	{"anewarray", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, anewarray)},
	{"arraylength", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, arraylength)},
	{"athrow", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, athrow)},
	{"checkcast", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, checkcast)},
	{"instanceof_", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, instanceof_)},
	{"monitorenter", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, monitorenter)},
	{"monitorexit", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, monitorexit)},
	{"wide", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, wide)},
	{"multianewarray", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, multianewarray)},
	{"if_acmp_null", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, if_acmp_null)},
	{"if_acmp_nonnull", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, if_acmp_nonnull)},
	{"goto_w", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, goto_w)},
	{"jsr_w", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, jsr_w)},
	{"breakpoint", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, breakpoint)},
	{"ByteCodeCount", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ByteCodeCount)},
	{"string_add", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, string_add)},
	{"bool_not", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, bool_not)},
	{"bool_and", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, bool_and)},
	{"bool_or", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, bool_or)},
	{"ishll", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ishll)},
	{"lshll", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lshll)},
	{"ishrl", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, ishrl)},
	{"lshrl", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lshrl)},
	{"iushrl", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, iushrl)},
	{"lushrl", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, lushrl)},
	{"nullchk", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, nullchk)},
	{"error", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, error)},
	{"dontgoto", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, dontgoto)},
	{"preShift", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, preShift)},
	{"preMask", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, preMask)},
	{"INTcode", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, INTcode)},
	{"LONGcode", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, LONGcode)},
	{"FLOATcode", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, FLOATcode)},
	{"DOUBLEcode", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, DOUBLEcode)},
	{"OBJECTcode", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, OBJECTcode)},
	{"BYTEcode", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, BYTEcode)},
	{"CHARcode", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, CHARcode)},
	{"SHORTcode", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, SHORTcode)},
	{"VOIDcode", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, VOIDcode)},
	{"TypeCodeCount", "I", nullptr, $PUBLIC | $STATIC | $FINAL, $constField(ByteCodes, TypeCodeCount)},
	{"typecodeNames", "[Ljava/lang/String;", nullptr, $PUBLIC | $STATIC | $FINAL, $staticField(ByteCodes, typecodeNames)},
	{}
};

$ClassInfo _ByteCodes_ClassInfo_ = {
	$PUBLIC | $INTERFACE | $ABSTRACT,
	"com.sun.tools.javac.jvm.ByteCodes",
	nullptr,
	nullptr,
	_ByteCodes_FieldInfo_
};

$Object* allocate$ByteCodes($Class* clazz) {
	return $of($alloc(ByteCodes));
}

$StringArray* ByteCodes::typecodeNames = nullptr;

void clinit$ByteCodes($Class* class$) {
	$assignStatic(ByteCodes::typecodeNames, $new($StringArray, {
		"int"_s,
		"long"_s,
		"float"_s,
		"double"_s,
		"object"_s,
		"byte"_s,
		"char"_s,
		"short"_s,
		"void"_s,
		"oops"_s
	}));
}

$Class* ByteCodes::load$($String* name, bool initialize) {
	$loadClass(ByteCodes, name, initialize, &_ByteCodes_ClassInfo_, clinit$ByteCodes, allocate$ByteCodes);
	return class$;
}

$Class* ByteCodes::class$ = nullptr;

				} // jvm
			} // javac
		} // tools
	} // sun
} // com