/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_prefs_WindowsPreferences */

#ifndef _Included_java_util_prefs_WindowsPreferences
#define _Included_java_util_prefs_WindowsPreferences
#ifdef __cplusplus
extern "C" {
#endif
#undef java_util_prefs_WindowsPreferences_MAX_KEY_LENGTH
#define java_util_prefs_WindowsPreferences_MAX_KEY_LENGTH 80L
#undef java_util_prefs_WindowsPreferences_MAX_VALUE_LENGTH
#define java_util_prefs_WindowsPreferences_MAX_VALUE_LENGTH 8192L
#undef java_util_prefs_WindowsPreferences_MAX_NAME_LENGTH
#define java_util_prefs_WindowsPreferences_MAX_NAME_LENGTH 80L
#undef java_util_prefs_WindowsPreferences_CODE_POINT_U0000
#define java_util_prefs_WindowsPreferences_CODE_POINT_U0000 0L
#undef java_util_prefs_WindowsPreferences_HKEY_CURRENT_USER
#define java_util_prefs_WindowsPreferences_HKEY_CURRENT_USER -2147483647L
#undef java_util_prefs_WindowsPreferences_HKEY_LOCAL_MACHINE
#define java_util_prefs_WindowsPreferences_HKEY_LOCAL_MACHINE -2147483646L
#undef java_util_prefs_WindowsPreferences_USER_ROOT_NATIVE_HANDLE
#define java_util_prefs_WindowsPreferences_USER_ROOT_NATIVE_HANDLE -2147483647L
#undef java_util_prefs_WindowsPreferences_SYSTEM_ROOT_NATIVE_HANDLE
#define java_util_prefs_WindowsPreferences_SYSTEM_ROOT_NATIVE_HANDLE -2147483646L
#undef java_util_prefs_WindowsPreferences_MAX_WINDOWS_PATH_LENGTH
#define java_util_prefs_WindowsPreferences_MAX_WINDOWS_PATH_LENGTH 256L
#undef java_util_prefs_WindowsPreferences_ERROR_SUCCESS
#define java_util_prefs_WindowsPreferences_ERROR_SUCCESS 0L
#undef java_util_prefs_WindowsPreferences_ERROR_FILE_NOT_FOUND
#define java_util_prefs_WindowsPreferences_ERROR_FILE_NOT_FOUND 2L
#undef java_util_prefs_WindowsPreferences_ERROR_ACCESS_DENIED
#define java_util_prefs_WindowsPreferences_ERROR_ACCESS_DENIED 5L
#undef java_util_prefs_WindowsPreferences_NATIVE_HANDLE
#define java_util_prefs_WindowsPreferences_NATIVE_HANDLE 0L
#undef java_util_prefs_WindowsPreferences_ERROR_CODE
#define java_util_prefs_WindowsPreferences_ERROR_CODE 1L
#undef java_util_prefs_WindowsPreferences_SUBKEYS_NUMBER
#define java_util_prefs_WindowsPreferences_SUBKEYS_NUMBER 0L
#undef java_util_prefs_WindowsPreferences_VALUES_NUMBER
#define java_util_prefs_WindowsPreferences_VALUES_NUMBER 2L
#undef java_util_prefs_WindowsPreferences_MAX_KEY_LENGTH
#define java_util_prefs_WindowsPreferences_MAX_KEY_LENGTH 3L
#undef java_util_prefs_WindowsPreferences_MAX_VALUE_NAME_LENGTH
#define java_util_prefs_WindowsPreferences_MAX_VALUE_NAME_LENGTH 4L
#undef java_util_prefs_WindowsPreferences_DISPOSITION
#define java_util_prefs_WindowsPreferences_DISPOSITION 2L
#undef java_util_prefs_WindowsPreferences_REG_CREATED_NEW_KEY
#define java_util_prefs_WindowsPreferences_REG_CREATED_NEW_KEY 1L
#undef java_util_prefs_WindowsPreferences_REG_OPENED_EXISTING_KEY
#define java_util_prefs_WindowsPreferences_REG_OPENED_EXISTING_KEY 2L
#undef java_util_prefs_WindowsPreferences_NULL_NATIVE_HANDLE
#define java_util_prefs_WindowsPreferences_NULL_NATIVE_HANDLE 0L
#undef java_util_prefs_WindowsPreferences_DELETE
#define java_util_prefs_WindowsPreferences_DELETE 65536L
#undef java_util_prefs_WindowsPreferences_KEY_QUERY_VALUE
#define java_util_prefs_WindowsPreferences_KEY_QUERY_VALUE 1L
#undef java_util_prefs_WindowsPreferences_KEY_SET_VALUE
#define java_util_prefs_WindowsPreferences_KEY_SET_VALUE 2L
#undef java_util_prefs_WindowsPreferences_KEY_CREATE_SUB_KEY
#define java_util_prefs_WindowsPreferences_KEY_CREATE_SUB_KEY 4L
#undef java_util_prefs_WindowsPreferences_KEY_ENUMERATE_SUB_KEYS
#define java_util_prefs_WindowsPreferences_KEY_ENUMERATE_SUB_KEYS 8L
#undef java_util_prefs_WindowsPreferences_KEY_READ
#define java_util_prefs_WindowsPreferences_KEY_READ 131097L
#undef java_util_prefs_WindowsPreferences_KEY_WRITE
#define java_util_prefs_WindowsPreferences_KEY_WRITE 131078L
#undef java_util_prefs_WindowsPreferences_KEY_ALL_ACCESS
#define java_util_prefs_WindowsPreferences_KEY_ALL_ACCESS 983103L
/*
 * Class:     java_util_prefs_WindowsPreferences
 * Method:    WindowsRegOpenKey
 * Signature: (J[BI)[J
 */
JNIEXPORT jlongArray JNICALL Java_java_util_prefs_WindowsPreferences_WindowsRegOpenKey
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     java_util_prefs_WindowsPreferences
 * Method:    WindowsRegCloseKey
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_java_util_prefs_WindowsPreferences_WindowsRegCloseKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_prefs_WindowsPreferences
 * Method:    WindowsRegCreateKeyEx
 * Signature: (J[B)[J
 */
JNIEXPORT jlongArray JNICALL Java_java_util_prefs_WindowsPreferences_WindowsRegCreateKeyEx
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     java_util_prefs_WindowsPreferences
 * Method:    WindowsRegDeleteKey
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_java_util_prefs_WindowsPreferences_WindowsRegDeleteKey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     java_util_prefs_WindowsPreferences
 * Method:    WindowsRegFlushKey
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_java_util_prefs_WindowsPreferences_WindowsRegFlushKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_prefs_WindowsPreferences
 * Method:    WindowsRegQueryValueEx
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_util_prefs_WindowsPreferences_WindowsRegQueryValueEx
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     java_util_prefs_WindowsPreferences
 * Method:    WindowsRegSetValueEx
 * Signature: (J[B[B)I
 */
JNIEXPORT jint JNICALL Java_java_util_prefs_WindowsPreferences_WindowsRegSetValueEx
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     java_util_prefs_WindowsPreferences
 * Method:    WindowsRegDeleteValue
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_java_util_prefs_WindowsPreferences_WindowsRegDeleteValue
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     java_util_prefs_WindowsPreferences
 * Method:    WindowsRegQueryInfoKey
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_java_util_prefs_WindowsPreferences_WindowsRegQueryInfoKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_prefs_WindowsPreferences
 * Method:    WindowsRegEnumKeyEx
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_util_prefs_WindowsPreferences_WindowsRegEnumKeyEx
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     java_util_prefs_WindowsPreferences
 * Method:    WindowsRegEnumValue
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_util_prefs_WindowsPreferences_WindowsRegEnumValue
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
