#include <javax/swing/text/html/default.css.resource.h>

namespace javax {
    namespace swing {
        namespace text {
            namespace html {

const char default$css$resource$data[] =
"/*\n"
" * Copyright (c) 1997, 2005, Oracle and/or its affiliates. All rights reserved.\n"
" * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.\n"
" *\n"
" * This code is free software; you can redistribute it and/or modify it\n"
" * under the terms of the GNU General Public License version 2 only, as\n"
" * published by the Free Software Foundation.  Oracle designates this\n"
" * particular file as subject to the \"Classpath\" exception as provided\n"
" * by Oracle in the LICENSE file that accompanied this code.\n"
" *\n"
" * This code is distributed in the hope that it will be useful, but WITHOUT\n"
" * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or\n"
" * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License\n"
" * version 2 for more details (a copy is included in the LICENSE file that\n"
" * accompanied this code).\n"
" *\n"
" * You should have received a copy of the GNU General Public License version\n"
" * 2 along with this work; if not, write to the Free Software Foundation,\n"
" * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.\n"
" *\n"
" * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA\n"
" * or visit www.oracle.com if you need additional information or have any\n"
" * questions.\n"
" */\n"
"\n"
"/*\n"
" */\n"
"\n"
"body  {font-size: 14pt;\n"
"       font-family: Serif;\n"
"       font-weight: normal;\n"
"       margin-left: 0;\n"
"       margin-right: 0;\n"
"       color: black}\n"
"\n"
"p   {margin-top: 15}\n"
"\n"
"h1  {font-size: x-large;\n"
"     font-weight: bold;\n"
"     margin-top: 10;\n"
"     margin-bottom: 10}\n"
"\n"
"h2 {font-size: large;\n"
"    font-weight: bold;\n"
"    margin-top: 10;\n"
"    margin-bottom: 10}\n"
"\n"
"h3 {font-size: medium;\n"
"    font-weight: bold;\n"
"    margin-top: 10;\n"
"    margin-bottom: 10}\n"
"\n"
"h4 {font-size: small;\n"
"    font-weight: bold;\n"
"    margin-top: 10;\n"
"    margin-bottom: 10}\n"
"\n"
"h5 {font-size: x-small;\n"
"    font-weight: bold;\n"
"    margin-top: 10;\n"
"    margin-bottom: 10}\n"
"\n"
"h6 {font-size: xx-small;\n"
"    font-weight: bold;\n"
"    margin-top: 10;\n"
"    margin-bottom: 10}\n"
"\n"
"li p {margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"td p {margin-top: 0}\n"
"\n"
"menu li p {margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"menu li {margin-left: 0;\n"
"    margin-right: 0;\n"
"    margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"menu {margin-left-ltr: 40;\n"
"    margin-right-rtl: 40;\n"
"    margin-top: 10;\n"
"    margin-bottom: 10}\n"
"\n"
"dir li p {margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"dir li {margin-left: 0;\n"
"    margin-right: 0;\n"
"    margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"dir {margin-left-ltr: 40;\n"
"    margin-right-rtl: 40;\n"
"    margin-top: 10;\n"
"    margin-bottom: 10}\n"
"\n"
"dd {margin-left-ltr: 40;\n"
"    margin-right-rtl: 40;\n"
"    margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"dd p {margin-left: 0;\n"
"    margin-rigth: 0;\n"
"    margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"dt {margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"dl {margin-left: 0;\n"
"    margin-top: 10;\n"
"    margin-bottom: 10}\n"
"\n"
"ol li {margin-left: 0;\n"
"    margin-right: 0;\n"
"    margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"ol {\n"
"    margin-top: 10;\n"
"    margin-bottom: 10;\n"
"    margin-left-ltr: 50;\n"
"    margin-right-rtl: 50;\n"
"    list-style-type: decimal\n"
"}\n"
"\n"
"ol li p {margin-top: 0;\n"
"    margin-bottom:0}\n"
"\n"
"ul li {margin-left: 0;\n"
"    margin-right: 0;\n"
"    margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"ul {margin-top: 10;\n"
"    margin-bottom: 10;\n"
"    margin-left-ltr: 50;\n"
"    margin-right-rtl: 50;\n"
"    list-style-type: disc;\n"
"    -bullet-gap: 10}\n"
"\n"
"ul li ul li {margin-left: 0;\n"
"    margin-right: 0;\n"
"    margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"ul li ul {list-style-type: circle;\n"
"    margin-left-ltr: 25;\n"
"    margin-right-rtl: 25;}\n"
"\n"
"ul li ul li ul li {margin-left: 0;\n"
"    margin-right: 0;\n"
"    margin-top: 0;\n"
"    margin-bottom: 0}\n"
"\n"
"ul li ul li ul {list-style-type: square;\n"
"    margin-left-ltr: 25;\n"
"    margin-right-rtl: 25}\n"
"\n"
"ul li menu {list-style-type: circle;\n"
"    margin-left-ltr: 25;\n"
"    margin-right-rtl: 25;}\n"
"\n"
"ul li p {margin-top: 0;\n"
"    margin-bottom:0}\n"
"\n"
"a {color: blue;\n"
"   text-decoration: underline}\n"
"\n"
"big {font-size: x-large}\n"
"\n"
"small {font-size: x-small}\n"
"\n"
"samp {font-size: small;\n"
"      font-family: Monospaced}\n"
"\n"
"cite {font-style: italic}\n"
"\n"
"code {font-size: small;\n"
"      font-family: Monospaced}\n"
"\n"
"dfn {font-style: italic}\n"
"\n"
"em {font-style: italic}\n"
"\n"
"i  {font-style: italic}\n"
"\n"
"b  {font-weight: bold}\n"
"\n"
"kbd {font-size: small;\n"
"     font-family: Monospaced}\n"
"\n"
"s {text-decoration: line-through}\n"
"\n"
"strike {text-decoration: line-through}\n"
"\n"
"strong {font-weight: bold}\n"
"\n"
"sub {vertical-align: sub}\n"
"\n"
"sup {vertical-align: sup}\n"
"\n"
"tt {font-family: Monospaced}\n"
"\n"
"u {text-decoration: underline}\n"
"\n"
"var {font-weight: bold;\n"
"     font-style: italic}\n"
"\n"
"table {\n"
"        border-style: outset;\n"
"        border-width: 0;\n"
"}\n"
"\n"
"tr {\n"
"	text-align: left\n"
"}\n"
"\n"
"td {\n"
"        border-width: 0;\n"
"	border-style: inset;\n"
"	padding-left: 3;\n"
"	padding-right: 3;\n"
"	padding-top: 3;\n"
"	padding-bottom: 3\n"
"}\n"
"\n"
"th {\n"
"	text-align: center;\n"
"	font-weight: bold;\n"
"        border-width: 0;\n"
"	border-style: inset;\n"
"	padding-left: 3;\n"
"	padding-right: 3;\n"
"	padding-top: 3;\n"
"	padding-bottom: 3\n"
"}\n"
"\n"
"address {\n"
"	color: blue;\n"
"	font-style: italic\n"
"}\n"
"\n"
"blockquote {\n"
"	margin-top: 5;\n"
"	margin-bottom: 5;\n"
"	margin-left: 35;\n"
"	margin-right: 35\n"
"}\n"
"\n"
"center {text-align: center}\n"
"\n"
"pre {margin-top: 5;\n"
"     margin-bottom: 5;\n"
"     font-family: Monospaced}\n"
"\n"
"pre p {margin-top: 0}\n"
"\n"
"caption {\n"
"    caption-side: top;\n"
"    text-align: center\n"
"}\n"
"\n"
"nobr { white-space: nowrap }\n"
"\n";

int8_t* default$css$resource::get(int32_t& length) {
    length = sizeof(default$css$resource$data) - 1;
    return (int8_t*)default$css$resource$data;
}

            } // html
        } // text
    } // swing
} // javax
