#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel.h>
#include <com/sun/java/swing/plaf/motif/MotifBorders$BevelBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifBorders$ButtonBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifBorders$FocusBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifBorders$MenuBarBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifBorders$MotifPopupMenuBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifBorders$ToggleButtonBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$1.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$10.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$11.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$12.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$2.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$3.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$4.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$5.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$6.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$7.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$8.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$9.h>
#include <java/awt/Color.h>
#include <java/awt/Font.h>
#include <java/awt/event/KeyEvent.h>
#include <javax/swing/JTextField.h>
#include <javax/swing/UIDefaults$LazyInputMap.h>
#include <javax/swing/UIDefaults.h>
#include <javax/swing/border/Border.h>
#include <javax/swing/plaf/BorderUIResource$CompoundBorderUIResource.h>
#include <javax/swing/plaf/BorderUIResource$EmptyBorderUIResource.h>
#include <javax/swing/plaf/BorderUIResource$LineBorderUIResource.h>
#include <javax/swing/plaf/ColorUIResource.h>
#include <javax/swing/plaf/FontUIResource.h>
#include <javax/swing/plaf/InsetsUIResource.h>
#include <javax/swing/plaf/basic/BasicBorders$MarginBorder.h>
#include <javax/swing/plaf/basic/BasicLookAndFeel.h>
#include <javax/swing/text/DefaultEditorKit.h>
#include <sun/swing/SwingAccessor$UIDefaultsAccessor.h>
#include <sun/swing/SwingAccessor.h>
#include <sun/swing/SwingUtilities2.h>
#include <jcpp.h>

#undef DIALOG
#undef FALSE
#undef META_MASK
#undef MONOSPACED
#undef PLAIN
#undef SANS_SERIF
#undef SERIF
#undef TRUE

using $MotifBorders$BevelBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$BevelBorder;
using $MotifBorders$ButtonBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$ButtonBorder;
using $MotifBorders$FocusBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$FocusBorder;
using $MotifBorders$MenuBarBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$MenuBarBorder;
using $MotifBorders$MotifPopupMenuBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$MotifPopupMenuBorder;
using $MotifBorders$ToggleButtonBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$ToggleButtonBorder;
using $MotifLookAndFeel$1 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$1;
using $MotifLookAndFeel$10 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$10;
using $MotifLookAndFeel$11 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$11;
using $MotifLookAndFeel$12 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$12;
using $MotifLookAndFeel$2 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$2;
using $MotifLookAndFeel$3 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$3;
using $MotifLookAndFeel$4 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$4;
using $MotifLookAndFeel$5 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$5;
using $MotifLookAndFeel$6 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$6;
using $MotifLookAndFeel$7 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$7;
using $MotifLookAndFeel$8 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$8;
using $MotifLookAndFeel$9 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$9;
using $Color = ::java::awt::Color;
using $Font = ::java::awt::Font;
using $KeyEvent = ::java::awt::event::KeyEvent;
using $Boolean = ::java::lang::Boolean;
using $ClassInfo = ::java::lang::ClassInfo;
using $CompoundAttribute = ::java::lang::CompoundAttribute;
using $InnerClassInfo = ::java::lang::InnerClassInfo;
using $Integer = ::java::lang::Integer;
using $MethodInfo = ::java::lang::MethodInfo;
using $NamedAttribute = ::java::lang::NamedAttribute;
using $JTextField = ::javax::swing::JTextField;
using $UIDefaults = ::javax::swing::UIDefaults;
using $UIDefaults$LazyInputMap = ::javax::swing::UIDefaults$LazyInputMap;
using $Border = ::javax::swing::border::Border;
using $BorderUIResource$CompoundBorderUIResource = ::javax::swing::plaf::BorderUIResource$CompoundBorderUIResource;
using $BorderUIResource$EmptyBorderUIResource = ::javax::swing::plaf::BorderUIResource$EmptyBorderUIResource;
using $BorderUIResource$LineBorderUIResource = ::javax::swing::plaf::BorderUIResource$LineBorderUIResource;
using $ColorUIResource = ::javax::swing::plaf::ColorUIResource;
using $FontUIResource = ::javax::swing::plaf::FontUIResource;
using $InsetsUIResource = ::javax::swing::plaf::InsetsUIResource;
using $BasicBorders$MarginBorder = ::javax::swing::plaf::basic::BasicBorders$MarginBorder;
using $BasicLookAndFeel = ::javax::swing::plaf::basic::BasicLookAndFeel;
using $DefaultEditorKit = ::javax::swing::text::DefaultEditorKit;
using $SwingAccessor = ::sun::swing::SwingAccessor;
using $SwingUtilities2 = ::sun::swing::SwingUtilities2;

namespace com {
	namespace sun {
		namespace java {
			namespace swing {
				namespace plaf {
					namespace motif {

void MotifLookAndFeel::init$() {
	$BasicLookAndFeel::init$();
}

$String* MotifLookAndFeel::getName() {
	return "CDE/Motif"_s;
}

$String* MotifLookAndFeel::getID() {
	return "Motif"_s;
}

$String* MotifLookAndFeel::getDescription() {
	return "The CDE/Motif Look and Feel"_s;
}

bool MotifLookAndFeel::isNativeLookAndFeel() {
	return false;
}

bool MotifLookAndFeel::isSupportedLookAndFeel() {
	return true;
}

void MotifLookAndFeel::initSystemColorDefaults($UIDefaults* table) {
	$var($StringArray, defaultSystemColors, $new($StringArray, {
		"desktop"_s,
		"#005C5C"_s,
		"activeCaption"_s,
		"#000080"_s,
		"activeCaptionText"_s,
		"#FFFFFF"_s,
		"activeCaptionBorder"_s,
		"#B24D7A"_s,
		"inactiveCaption"_s,
		"#AEB2C3"_s,
		"inactiveCaptionText"_s,
		"#000000"_s,
		"inactiveCaptionBorder"_s,
		"#AEB2C3"_s,
		"window"_s,
		"#AEB2C3"_s,
		"windowBorder"_s,
		"#AEB2C3"_s,
		"windowText"_s,
		"#000000"_s,
		"menu"_s,
		"#AEB2C3"_s,
		"menuText"_s,
		"#000000"_s,
		"text"_s,
		"#FFF7E9"_s,
		"textText"_s,
		"#000000"_s,
		"textHighlight"_s,
		"#000000"_s,
		"textHighlightText"_s,
		"#FFF7E9"_s,
		"textInactiveText"_s,
		"#808080"_s,
		"control"_s,
		"#AEB2C3"_s,
		"controlText"_s,
		"#000000"_s,
		"controlHighlight"_s,
		"#DCDEE5"_s,
		"controlLtHighlight"_s,
		"#DCDEE5"_s,
		"controlShadow"_s,
		"#63656F"_s,
		"controlLightShadow"_s,
		"#9397A5"_s,
		"controlDkShadow"_s,
		"#000000"_s,
		"scrollbar"_s,
		"#AEB2C3"_s,
		"info"_s,
		"#FFF7E9"_s,
		"infoText"_s,
		"#000000"_s
	}));
	loadSystemColors(table, defaultSystemColors, false);
}

void MotifLookAndFeel::initClassDefaults($UIDefaults* table) {
	$useLocalObjectStack();
	$BasicLookAndFeel::initClassDefaults(table);
	$var($String, motifPackageName, "com.sun.java.swing.plaf.motif."_s);
	$var($ObjectArray, uiDefaults, $new($ObjectArray, {
		"ButtonUI"_s,
		$$str({motifPackageName, "MotifButtonUI"_s}),
		"CheckBoxUI"_s,
		$$str({motifPackageName, "MotifCheckBoxUI"_s}),
		"DirectoryPaneUI"_s,
		$$str({motifPackageName, "MotifDirectoryPaneUI"_s}),
		"FileChooserUI"_s,
		$$str({motifPackageName, "MotifFileChooserUI"_s}),
		"LabelUI"_s,
		$$str({motifPackageName, "MotifLabelUI"_s}),
		"MenuBarUI"_s,
		$$str({motifPackageName, "MotifMenuBarUI"_s}),
		"MenuUI"_s,
		$$str({motifPackageName, "MotifMenuUI"_s}),
		"MenuItemUI"_s,
		$$str({motifPackageName, "MotifMenuItemUI"_s}),
		"CheckBoxMenuItemUI"_s,
		$$str({motifPackageName, "MotifCheckBoxMenuItemUI"_s}),
		"RadioButtonMenuItemUI"_s,
		$$str({motifPackageName, "MotifRadioButtonMenuItemUI"_s}),
		"RadioButtonUI"_s,
		$$str({motifPackageName, "MotifRadioButtonUI"_s}),
		"ToggleButtonUI"_s,
		$$str({motifPackageName, "MotifToggleButtonUI"_s}),
		"PopupMenuUI"_s,
		$$str({motifPackageName, "MotifPopupMenuUI"_s}),
		"ProgressBarUI"_s,
		$$str({motifPackageName, "MotifProgressBarUI"_s}),
		"ScrollBarUI"_s,
		$$str({motifPackageName, "MotifScrollBarUI"_s}),
		"ScrollPaneUI"_s,
		$$str({motifPackageName, "MotifScrollPaneUI"_s}),
		"SliderUI"_s,
		$$str({motifPackageName, "MotifSliderUI"_s}),
		"SplitPaneUI"_s,
		$$str({motifPackageName, "MotifSplitPaneUI"_s}),
		"TabbedPaneUI"_s,
		$$str({motifPackageName, "MotifTabbedPaneUI"_s}),
		"TextAreaUI"_s,
		$$str({motifPackageName, "MotifTextAreaUI"_s}),
		"TextFieldUI"_s,
		$$str({motifPackageName, "MotifTextFieldUI"_s}),
		"PasswordFieldUI"_s,
		$$str({motifPackageName, "MotifPasswordFieldUI"_s}),
		"TextPaneUI"_s,
		$$str({motifPackageName, "MotifTextPaneUI"_s}),
		"EditorPaneUI"_s,
		$$str({motifPackageName, "MotifEditorPaneUI"_s}),
		"TreeUI"_s,
		$$str({motifPackageName, "MotifTreeUI"_s}),
		"InternalFrameUI"_s,
		$$str({motifPackageName, "MotifInternalFrameUI"_s}),
		"DesktopPaneUI"_s,
		$$str({motifPackageName, "MotifDesktopPaneUI"_s}),
		"SeparatorUI"_s,
		$$str({motifPackageName, "MotifSeparatorUI"_s}),
		"PopupMenuSeparatorUI"_s,
		$$str({motifPackageName, "MotifPopupMenuSeparatorUI"_s}),
		"OptionPaneUI"_s,
		$$str({motifPackageName, "MotifOptionPaneUI"_s}),
		"ComboBoxUI"_s,
		$$str({motifPackageName, "MotifComboBoxUI"_s}),
		"DesktopIconUI"_s,
		$$str({motifPackageName, "MotifDesktopIconUI"_s})
	}));
	$nc(table)->putDefaults(uiDefaults);
}

void MotifLookAndFeel::initResourceBundle($UIDefaults* table) {
	$$nc($SwingAccessor::getUIDefaultsAccessor())->addInternalBundle(table, "com.sun.java.swing.plaf.motif.resources.motif"_s);
}

void MotifLookAndFeel::initComponentDefaults($UIDefaults* table) {
	$useLocalObjectStack();
	$BasicLookAndFeel::initComponentDefaults(table);
	initResourceBundle(table);
	$init($Font);
	$var($FontUIResource, dialogPlain12, $new($FontUIResource, $Font::DIALOG, $Font::PLAIN, 12));
	$var($FontUIResource, serifPlain12, $new($FontUIResource, $Font::SERIF, $Font::PLAIN, 12));
	$var($FontUIResource, sansSerifPlain12, $new($FontUIResource, $Font::SANS_SERIF, $Font::PLAIN, 12));
	$var($FontUIResource, monospacedPlain12, $new($FontUIResource, $Font::MONOSPACED, $Font::PLAIN, 12));
	$init($Color);
	$var($ColorUIResource, red, $new($ColorUIResource, $Color::red));
	$var($ColorUIResource, black, $new($ColorUIResource, $Color::black));
	$var($ColorUIResource, white, $new($ColorUIResource, $Color::white));
	$var($ColorUIResource, lightGray, $new($ColorUIResource, $Color::lightGray));
	$var($ColorUIResource, controlDarker, $new($ColorUIResource, 147, 151, 165));
	$var($ColorUIResource, scrollBarTrack, controlDarker);
	$var($ColorUIResource, menuItemPressedBackground, $new($ColorUIResource, 165, 165, 165));
	$var($ColorUIResource, menuItemPressedForeground, $new($ColorUIResource, 0, 0, 0));
	$var($Color, var$0, $nc(table)->getColor("controlShadow"_s));
	$var($Border, loweredBevelBorder, $new($MotifBorders$BevelBorder, false, var$0, $(table->getColor("controlLtHighlight"_s))));
	$var($Color, var$1, table->getColor("controlShadow"_s));
	$var($Border, raisedBevelBorder, $new($MotifBorders$BevelBorder, true, var$1, $(table->getColor("controlLtHighlight"_s))));
	$var($Border, marginBorder, $new($BasicBorders$MarginBorder));
	$var($Color, var$2, table->getColor("control"_s));
	$var($Border, focusBorder, $new($MotifBorders$FocusBorder, var$2, $(table->getColor("activeCaptionBorder"_s))));
	$var($Border, focusBevelBorder, $new($BorderUIResource$CompoundBorderUIResource, focusBorder, loweredBevelBorder));
	$var($Border, comboBoxBorder, $new($BorderUIResource$CompoundBorderUIResource, focusBorder, raisedBevelBorder));
	$var($Color, var$3, table->getColor("Button.shadow"_s));
	$var($Color, var$4, table->getColor("Button.highlight"_s));
	$var($Color, var$5, table->getColor("Button.darkShadow"_s));
	$var($Border, buttonBorder, $new($BorderUIResource$CompoundBorderUIResource, $$new($MotifBorders$ButtonBorder, var$3, var$4, var$5, $(table->getColor("activeCaptionBorder"_s))), marginBorder));
	$var($Color, var$6, table->getColor("ToggleButton.shadow"_s));
	$var($Color, var$7, table->getColor("ToggleButton.highlight"_s));
	$var($Color, var$8, table->getColor("ToggleButton.darkShadow"_s));
	$var($Border, toggleButtonBorder, $new($BorderUIResource$CompoundBorderUIResource, $$new($MotifBorders$ToggleButtonBorder, var$6, var$7, var$8, $(table->getColor("activeCaptionBorder"_s))), marginBorder));
	$var($Border, textFieldBorder, $new($BorderUIResource$CompoundBorderUIResource, focusBevelBorder, marginBorder));
	$var($Font, var$9, table->getFont("PopupMenu.font"_s));
	$var($Color, var$10, table->getColor("PopupMenu.background"_s));
	$var($Color, var$11, table->getColor("PopupMenu.foreground"_s));
	$var($Color, var$12, table->getColor("controlShadow"_s));
	$var($Border, popupMenuBorder, $new($BorderUIResource$CompoundBorderUIResource, raisedBevelBorder, $$new($MotifBorders$MotifPopupMenuBorder, var$9, var$10, var$11, var$12, $(table->getColor("controlLtHighlight"_s)))));
	$var($Object, menuItemCheckIcon, $new($MotifLookAndFeel$1, this));
	$var($Object, menuItemArrowIcon, $new($MotifLookAndFeel$2, this));
	$var($Object, menuArrowIcon, $new($MotifLookAndFeel$3, this));
	$var($Object, checkBoxIcon, $new($MotifLookAndFeel$4, this));
	$var($Object, radioButtonIcon, $new($MotifLookAndFeel$5, this));
	$var($Object, unselectedTabBackground, $new($MotifLookAndFeel$6, this));
	$var($Object, unselectedTabForeground, $new($MotifLookAndFeel$7, this));
	$var($Object, unselectedTabShadow, $new($MotifLookAndFeel$8, this));
	$var($Object, unselectedTabHighlight, $new($MotifLookAndFeel$9, this));
	$init($DefaultEditorKit);
	$init($JTextField);
	$var($Object, fieldInputMap, $new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
		"COPY"_s,
		$DefaultEditorKit::copyAction,
		"PASTE"_s,
		$DefaultEditorKit::pasteAction,
		"CUT"_s,
		$DefaultEditorKit::cutAction,
		"control INSERT"_s,
		$DefaultEditorKit::copyAction,
		"shift INSERT"_s,
		$DefaultEditorKit::pasteAction,
		"shift DELETE"_s,
		$DefaultEditorKit::cutAction,
		"control F"_s,
		$DefaultEditorKit::forwardAction,
		"control B"_s,
		$DefaultEditorKit::backwardAction,
		"control D"_s,
		$DefaultEditorKit::deleteNextCharAction,
		"BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"shift BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"ctrl H"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"DELETE"_s,
		$DefaultEditorKit::deleteNextCharAction,
		"ctrl DELETE"_s,
		$DefaultEditorKit::deleteNextWordAction,
		"ctrl BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevWordAction,
		"RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"KP_RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"KP_LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"shift LEFT"_s,
		$DefaultEditorKit::selectionBackwardAction,
		"shift RIGHT"_s,
		$DefaultEditorKit::selectionForwardAction,
		"control LEFT"_s,
		$DefaultEditorKit::previousWordAction,
		"control RIGHT"_s,
		$DefaultEditorKit::nextWordAction,
		"control shift LEFT"_s,
		$DefaultEditorKit::selectionPreviousWordAction,
		"control shift RIGHT"_s,
		$DefaultEditorKit::selectionNextWordAction,
		"control SLASH"_s,
		$DefaultEditorKit::selectAllAction,
		"HOME"_s,
		$DefaultEditorKit::beginLineAction,
		"END"_s,
		$DefaultEditorKit::endLineAction,
		"shift HOME"_s,
		$DefaultEditorKit::selectionBeginLineAction,
		"shift END"_s,
		$DefaultEditorKit::selectionEndLineAction,
		"control BACK_SLASH"_s,
		"unselect"_s,
		"ENTER"_s,
		$JTextField::notifyAction,
		"control shift O"_s,
		"toggle-componentOrientation"_s
	})));
	$var($Object, passwordInputMap, $new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
		"COPY"_s,
		$DefaultEditorKit::copyAction,
		"PASTE"_s,
		$DefaultEditorKit::pasteAction,
		"CUT"_s,
		$DefaultEditorKit::cutAction,
		"control INSERT"_s,
		$DefaultEditorKit::copyAction,
		"shift INSERT"_s,
		$DefaultEditorKit::pasteAction,
		"shift DELETE"_s,
		$DefaultEditorKit::cutAction,
		"control F"_s,
		$DefaultEditorKit::forwardAction,
		"control B"_s,
		$DefaultEditorKit::backwardAction,
		"control D"_s,
		$DefaultEditorKit::deleteNextCharAction,
		"BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"shift BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"ctrl H"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"DELETE"_s,
		$DefaultEditorKit::deleteNextCharAction,
		"RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"KP_RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"KP_LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"shift LEFT"_s,
		$DefaultEditorKit::selectionBackwardAction,
		"shift RIGHT"_s,
		$DefaultEditorKit::selectionForwardAction,
		"control LEFT"_s,
		$DefaultEditorKit::beginLineAction,
		"control RIGHT"_s,
		$DefaultEditorKit::endLineAction,
		"control shift LEFT"_s,
		$DefaultEditorKit::selectionBeginLineAction,
		"control shift RIGHT"_s,
		$DefaultEditorKit::selectionEndLineAction,
		"control SLASH"_s,
		$DefaultEditorKit::selectAllAction,
		"HOME"_s,
		$DefaultEditorKit::beginLineAction,
		"END"_s,
		$DefaultEditorKit::endLineAction,
		"shift HOME"_s,
		$DefaultEditorKit::selectionBeginLineAction,
		"shift END"_s,
		$DefaultEditorKit::selectionEndLineAction,
		"control BACK_SLASH"_s,
		"unselect"_s,
		"ENTER"_s,
		$JTextField::notifyAction,
		"control shift O"_s,
		"toggle-componentOrientation"_s
	})));
	$var($Object, multilineInputMap, $new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
		"COPY"_s,
		$DefaultEditorKit::copyAction,
		"PASTE"_s,
		$DefaultEditorKit::pasteAction,
		"CUT"_s,
		$DefaultEditorKit::cutAction,
		"control INSERT"_s,
		$DefaultEditorKit::copyAction,
		"shift INSERT"_s,
		$DefaultEditorKit::pasteAction,
		"shift DELETE"_s,
		$DefaultEditorKit::cutAction,
		"control F"_s,
		$DefaultEditorKit::forwardAction,
		"control B"_s,
		$DefaultEditorKit::backwardAction,
		"control D"_s,
		$DefaultEditorKit::deleteNextCharAction,
		"BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"shift BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"ctrl H"_s,
		$DefaultEditorKit::deletePrevCharAction,
		"DELETE"_s,
		$DefaultEditorKit::deleteNextCharAction,
		"ctrl DELETE"_s,
		$DefaultEditorKit::deleteNextWordAction,
		"ctrl BACK_SPACE"_s,
		$DefaultEditorKit::deletePrevWordAction,
		"RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"KP_RIGHT"_s,
		$DefaultEditorKit::forwardAction,
		"KP_LEFT"_s,
		$DefaultEditorKit::backwardAction,
		"shift LEFT"_s,
		$DefaultEditorKit::selectionBackwardAction,
		"shift RIGHT"_s,
		$DefaultEditorKit::selectionForwardAction,
		"control LEFT"_s,
		$DefaultEditorKit::previousWordAction,
		"control RIGHT"_s,
		$DefaultEditorKit::nextWordAction,
		"control shift LEFT"_s,
		$DefaultEditorKit::selectionPreviousWordAction,
		"control shift RIGHT"_s,
		$DefaultEditorKit::selectionNextWordAction,
		"control SLASH"_s,
		$DefaultEditorKit::selectAllAction,
		"HOME"_s,
		$DefaultEditorKit::beginLineAction,
		"END"_s,
		$DefaultEditorKit::endLineAction,
		"shift HOME"_s,
		$DefaultEditorKit::selectionBeginLineAction,
		"shift END"_s,
		$DefaultEditorKit::selectionEndLineAction,
		"control N"_s,
		$DefaultEditorKit::downAction,
		"control P"_s,
		$DefaultEditorKit::upAction,
		"UP"_s,
		$DefaultEditorKit::upAction,
		"DOWN"_s,
		$DefaultEditorKit::downAction,
		"PAGE_UP"_s,
		$DefaultEditorKit::pageUpAction,
		"PAGE_DOWN"_s,
		$DefaultEditorKit::pageDownAction,
		"shift PAGE_UP"_s,
		"selection-page-up"_s,
		"shift PAGE_DOWN"_s,
		"selection-page-down"_s,
		"ctrl shift PAGE_UP"_s,
		"selection-page-left"_s,
		"ctrl shift PAGE_DOWN"_s,
		"selection-page-right"_s,
		"shift UP"_s,
		$DefaultEditorKit::selectionUpAction,
		"shift DOWN"_s,
		$DefaultEditorKit::selectionDownAction,
		"ENTER"_s,
		$DefaultEditorKit::insertBreakAction,
		"TAB"_s,
		$DefaultEditorKit::insertTabAction,
		"control BACK_SLASH"_s,
		"unselect"_s,
		"control HOME"_s,
		$DefaultEditorKit::beginAction,
		"control END"_s,
		$DefaultEditorKit::endAction,
		"control shift HOME"_s,
		$DefaultEditorKit::selectionBeginAction,
		"control shift END"_s,
		$DefaultEditorKit::selectionEndAction,
		"control T"_s,
		"next-link-action"_s,
		"control shift T"_s,
		"previous-link-action"_s,
		"control SPACE"_s,
		"activate-link-action"_s,
		"control shift O"_s,
		"toggle-componentOrientation"_s
	})));
	$var($Object, treeOpenIcon, $SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/TreeOpen.gif"_s));
	$var($Object, treeClosedIcon, $SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/TreeClosed.gif"_s));
	$var($Object, treeLeafIcon, $new($MotifLookAndFeel$10, this));
	$var($Object, treeExpandedIcon, $new($MotifLookAndFeel$11, this));
	$var($Object, treeCollapsedIcon, $new($MotifLookAndFeel$12, this));
	$var($Color, var$13, table->getColor("MenuBar.shadow"_s));
	$var($Color, var$14, table->getColor("MenuBar.highlight"_s));
	$var($Color, var$15, table->getColor("MenuBar.darkShadow"_s));
	$var($Border, menuBarBorder, $new($MotifBorders$MenuBarBorder, var$13, var$14, var$15, $(table->getColor("activeCaptionBorder"_s))));
	$var($Border, menuMarginBorder, $new($BorderUIResource$CompoundBorderUIResource, loweredBevelBorder, marginBorder));
	$var($Border, focusCellHighlightBorder, $new($BorderUIResource$LineBorderUIResource, $(table->getColor("activeCaptionBorder"_s))));
	$var($Object, sliderFocusInsets, $new($InsetsUIResource, 0, 0, 0, 0));
	$var($Object, tabbedPaneTabInsets, $new($InsetsUIResource, 3, 4, 3, 4));
	$var($Object, tabbedPaneTabPadInsets, $new($InsetsUIResource, 3, 0, 1, 0));
	$var($Object, tabbedPaneTabAreaInsets, $new($InsetsUIResource, 4, 2, 0, 8));
	$var($Object, tabbedPaneContentBorderInsets, $new($InsetsUIResource, 2, 2, 2, 2));
	$var($Object, optionPaneBorder, $new($BorderUIResource$EmptyBorderUIResource, 10, 0, 0, 0));
	$var($Object, optionPaneButtonAreaBorder, $new($BorderUIResource$EmptyBorderUIResource, 10, 10, 10, 10));
	$var($Object, optionPaneMessageAreaBorder, $new($BorderUIResource$EmptyBorderUIResource, 10, 10, 12, 10));
	int32_t metaMask = $KeyEvent::META_MASK;
	$var($ObjectArray, defaults, $new($ObjectArray, {
		"Desktop.background"_s,
		$(table->get("desktop"_s)),
		"Desktop.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ctrl F5"_s,
			"restore"_s,
			"ctrl F4"_s,
			"close"_s,
			"ctrl F7"_s,
			"move"_s,
			"ctrl F8"_s,
			"resize"_s,
			"RIGHT"_s,
			"right"_s,
			"KP_RIGHT"_s,
			"right"_s,
			"shift RIGHT"_s,
			"shrinkRight"_s,
			"shift KP_RIGHT"_s,
			"shrinkRight"_s,
			"LEFT"_s,
			"left"_s,
			"KP_LEFT"_s,
			"left"_s,
			"shift LEFT"_s,
			"shrinkLeft"_s,
			"shift KP_LEFT"_s,
			"shrinkLeft"_s,
			"UP"_s,
			"up"_s,
			"KP_UP"_s,
			"up"_s,
			"shift UP"_s,
			"shrinkUp"_s,
			"shift KP_UP"_s,
			"shrinkUp"_s,
			"DOWN"_s,
			"down"_s,
			"KP_DOWN"_s,
			"down"_s,
			"shift DOWN"_s,
			"shrinkDown"_s,
			"shift KP_DOWN"_s,
			"shrinkDown"_s,
			"ESCAPE"_s,
			"escape"_s,
			"ctrl F9"_s,
			"minimize"_s,
			"ctrl F10"_s,
			"maximize"_s,
			"ctrl F6"_s,
			"selectNextFrame"_s,
			"ctrl TAB"_s,
			"selectNextFrame"_s,
			"ctrl alt F6"_s,
			"selectNextFrame"_s,
			"shift ctrl alt F6"_s,
			"selectPreviousFrame"_s,
			"ctrl F12"_s,
			"navigateNext"_s,
			"shift ctrl F12"_s,
			"navigatePrevious"_s
		})),
		"Panel.background"_s,
		$(table->get("control"_s)),
		"Panel.foreground"_s,
		$(table->get("textText"_s)),
		"Panel.font"_s,
		dialogPlain12,
		"ProgressBar.font"_s,
		dialogPlain12,
		"ProgressBar.foreground"_s,
		controlDarker,
		"ProgressBar.background"_s,
		$(table->get("control"_s)),
		"ProgressBar.selectionForeground"_s,
		$(table->get("control"_s)),
		"ProgressBar.selectionBackground"_s,
		$(table->get("controlText"_s)),
		"ProgressBar.border"_s,
		loweredBevelBorder,
		"ProgressBar.cellLength"_s,
		$($Integer::valueOf(6)),
		"ProgressBar.cellSpacing"_s,
		$($Integer::valueOf(0)),
		"Button.margin"_s,
		$$new($InsetsUIResource, 2, 4, 2, 4),
		"Button.border"_s,
		buttonBorder,
		"Button.background"_s,
		$(table->get("control"_s)),
		"Button.foreground"_s,
		$(table->get("controlText"_s)),
		"Button.select"_s,
		$(table->get("controlLightShadow"_s)),
		"Button.font"_s,
		dialogPlain12,
		"Button.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"SPACE"_s,
			"pressed"_s,
			"released SPACE"_s,
			"released"_s
		})),
		"CheckBox.textIconGap"_s,
		$($Integer::valueOf(8)),
		"CheckBox.margin"_s,
		$$new($InsetsUIResource, 4, 2, 4, 2),
		"CheckBox.icon"_s,
		checkBoxIcon,
		"CheckBox.focus"_s,
		$(table->get("activeCaptionBorder"_s)),
		"CheckBox.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"SPACE"_s,
			"pressed"_s,
			"released SPACE"_s,
			"released"_s
		})),
		"RadioButton.margin"_s,
		$$new($InsetsUIResource, 4, 2, 4, 2),
		"RadioButton.textIconGap"_s,
		$($Integer::valueOf(8)),
		"RadioButton.background"_s,
		$(table->get("control"_s)),
		"RadioButton.foreground"_s,
		$(table->get("controlText"_s)),
		"RadioButton.icon"_s,
		radioButtonIcon,
		"RadioButton.focus"_s,
		$(table->get("activeCaptionBorder"_s)),
		"RadioButton.icon"_s,
		radioButtonIcon,
		"RadioButton.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"SPACE"_s,
			"pressed"_s,
			"released SPACE"_s,
			"released"_s
		})),
		"ToggleButton.border"_s,
		toggleButtonBorder,
		"ToggleButton.background"_s,
		$(table->get("control"_s)),
		"ToggleButton.foreground"_s,
		$(table->get("controlText"_s)),
		"ToggleButton.focus"_s,
		$(table->get("controlText"_s)),
		"ToggleButton.select"_s,
		$(table->get("controlLightShadow"_s)),
		"ToggleButton.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"SPACE"_s,
			"pressed"_s,
			"released SPACE"_s,
			"released"_s
		})),
		"Menu.border"_s,
		menuMarginBorder,
		"Menu.font"_s,
		dialogPlain12,
		"Menu.acceleratorFont"_s,
		dialogPlain12,
		"Menu.acceleratorSelectionForeground"_s,
		menuItemPressedForeground,
		"Menu.foreground"_s,
		$(table->get("menuText"_s)),
		"Menu.background"_s,
		$(table->get("menu"_s)),
		"Menu.selectionForeground"_s,
		menuItemPressedForeground,
		"Menu.selectionBackground"_s,
		menuItemPressedBackground,
		"Menu.checkIcon"_s,
		menuItemCheckIcon,
		"Menu.arrowIcon"_s,
		menuArrowIcon,
		"Menu.menuPopupOffsetX"_s,
		$($Integer::valueOf(0)),
		"Menu.menuPopupOffsetY"_s,
		$($Integer::valueOf(0)),
		"Menu.submenuPopupOffsetX"_s,
		$($Integer::valueOf(-2)),
		"Menu.submenuPopupOffsetY"_s,
		$($Integer::valueOf(3)),
		"Menu.shortcutKeys"_s,
		$$new($ints, {
			$SwingUtilities2::getSystemMnemonicKeyMask(),
			metaMask,
			$SwingUtilities2::setAltGraphMask($SwingUtilities2::getSystemMnemonicKeyMask())
		}),
		"Menu.cancelMode"_s,
		"hideMenuTree"_s,
		"MenuBar.border"_s,
		menuBarBorder,
		"MenuBar.background"_s,
		$(table->get("menu"_s)),
		"MenuBar.foreground"_s,
		$(table->get("menuText"_s)),
		"MenuBar.font"_s,
		dialogPlain12,
		"MenuBar.windowBindings"_s,
		$$new($ObjectArray, {
			"F10"_s,
			"takeFocus"_s
		}),
		"MenuItem.border"_s,
		menuMarginBorder,
		"MenuItem.font"_s,
		dialogPlain12,
		"MenuItem.acceleratorFont"_s,
		dialogPlain12,
		"MenuItem.acceleratorSelectionForeground"_s,
		menuItemPressedForeground,
		"MenuItem.foreground"_s,
		$(table->get("menuText"_s)),
		"MenuItem.background"_s,
		$(table->get("menu"_s)),
		"MenuItem.selectionForeground"_s,
		menuItemPressedForeground,
		"MenuItem.selectionBackground"_s,
		menuItemPressedBackground,
		"MenuItem.checkIcon"_s,
		menuItemCheckIcon,
		"MenuItem.arrowIcon"_s,
		menuItemArrowIcon,
		"RadioButtonMenuItem.border"_s,
		menuMarginBorder,
		"RadioButtonMenuItem.font"_s,
		dialogPlain12,
		"RadioButtonMenuItem.acceleratorFont"_s,
		dialogPlain12,
		"RadioButtonMenuItem.acceleratorSelectionForeground"_s,
		menuItemPressedForeground,
		"RadioButtonMenuItem.foreground"_s,
		$(table->get("menuText"_s)),
		"RadioButtonMenuItem.background"_s,
		$(table->get("menu"_s)),
		"RadioButtonMenuItem.selectionForeground"_s,
		menuItemPressedForeground,
		"RadioButtonMenuItem.selectionBackground"_s,
		menuItemPressedBackground,
		"RadioButtonMenuItem.checkIcon"_s,
		radioButtonIcon,
		"RadioButtonMenuItem.arrowIcon"_s,
		menuItemArrowIcon,
		"CheckBoxMenuItem.border"_s,
		menuMarginBorder,
		"CheckBoxMenuItem.font"_s,
		dialogPlain12,
		"CheckBoxMenuItem.acceleratorFont"_s,
		dialogPlain12,
		"CheckBoxMenuItem.acceleratorSelectionForeground"_s,
		menuItemPressedForeground,
		"CheckBoxMenuItem.foreground"_s,
		$(table->get("menuText"_s)),
		"CheckBoxMenuItem.background"_s,
		$(table->get("menu"_s)),
		"CheckBoxMenuItem.selectionForeground"_s,
		menuItemPressedForeground,
		"CheckBoxMenuItem.selectionBackground"_s,
		menuItemPressedBackground,
		"CheckBoxMenuItem.checkIcon"_s,
		checkBoxIcon,
		"CheckBoxMenuItem.arrowIcon"_s,
		menuItemArrowIcon,
		"PopupMenu.background"_s,
		$(table->get("menu"_s)),
		"PopupMenu.border"_s,
		popupMenuBorder,
		"PopupMenu.foreground"_s,
		$(table->get("menuText"_s)),
		"PopupMenu.font"_s,
		dialogPlain12,
		"PopupMenu.consumeEventOnClose"_s,
		$Boolean::FALSE,
		"Label.font"_s,
		dialogPlain12,
		"Label.background"_s,
		$(table->get("control"_s)),
		"Label.foreground"_s,
		$(table->get("controlText"_s)),
		"Separator.shadow"_s,
		$(table->get("controlShadow"_s)),
		"Separator.highlight"_s,
		$(table->get("controlLtHighlight"_s)),
		"Separator.background"_s,
		$(table->get("controlLtHighlight"_s)),
		"Separator.foreground"_s,
		$(table->get("controlShadow"_s)),
		"List.focusCellHighlightBorder"_s,
		focusCellHighlightBorder,
		"List.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"COPY"_s,
			"copy"_s,
			"PASTE"_s,
			"paste"_s,
			"CUT"_s,
			"cut"_s,
			"control INSERT"_s,
			"copy"_s,
			"shift INSERT"_s,
			"paste"_s,
			"shift DELETE"_s,
			"cut"_s,
			"UP"_s,
			"selectPreviousRow"_s,
			"KP_UP"_s,
			"selectPreviousRow"_s,
			"shift UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"shift KP_UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl shift UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl shift KP_UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl UP"_s,
			"selectPreviousRowChangeLead"_s,
			"ctrl KP_UP"_s,
			"selectPreviousRowChangeLead"_s,
			"DOWN"_s,
			"selectNextRow"_s,
			"KP_DOWN"_s,
			"selectNextRow"_s,
			"shift DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"shift KP_DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl shift DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl shift KP_DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl DOWN"_s,
			"selectNextRowChangeLead"_s,
			"ctrl KP_DOWN"_s,
			"selectNextRowChangeLead"_s,
			"LEFT"_s,
			"selectPreviousColumn"_s,
			"KP_LEFT"_s,
			"selectPreviousColumn"_s,
			"shift LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"shift KP_LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl shift LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl shift KP_LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl LEFT"_s,
			"selectPreviousColumnChangeLead"_s,
			"ctrl KP_LEFT"_s,
			"selectPreviousColumnChangeLead"_s,
			"RIGHT"_s,
			"selectNextColumn"_s,
			"KP_RIGHT"_s,
			"selectNextColumn"_s,
			"shift RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"shift KP_RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl shift RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl shift KP_RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl RIGHT"_s,
			"selectNextColumnChangeLead"_s,
			"ctrl KP_RIGHT"_s,
			"selectNextColumnChangeLead"_s,
			"HOME"_s,
			"selectFirstRow"_s,
			"shift HOME"_s,
			"selectFirstRowExtendSelection"_s,
			"ctrl shift HOME"_s,
			"selectFirstRowExtendSelection"_s,
			"ctrl HOME"_s,
			"selectFirstRowChangeLead"_s,
			"END"_s,
			"selectLastRow"_s,
			"shift END"_s,
			"selectLastRowExtendSelection"_s,
			"ctrl shift END"_s,
			"selectLastRowExtendSelection"_s,
			"ctrl END"_s,
			"selectLastRowChangeLead"_s,
			"PAGE_UP"_s,
			"scrollUp"_s,
			"shift PAGE_UP"_s,
			"scrollUpExtendSelection"_s,
			"ctrl shift PAGE_UP"_s,
			"scrollUpExtendSelection"_s,
			"ctrl PAGE_UP"_s,
			"scrollUpChangeLead"_s,
			"PAGE_DOWN"_s,
			"scrollDown"_s,
			"shift PAGE_DOWN"_s,
			"scrollDownExtendSelection"_s,
			"ctrl shift PAGE_DOWN"_s,
			"scrollDownExtendSelection"_s,
			"ctrl PAGE_DOWN"_s,
			"scrollDownChangeLead"_s,
			"ctrl A"_s,
			"selectAll"_s,
			"ctrl SLASH"_s,
			"selectAll"_s,
			"ctrl BACK_SLASH"_s,
			"clearSelection"_s,
			"SPACE"_s,
			"addToSelection"_s,
			"ctrl SPACE"_s,
			"toggleAndAnchor"_s,
			"shift SPACE"_s,
			"extendTo"_s,
			"ctrl shift SPACE"_s,
			"moveSelectionTo"_s
		})),
		"DesktopIcon.icon"_s,
		$($SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/DesktopIcon.gif"_s)),
		"DesktopIcon.border"_s,
		nullptr,
		"DesktopIcon.windowBindings"_s,
		$$new($ObjectArray, {
			"ESCAPE"_s,
			"hideSystemMenu"_s
		}),
		"InternalFrame.activeTitleBackground"_s,
		$(table->get("activeCaptionBorder"_s)),
		"InternalFrame.inactiveTitleBackground"_s,
		$(table->get("inactiveCaptionBorder"_s)),
		"InternalFrame.windowBindings"_s,
		$$new($ObjectArray, {
			"shift ESCAPE"_s,
			"showSystemMenu"_s,
			"ctrl SPACE"_s,
			"showSystemMenu"_s,
			"ESCAPE"_s,
			"hideSystemMenu"_s
		}),
		"ScrollBar.background"_s,
		scrollBarTrack,
		"ScrollBar.foreground"_s,
		$(table->get("control"_s)),
		"ScrollBar.track"_s,
		scrollBarTrack,
		"ScrollBar.trackHighlight"_s,
		$(table->get("controlDkShadow"_s)),
		"ScrollBar.thumb"_s,
		$(table->get("control"_s)),
		"ScrollBar.thumbHighlight"_s,
		$(table->get("controlHighlight"_s)),
		"ScrollBar.thumbDarkShadow"_s,
		$(table->get("controlDkShadow"_s)),
		"ScrollBar.thumbShadow"_s,
		$(table->get("controlShadow"_s)),
		"ScrollBar.border"_s,
		loweredBevelBorder,
		"ScrollBar.allowsAbsolutePositioning"_s,
		$Boolean::TRUE,
		"ScrollBar.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"RIGHT"_s,
			"positiveUnitIncrement"_s,
			"KP_RIGHT"_s,
			"positiveUnitIncrement"_s,
			"DOWN"_s,
			"positiveUnitIncrement"_s,
			"KP_DOWN"_s,
			"positiveUnitIncrement"_s,
			"PAGE_DOWN"_s,
			"positiveBlockIncrement"_s,
			"ctrl PAGE_DOWN"_s,
			"positiveBlockIncrement"_s,
			"LEFT"_s,
			"negativeUnitIncrement"_s,
			"KP_LEFT"_s,
			"negativeUnitIncrement"_s,
			"UP"_s,
			"negativeUnitIncrement"_s,
			"KP_UP"_s,
			"negativeUnitIncrement"_s,
			"PAGE_UP"_s,
			"negativeBlockIncrement"_s,
			"ctrl PAGE_UP"_s,
			"negativeBlockIncrement"_s,
			"HOME"_s,
			"minScroll"_s,
			"END"_s,
			"maxScroll"_s
		})),
		"ScrollPane.font"_s,
		dialogPlain12,
		"ScrollPane.background"_s,
		$(table->get("control"_s)),
		"ScrollPane.foreground"_s,
		$(table->get("controlText"_s)),
		"ScrollPane.border"_s,
		nullptr,
		"ScrollPane.viewportBorder"_s,
		loweredBevelBorder,
		"ScrollPane.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"RIGHT"_s,
			"unitScrollRight"_s,
			"KP_RIGHT"_s,
			"unitScrollRight"_s,
			"DOWN"_s,
			"unitScrollDown"_s,
			"KP_DOWN"_s,
			"unitScrollDown"_s,
			"LEFT"_s,
			"unitScrollLeft"_s,
			"KP_LEFT"_s,
			"unitScrollLeft"_s,
			"UP"_s,
			"unitScrollUp"_s,
			"KP_UP"_s,
			"unitScrollUp"_s,
			"PAGE_UP"_s,
			"scrollUp"_s,
			"PAGE_DOWN"_s,
			"scrollDown"_s,
			"ctrl PAGE_UP"_s,
			"scrollLeft"_s,
			"ctrl PAGE_DOWN"_s,
			"scrollRight"_s,
			"ctrl HOME"_s,
			"scrollHome"_s,
			"ctrl END"_s,
			"scrollEnd"_s
		})),
		"Slider.font"_s,
		dialogPlain12,
		"Slider.border"_s,
		focusBevelBorder,
		"Slider.foreground"_s,
		$(table->get("control"_s)),
		"Slider.background"_s,
		controlDarker,
		"Slider.highlight"_s,
		$(table->get("controlHighlight"_s)),
		"Slider.shadow"_s,
		$(table->get("controlShadow"_s)),
		"Slider.focus"_s,
		$(table->get("controlDkShadow"_s)),
		"Slider.focusInsets"_s,
		sliderFocusInsets,
		"Slider.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"RIGHT"_s,
			"positiveUnitIncrement"_s,
			"KP_RIGHT"_s,
			"positiveUnitIncrement"_s,
			"DOWN"_s,
			"negativeUnitIncrement"_s,
			"KP_DOWN"_s,
			"negativeUnitIncrement"_s,
			"ctrl PAGE_DOWN"_s,
			"negativeBlockIncrement"_s,
			"LEFT"_s,
			"negativeUnitIncrement"_s,
			"KP_LEFT"_s,
			"negativeUnitIncrement"_s,
			"UP"_s,
			"positiveUnitIncrement"_s,
			"KP_UP"_s,
			"positiveUnitIncrement"_s,
			"ctrl PAGE_UP"_s,
			"positiveBlockIncrement"_s,
			"HOME"_s,
			"minScroll"_s,
			"END"_s,
			"maxScroll"_s
		})),
		"Spinner.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"UP"_s,
			"increment"_s,
			"KP_UP"_s,
			"increment"_s,
			"DOWN"_s,
			"decrement"_s,
			"KP_DOWN"_s,
			"decrement"_s
		})),
		"Spinner.border"_s,
		textFieldBorder,
		"SplitPane.background"_s,
		$(table->get("control"_s)),
		"SplitPane.highlight"_s,
		$(table->get("controlHighlight"_s)),
		"SplitPane.shadow"_s,
		$(table->get("controlShadow"_s)),
		"SplitPane.dividerSize"_s,
		$($Integer::valueOf(20)),
		"SplitPane.activeThumb"_s,
		$(table->get("activeCaptionBorder"_s)),
		"SplitPane.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"UP"_s,
			"negativeIncrement"_s,
			"DOWN"_s,
			"positiveIncrement"_s,
			"LEFT"_s,
			"negativeIncrement"_s,
			"RIGHT"_s,
			"positiveIncrement"_s,
			"KP_UP"_s,
			"negativeIncrement"_s,
			"KP_DOWN"_s,
			"positiveIncrement"_s,
			"KP_LEFT"_s,
			"negativeIncrement"_s,
			"KP_RIGHT"_s,
			"positiveIncrement"_s,
			"HOME"_s,
			"selectMin"_s,
			"END"_s,
			"selectMax"_s,
			"F8"_s,
			"startResize"_s,
			"F6"_s,
			"toggleFocus"_s,
			"ctrl TAB"_s,
			"focusOutForward"_s,
			"ctrl shift TAB"_s,
			"focusOutBackward"_s
		})),
		"TabbedPane.font"_s,
		dialogPlain12,
		"TabbedPane.background"_s,
		$(table->get("control"_s)),
		"TabbedPane.foreground"_s,
		$(table->get("controlText"_s)),
		"TabbedPane.light"_s,
		$(table->get("controlHighlight"_s)),
		"TabbedPane.highlight"_s,
		$(table->get("controlLtHighlight"_s)),
		"TabbedPane.shadow"_s,
		$(table->get("controlShadow"_s)),
		"TabbedPane.darkShadow"_s,
		$(table->get("controlShadow"_s)),
		"TabbedPane.unselectedTabBackground"_s,
		unselectedTabBackground,
		"TabbedPane.unselectedTabForeground"_s,
		unselectedTabForeground,
		"TabbedPane.unselectedTabHighlight"_s,
		unselectedTabHighlight,
		"TabbedPane.unselectedTabShadow"_s,
		unselectedTabShadow,
		"TabbedPane.focus"_s,
		$(table->get("activeCaptionBorder"_s)),
		"TabbedPane.tabInsets"_s,
		tabbedPaneTabInsets,
		"TabbedPane.selectedTabPadInsets"_s,
		tabbedPaneTabPadInsets,
		"TabbedPane.tabAreaInsets"_s,
		tabbedPaneTabAreaInsets,
		"TabbedPane.contentBorderInsets"_s,
		tabbedPaneContentBorderInsets,
		"TabbedPane.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"RIGHT"_s,
			"navigateRight"_s,
			"KP_RIGHT"_s,
			"navigateRight"_s,
			"LEFT"_s,
			"navigateLeft"_s,
			"KP_LEFT"_s,
			"navigateLeft"_s,
			"UP"_s,
			"navigateUp"_s,
			"KP_UP"_s,
			"navigateUp"_s,
			"DOWN"_s,
			"navigateDown"_s,
			"KP_DOWN"_s,
			"navigateDown"_s,
			"ctrl DOWN"_s,
			"requestFocusForVisibleComponent"_s,
			"ctrl KP_DOWN"_s,
			"requestFocusForVisibleComponent"_s
		})),
		"TabbedPane.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ctrl PAGE_DOWN"_s,
			"navigatePageDown"_s,
			"ctrl PAGE_UP"_s,
			"navigatePageUp"_s,
			"ctrl UP"_s,
			"requestFocus"_s,
			"ctrl KP_UP"_s,
			"requestFocus"_s
		})),
		"Tree.background"_s,
		controlDarker,
		"Tree.hash"_s,
		$(table->get("controlDkShadow"_s)),
		"Tree.iconShadow"_s,
		$(table->get("controlShadow"_s)),
		"Tree.iconHighlight"_s,
		$(table->get("controlHighlight"_s)),
		"Tree.iconBackground"_s,
		$(table->get("control"_s)),
		"Tree.iconForeground"_s,
		$(table->get("controlShadow"_s)),
		"Tree.textBackground"_s,
		controlDarker,
		"Tree.textForeground"_s,
		$(table->get("textText"_s)),
		"Tree.selectionBackground"_s,
		$(table->get("text"_s)),
		"Tree.selectionForeground"_s,
		$(table->get("textText"_s)),
		"Tree.selectionBorderColor"_s,
		$(table->get("activeCaptionBorder"_s)),
		"Tree.openIcon"_s,
		treeOpenIcon,
		"Tree.closedIcon"_s,
		treeClosedIcon,
		"Tree.leafIcon"_s,
		treeLeafIcon,
		"Tree.expandedIcon"_s,
		treeExpandedIcon,
		"Tree.collapsedIcon"_s,
		treeCollapsedIcon,
		"Tree.editorBorder"_s,
		focusBorder,
		"Tree.editorBorderSelectionColor"_s,
		$(table->get("activeCaptionBorder"_s)),
		"Tree.rowHeight"_s,
		$($Integer::valueOf(18)),
		"Tree.drawsFocusBorderAroundIcon"_s,
		$Boolean::TRUE,
		"Tree.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"COPY"_s,
			"copy"_s,
			"PASTE"_s,
			"paste"_s,
			"CUT"_s,
			"cut"_s,
			"control INSERT"_s,
			"copy"_s,
			"shift INSERT"_s,
			"paste"_s,
			"shift DELETE"_s,
			"cut"_s,
			"UP"_s,
			"selectPrevious"_s,
			"KP_UP"_s,
			"selectPrevious"_s,
			"shift UP"_s,
			"selectPreviousExtendSelection"_s,
			"shift KP_UP"_s,
			"selectPreviousExtendSelection"_s,
			"ctrl shift UP"_s,
			"selectPreviousExtendSelection"_s,
			"ctrl shift KP_UP"_s,
			"selectPreviousExtendSelection"_s,
			"ctrl UP"_s,
			"selectPreviousChangeLead"_s,
			"ctrl KP_UP"_s,
			"selectPreviousChangeLead"_s,
			"DOWN"_s,
			"selectNext"_s,
			"KP_DOWN"_s,
			"selectNext"_s,
			"shift DOWN"_s,
			"selectNextExtendSelection"_s,
			"shift KP_DOWN"_s,
			"selectNextExtendSelection"_s,
			"ctrl shift DOWN"_s,
			"selectNextExtendSelection"_s,
			"ctrl shift KP_DOWN"_s,
			"selectNextExtendSelection"_s,
			"ctrl DOWN"_s,
			"selectNextChangeLead"_s,
			"ctrl KP_DOWN"_s,
			"selectNextChangeLead"_s,
			"RIGHT"_s,
			"selectChild"_s,
			"KP_RIGHT"_s,
			"selectChild"_s,
			"LEFT"_s,
			"selectParent"_s,
			"KP_LEFT"_s,
			"selectParent"_s,
			"PAGE_UP"_s,
			"scrollUpChangeSelection"_s,
			"shift PAGE_UP"_s,
			"scrollUpExtendSelection"_s,
			"ctrl shift PAGE_UP"_s,
			"scrollUpExtendSelection"_s,
			"ctrl PAGE_UP"_s,
			"scrollUpChangeLead"_s,
			"PAGE_DOWN"_s,
			"scrollDownChangeSelection"_s,
			"shift PAGE_DOWN"_s,
			"scrollDownExtendSelection"_s,
			"ctrl shift PAGE_DOWN"_s,
			"scrollDownExtendSelection"_s,
			"ctrl PAGE_DOWN"_s,
			"scrollDownChangeLead"_s,
			"HOME"_s,
			"selectFirst"_s,
			"shift HOME"_s,
			"selectFirstExtendSelection"_s,
			"ctrl shift HOME"_s,
			"selectFirstExtendSelection"_s,
			"ctrl HOME"_s,
			"selectFirstChangeLead"_s,
			"END"_s,
			"selectLast"_s,
			"shift END"_s,
			"selectLastExtendSelection"_s,
			"ctrl shift END"_s,
			"selectLastExtendSelection"_s,
			"ctrl END"_s,
			"selectLastChangeLead"_s,
			"F2"_s,
			"startEditing"_s,
			"ctrl A"_s,
			"selectAll"_s,
			"ctrl SLASH"_s,
			"selectAll"_s,
			"ctrl BACK_SLASH"_s,
			"clearSelection"_s,
			"ctrl LEFT"_s,
			"scrollLeft"_s,
			"ctrl KP_LEFT"_s,
			"scrollLeft"_s,
			"ctrl RIGHT"_s,
			"scrollRight"_s,
			"ctrl KP_RIGHT"_s,
			"scrollRight"_s,
			"SPACE"_s,
			"addToSelection"_s,
			"ctrl SPACE"_s,
			"toggleAndAnchor"_s,
			"shift SPACE"_s,
			"extendTo"_s,
			"ctrl shift SPACE"_s,
			"moveSelectionTo"_s
		})),
		"Tree.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ESCAPE"_s,
			"cancel"_s
		})),
		"Table.focusCellHighlightBorder"_s,
		focusCellHighlightBorder,
		"Table.scrollPaneBorder"_s,
		nullptr,
		"Table.dropLineShortColor"_s,
		$(table->get("activeCaptionBorder"_s)),
		"Table.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"COPY"_s,
			"copy"_s,
			"PASTE"_s,
			"paste"_s,
			"CUT"_s,
			"cut"_s,
			"control INSERT"_s,
			"copy"_s,
			"shift INSERT"_s,
			"paste"_s,
			"shift DELETE"_s,
			"cut"_s,
			"RIGHT"_s,
			"selectNextColumn"_s,
			"KP_RIGHT"_s,
			"selectNextColumn"_s,
			"shift RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"shift KP_RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl shift RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl shift KP_RIGHT"_s,
			"selectNextColumnExtendSelection"_s,
			"ctrl RIGHT"_s,
			"selectNextColumnChangeLead"_s,
			"ctrl KP_RIGHT"_s,
			"selectNextColumnChangeLead"_s,
			"LEFT"_s,
			"selectPreviousColumn"_s,
			"KP_LEFT"_s,
			"selectPreviousColumn"_s,
			"shift LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"shift KP_LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl shift LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl shift KP_LEFT"_s,
			"selectPreviousColumnExtendSelection"_s,
			"ctrl LEFT"_s,
			"selectPreviousColumnChangeLead"_s,
			"ctrl KP_LEFT"_s,
			"selectPreviousColumnChangeLead"_s,
			"DOWN"_s,
			"selectNextRow"_s,
			"KP_DOWN"_s,
			"selectNextRow"_s,
			"shift DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"shift KP_DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl shift DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl shift KP_DOWN"_s,
			"selectNextRowExtendSelection"_s,
			"ctrl DOWN"_s,
			"selectNextRowChangeLead"_s,
			"ctrl KP_DOWN"_s,
			"selectNextRowChangeLead"_s,
			"UP"_s,
			"selectPreviousRow"_s,
			"KP_UP"_s,
			"selectPreviousRow"_s,
			"shift UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"shift KP_UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl shift UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl shift KP_UP"_s,
			"selectPreviousRowExtendSelection"_s,
			"ctrl UP"_s,
			"selectPreviousRowChangeLead"_s,
			"ctrl KP_UP"_s,
			"selectPreviousRowChangeLead"_s,
			"HOME"_s,
			"selectFirstColumn"_s,
			"shift HOME"_s,
			"selectFirstColumnExtendSelection"_s,
			"ctrl shift HOME"_s,
			"selectFirstRowExtendSelection"_s,
			"ctrl HOME"_s,
			"selectFirstRow"_s,
			"END"_s,
			"selectLastColumn"_s,
			"shift END"_s,
			"selectLastColumnExtendSelection"_s,
			"ctrl shift END"_s,
			"selectLastRowExtendSelection"_s,
			"ctrl END"_s,
			"selectLastRow"_s,
			"PAGE_UP"_s,
			"scrollUpChangeSelection"_s,
			"shift PAGE_UP"_s,
			"scrollUpExtendSelection"_s,
			"ctrl shift PAGE_UP"_s,
			"scrollLeftExtendSelection"_s,
			"ctrl PAGE_UP"_s,
			"scrollLeftChangeSelection"_s,
			"PAGE_DOWN"_s,
			"scrollDownChangeSelection"_s,
			"shift PAGE_DOWN"_s,
			"scrollDownExtendSelection"_s,
			"ctrl shift PAGE_DOWN"_s,
			"scrollRightExtendSelection"_s,
			"ctrl PAGE_DOWN"_s,
			"scrollRightChangeSelection"_s,
			"TAB"_s,
			"selectNextColumnCell"_s,
			"shift TAB"_s,
			"selectPreviousColumnCell"_s,
			"ENTER"_s,
			"selectNextRowCell"_s,
			"shift ENTER"_s,
			"selectPreviousRowCell"_s,
			"ctrl A"_s,
			"selectAll"_s,
			"ctrl SLASH"_s,
			"selectAll"_s,
			"ctrl BACK_SLASH"_s,
			"clearSelection"_s,
			"ESCAPE"_s,
			"cancel"_s,
			"F2"_s,
			"startEditing"_s,
			"SPACE"_s,
			"addToSelection"_s,
			"ctrl SPACE"_s,
			"toggleAndAnchor"_s,
			"shift SPACE"_s,
			"extendTo"_s,
			"ctrl shift SPACE"_s,
			"moveSelectionTo"_s,
			"F8"_s,
			"focusHeader"_s
		})),
		"FormattedTextField.focusInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ctrl C"_s,
			$DefaultEditorKit::copyAction,
			"ctrl V"_s,
			$DefaultEditorKit::pasteAction,
			"ctrl X"_s,
			$DefaultEditorKit::cutAction,
			"COPY"_s,
			$DefaultEditorKit::copyAction,
			"PASTE"_s,
			$DefaultEditorKit::pasteAction,
			"CUT"_s,
			$DefaultEditorKit::cutAction,
			"shift LEFT"_s,
			$DefaultEditorKit::selectionBackwardAction,
			"shift KP_LEFT"_s,
			$DefaultEditorKit::selectionBackwardAction,
			"shift RIGHT"_s,
			$DefaultEditorKit::selectionForwardAction,
			"shift KP_RIGHT"_s,
			$DefaultEditorKit::selectionForwardAction,
			"ctrl LEFT"_s,
			$DefaultEditorKit::previousWordAction,
			"ctrl KP_LEFT"_s,
			$DefaultEditorKit::previousWordAction,
			"ctrl RIGHT"_s,
			$DefaultEditorKit::nextWordAction,
			"ctrl KP_RIGHT"_s,
			$DefaultEditorKit::nextWordAction,
			"ctrl shift LEFT"_s,
			$DefaultEditorKit::selectionPreviousWordAction,
			"ctrl shift KP_LEFT"_s,
			$DefaultEditorKit::selectionPreviousWordAction,
			"ctrl shift RIGHT"_s,
			$DefaultEditorKit::selectionNextWordAction,
			"ctrl shift KP_RIGHT"_s,
			$DefaultEditorKit::selectionNextWordAction,
			"ctrl A"_s,
			$DefaultEditorKit::selectAllAction,
			"HOME"_s,
			$DefaultEditorKit::beginLineAction,
			"END"_s,
			$DefaultEditorKit::endLineAction,
			"shift HOME"_s,
			$DefaultEditorKit::selectionBeginLineAction,
			"shift END"_s,
			$DefaultEditorKit::selectionEndLineAction,
			"BACK_SPACE"_s,
			$DefaultEditorKit::deletePrevCharAction,
			"shift BACK_SPACE"_s,
			$DefaultEditorKit::deletePrevCharAction,
			"ctrl H"_s,
			$DefaultEditorKit::deletePrevCharAction,
			"DELETE"_s,
			$DefaultEditorKit::deleteNextCharAction,
			"ctrl DELETE"_s,
			$DefaultEditorKit::deleteNextWordAction,
			"ctrl BACK_SPACE"_s,
			$DefaultEditorKit::deletePrevWordAction,
			"RIGHT"_s,
			$DefaultEditorKit::forwardAction,
			"LEFT"_s,
			$DefaultEditorKit::backwardAction,
			"KP_RIGHT"_s,
			$DefaultEditorKit::forwardAction,
			"KP_LEFT"_s,
			$DefaultEditorKit::backwardAction,
			"ENTER"_s,
			$JTextField::notifyAction,
			"ctrl BACK_SLASH"_s,
			"unselect"_s,
			"control shift O"_s,
			"toggle-componentOrientation"_s,
			"ESCAPE"_s,
			"reset-field-edit"_s,
			"UP"_s,
			"increment"_s,
			"KP_UP"_s,
			"increment"_s,
			"DOWN"_s,
			"decrement"_s,
			"KP_DOWN"_s,
			"decrement"_s
		})),
		"ToolBar.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"UP"_s,
			"navigateUp"_s,
			"KP_UP"_s,
			"navigateUp"_s,
			"DOWN"_s,
			"navigateDown"_s,
			"KP_DOWN"_s,
			"navigateDown"_s,
			"LEFT"_s,
			"navigateLeft"_s,
			"KP_LEFT"_s,
			"navigateLeft"_s,
			"RIGHT"_s,
			"navigateRight"_s,
			"KP_RIGHT"_s,
			"navigateRight"_s
		})),
		"ComboBox.control"_s,
		$(table->get("control"_s)),
		"ComboBox.controlForeground"_s,
		black,
		"ComboBox.background"_s,
		$(table->get("window"_s)),
		"ComboBox.foreground"_s,
		black,
		"ComboBox.border"_s,
		comboBoxBorder,
		"ComboBox.selectionBackground"_s,
		black,
		"ComboBox.selectionForeground"_s,
		$(table->get("text"_s)),
		"ComboBox.disabledBackground"_s,
		$(table->get("control"_s)),
		"ComboBox.disabledForeground"_s,
		$(table->get("textInactiveText"_s)),
		"ComboBox.font"_s,
		dialogPlain12,
		"ComboBox.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ESCAPE"_s,
			"hidePopup"_s,
			"PAGE_UP"_s,
			"pageUpPassThrough"_s,
			"PAGE_DOWN"_s,
			"pageDownPassThrough"_s,
			"HOME"_s,
			"homePassThrough"_s,
			"END"_s,
			"endPassThrough"_s,
			"DOWN"_s,
			"selectNext"_s,
			"KP_DOWN"_s,
			"selectNext"_s,
			"UP"_s,
			"selectPrevious"_s,
			"KP_UP"_s,
			"selectPrevious"_s,
			"SPACE"_s,
			"spacePopup"_s,
			"ENTER"_s,
			"enterPressed"_s
		})),
		"TextField.caretForeground"_s,
		black,
		"TextField.caretBlinkRate"_s,
		$($Integer::valueOf(500)),
		"TextField.inactiveForeground"_s,
		$(table->get("textInactiveText"_s)),
		"TextField.selectionBackground"_s,
		$(table->get("textHighlight"_s)),
		"TextField.selectionForeground"_s,
		$(table->get("textHighlightText"_s)),
		"TextField.background"_s,
		$(table->get("window"_s)),
		"TextField.foreground"_s,
		$(table->get("textText"_s)),
		"TextField.font"_s,
		sansSerifPlain12,
		"TextField.border"_s,
		textFieldBorder,
		"TextField.focusInputMap"_s,
		fieldInputMap,
		"PasswordField.caretForeground"_s,
		black,
		"PasswordField.caretBlinkRate"_s,
		$($Integer::valueOf(500)),
		"PasswordField.inactiveForeground"_s,
		$(table->get("textInactiveText"_s)),
		"PasswordField.selectionBackground"_s,
		$(table->get("textHighlight"_s)),
		"PasswordField.selectionForeground"_s,
		$(table->get("textHighlightText"_s)),
		"PasswordField.background"_s,
		$(table->get("window"_s)),
		"PasswordField.foreground"_s,
		$(table->get("textText"_s)),
		"PasswordField.font"_s,
		monospacedPlain12,
		"PasswordField.border"_s,
		textFieldBorder,
		"PasswordField.focusInputMap"_s,
		passwordInputMap,
		"TextArea.caretForeground"_s,
		black,
		"TextArea.caretBlinkRate"_s,
		$($Integer::valueOf(500)),
		"TextArea.inactiveForeground"_s,
		$(table->get("textInactiveText"_s)),
		"TextArea.selectionBackground"_s,
		$(table->get("textHighlight"_s)),
		"TextArea.selectionForeground"_s,
		$(table->get("textHighlightText"_s)),
		"TextArea.background"_s,
		$(table->get("window"_s)),
		"TextArea.foreground"_s,
		$(table->get("textText"_s)),
		"TextArea.font"_s,
		monospacedPlain12,
		"TextArea.border"_s,
		marginBorder,
		"TextArea.focusInputMap"_s,
		multilineInputMap,
		"TextPane.caretForeground"_s,
		black,
		"TextPane.caretBlinkRate"_s,
		$($Integer::valueOf(500)),
		"TextPane.inactiveForeground"_s,
		$(table->get("textInactiveText"_s)),
		"TextPane.selectionBackground"_s,
		lightGray,
		"TextPane.selectionForeground"_s,
		$(table->get("textHighlightText"_s)),
		"TextPane.background"_s,
		white,
		"TextPane.foreground"_s,
		$(table->get("textText"_s)),
		"TextPane.font"_s,
		serifPlain12,
		"TextPane.border"_s,
		marginBorder,
		"TextPane.focusInputMap"_s,
		multilineInputMap,
		"EditorPane.caretForeground"_s,
		red,
		"EditorPane.caretBlinkRate"_s,
		$($Integer::valueOf(500)),
		"EditorPane.inactiveForeground"_s,
		$(table->get("textInactiveText"_s)),
		"EditorPane.selectionBackground"_s,
		lightGray,
		"EditorPane.selectionForeground"_s,
		$(table->get("textHighlightText"_s)),
		"EditorPane.background"_s,
		white,
		"EditorPane.foreground"_s,
		$(table->get("textText"_s)),
		"EditorPane.font"_s,
		serifPlain12,
		"EditorPane.border"_s,
		marginBorder,
		"EditorPane.focusInputMap"_s,
		multilineInputMap,
		"FileChooser.ancestorInputMap"_s,
		$$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			"ESCAPE"_s,
			"cancelSelection"_s
		})),
		"ToolTip.border"_s,
		raisedBevelBorder,
		"ToolTip.background"_s,
		$(table->get("info"_s)),
		"ToolTip.foreground"_s,
		$(table->get("infoText"_s)),
		"PopupMenu.selectedWindowInputMapBindings"_s,
		$$new($ObjectArray, {
			"ESCAPE"_s,
			"cancel"_s,
			"TAB"_s,
			"cancel"_s,
			"shift TAB"_s,
			"cancel"_s,
			"DOWN"_s,
			"selectNext"_s,
			"KP_DOWN"_s,
			"selectNext"_s,
			"UP"_s,
			"selectPrevious"_s,
			"KP_UP"_s,
			"selectPrevious"_s,
			"LEFT"_s,
			"selectParent"_s,
			"KP_LEFT"_s,
			"selectParent"_s,
			"RIGHT"_s,
			"selectChild"_s,
			"KP_RIGHT"_s,
			"selectChild"_s,
			"ENTER"_s,
			"return"_s,
			"ctrl ENTER"_s,
			"return"_s,
			"SPACE"_s,
			"return"_s
		}),
		"OptionPane.border"_s,
		optionPaneBorder,
		"OptionPane.messageAreaBorder"_s,
		optionPaneMessageAreaBorder,
		"OptionPane.buttonAreaBorder"_s,
		optionPaneButtonAreaBorder,
		"OptionPane.errorIcon"_s,
		$($SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/Error.gif"_s)),
		"OptionPane.informationIcon"_s,
		$($SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/Inform.gif"_s)),
		"OptionPane.warningIcon"_s,
		$($SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/Warn.gif"_s)),
		"OptionPane.questionIcon"_s,
		$($SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/Question.gif"_s)),
		"OptionPane.windowBindings"_s,
		$$new($ObjectArray, {
			"ESCAPE"_s,
			"close"_s
		}),
		"RootPane.defaultButtonWindowKeyBindings"_s,
		$$new($ObjectArray, {
			"ENTER"_s,
			"press"_s,
			"released ENTER"_s,
			"release"_s,
			"ctrl ENTER"_s,
			"press"_s,
			"ctrl released ENTER"_s,
			"release"_s
		})
	}));
	table->putDefaults(defaults);
}

MotifLookAndFeel::MotifLookAndFeel() {
}

$Class* MotifLookAndFeel::load$($String* name, bool initialize) {
	$MethodInfo methodInfos$$[] = {
		{"<init>", "()V", nullptr, $PUBLIC, $method(MotifLookAndFeel, init$, void)},
		{"getDescription", "()Ljava/lang/String;", nullptr, $PUBLIC, $virtualMethod(MotifLookAndFeel, getDescription, $String*)},
		{"getID", "()Ljava/lang/String;", nullptr, $PUBLIC, $virtualMethod(MotifLookAndFeel, getID, $String*)},
		{"getName", "()Ljava/lang/String;", nullptr, $PUBLIC, $virtualMethod(MotifLookAndFeel, getName, $String*)},
		{"initClassDefaults", "(Ljavax/swing/UIDefaults;)V", nullptr, $PROTECTED, $virtualMethod(MotifLookAndFeel, initClassDefaults, void, $UIDefaults*)},
		{"initComponentDefaults", "(Ljavax/swing/UIDefaults;)V", nullptr, $PROTECTED, $virtualMethod(MotifLookAndFeel, initComponentDefaults, void, $UIDefaults*)},
		{"initResourceBundle", "(Ljavax/swing/UIDefaults;)V", nullptr, $PRIVATE, $method(MotifLookAndFeel, initResourceBundle, void, $UIDefaults*)},
		{"initSystemColorDefaults", "(Ljavax/swing/UIDefaults;)V", nullptr, $PROTECTED, $virtualMethod(MotifLookAndFeel, initSystemColorDefaults, void, $UIDefaults*)},
		{"isNativeLookAndFeel", "()Z", nullptr, $PUBLIC, $virtualMethod(MotifLookAndFeel, isNativeLookAndFeel, bool)},
		{"isSupportedLookAndFeel", "()Z", nullptr, $PUBLIC, $virtualMethod(MotifLookAndFeel, isSupportedLookAndFeel, bool)},
		{}
	};
	$InnerClassInfo innerClassesInfo$$[] = {
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$12", nullptr, nullptr, 0},
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$11", nullptr, nullptr, 0},
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$10", nullptr, nullptr, 0},
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$9", nullptr, nullptr, 0},
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$8", nullptr, nullptr, 0},
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$7", nullptr, nullptr, 0},
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$6", nullptr, nullptr, 0},
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$5", nullptr, nullptr, 0},
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$4", nullptr, nullptr, 0},
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$3", nullptr, nullptr, 0},
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$2", nullptr, nullptr, 0},
		{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$1", nullptr, nullptr, 0},
		{}
	};
	$NamedAttribute annotations$$$namedAttribute[] = {
		{"since", 's', "13"},
		{"forRemoval", 'Z', "true"},
		{}
	};
	$CompoundAttribute annotations$$[] = {
		{"Ljava/lang/Deprecated;", annotations$$$namedAttribute},
		{}
	};
	$ClassInfo classInfo$$ = {
		$PUBLIC | $ACC_SUPER,
		"com.sun.java.swing.plaf.motif.MotifLookAndFeel",
		"javax.swing.plaf.basic.BasicLookAndFeel",
		nullptr,
		nullptr,
		methodInfos$$,
		nullptr,
		nullptr,
		innerClassesInfo$$,
		annotations$$,
		nullptr,
		"com.sun.java.swing.plaf.motif.MotifLookAndFeel$12,com.sun.java.swing.plaf.motif.MotifLookAndFeel$11,com.sun.java.swing.plaf.motif.MotifLookAndFeel$10,com.sun.java.swing.plaf.motif.MotifLookAndFeel$9,com.sun.java.swing.plaf.motif.MotifLookAndFeel$8,com.sun.java.swing.plaf.motif.MotifLookAndFeel$7,com.sun.java.swing.plaf.motif.MotifLookAndFeel$6,com.sun.java.swing.plaf.motif.MotifLookAndFeel$5,com.sun.java.swing.plaf.motif.MotifLookAndFeel$4,com.sun.java.swing.plaf.motif.MotifLookAndFeel$3,com.sun.java.swing.plaf.motif.MotifLookAndFeel$2,com.sun.java.swing.plaf.motif.MotifLookAndFeel$1"
	};
	$loadClass(MotifLookAndFeel, name, initialize, &classInfo$$, []($Class* clazz) -> $Object* {
		return $of($alloc(MotifLookAndFeel));
	});
	return class$;
}

$Class* MotifLookAndFeel::class$ = nullptr;

					} // motif
				} // plaf
			} // swing
		} // java
	} // sun
} // com