#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel.h>

#include <com/sun/java/swing/plaf/motif/MotifBorders$BevelBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifBorders$ButtonBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifBorders$FocusBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifBorders$MenuBarBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifBorders$MotifPopupMenuBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifBorders$ToggleButtonBorder.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$1.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$10.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$11.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$12.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$2.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$3.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$4.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$5.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$6.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$7.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$8.h>
#include <com/sun/java/swing/plaf/motif/MotifLookAndFeel$9.h>
#include <java/awt/Color.h>
#include <java/awt/Font.h>
#include <java/awt/event/KeyEvent.h>
#include <javax/swing/JTextField.h>
#include <javax/swing/UIDefaults$LazyInputMap.h>
#include <javax/swing/UIDefaults.h>
#include <javax/swing/border/AbstractBorder.h>
#include <javax/swing/border/Border.h>
#include <javax/swing/border/CompoundBorder.h>
#include <javax/swing/border/LineBorder.h>
#include <javax/swing/plaf/BorderUIResource$CompoundBorderUIResource.h>
#include <javax/swing/plaf/BorderUIResource$EmptyBorderUIResource.h>
#include <javax/swing/plaf/BorderUIResource$LineBorderUIResource.h>
#include <javax/swing/plaf/ColorUIResource.h>
#include <javax/swing/plaf/FontUIResource.h>
#include <javax/swing/plaf/InsetsUIResource.h>
#include <javax/swing/plaf/basic/BasicBorders$MarginBorder.h>
#include <javax/swing/plaf/basic/BasicLookAndFeel.h>
#include <javax/swing/text/DefaultEditorKit.h>
#include <sun/swing/SwingAccessor$UIDefaultsAccessor.h>
#include <sun/swing/SwingAccessor.h>
#include <sun/swing/SwingUtilities2.h>
#include <jcpp.h>

#undef DIALOG
#undef FALSE
#undef META_MASK
#undef MONOSPACED
#undef PLAIN
#undef SANS_SERIF
#undef SERIF
#undef TRUE

using $MotifBorders$BevelBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$BevelBorder;
using $MotifBorders$ButtonBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$ButtonBorder;
using $MotifBorders$FocusBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$FocusBorder;
using $MotifBorders$MenuBarBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$MenuBarBorder;
using $MotifBorders$MotifPopupMenuBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$MotifPopupMenuBorder;
using $MotifBorders$ToggleButtonBorder = ::com::sun::java::swing::plaf::motif::MotifBorders$ToggleButtonBorder;
using $MotifLookAndFeel$1 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$1;
using $MotifLookAndFeel$10 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$10;
using $MotifLookAndFeel$11 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$11;
using $MotifLookAndFeel$12 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$12;
using $MotifLookAndFeel$2 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$2;
using $MotifLookAndFeel$3 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$3;
using $MotifLookAndFeel$4 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$4;
using $MotifLookAndFeel$5 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$5;
using $MotifLookAndFeel$6 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$6;
using $MotifLookAndFeel$7 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$7;
using $MotifLookAndFeel$8 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$8;
using $MotifLookAndFeel$9 = ::com::sun::java::swing::plaf::motif::MotifLookAndFeel$9;
using $Color = ::java::awt::Color;
using $Font = ::java::awt::Font;
using $KeyEvent = ::java::awt::event::KeyEvent;
using $Boolean = ::java::lang::Boolean;
using $ClassInfo = ::java::lang::ClassInfo;
using $CompoundAttribute = ::java::lang::CompoundAttribute;
using $InnerClassInfo = ::java::lang::InnerClassInfo;
using $Integer = ::java::lang::Integer;
using $MethodInfo = ::java::lang::MethodInfo;
using $NamedAttribute = ::java::lang::NamedAttribute;
using $JTextField = ::javax::swing::JTextField;
using $UIDefaults = ::javax::swing::UIDefaults;
using $UIDefaults$LazyInputMap = ::javax::swing::UIDefaults$LazyInputMap;
using $AbstractBorder = ::javax::swing::border::AbstractBorder;
using $Border = ::javax::swing::border::Border;
using $CompoundBorder = ::javax::swing::border::CompoundBorder;
using $LineBorder = ::javax::swing::border::LineBorder;
using $BorderUIResource$CompoundBorderUIResource = ::javax::swing::plaf::BorderUIResource$CompoundBorderUIResource;
using $BorderUIResource$EmptyBorderUIResource = ::javax::swing::plaf::BorderUIResource$EmptyBorderUIResource;
using $BorderUIResource$LineBorderUIResource = ::javax::swing::plaf::BorderUIResource$LineBorderUIResource;
using $ColorUIResource = ::javax::swing::plaf::ColorUIResource;
using $FontUIResource = ::javax::swing::plaf::FontUIResource;
using $InsetsUIResource = ::javax::swing::plaf::InsetsUIResource;
using $BasicBorders$MarginBorder = ::javax::swing::plaf::basic::BasicBorders$MarginBorder;
using $BasicLookAndFeel = ::javax::swing::plaf::basic::BasicLookAndFeel;
using $DefaultEditorKit = ::javax::swing::text::DefaultEditorKit;
using $SwingAccessor = ::sun::swing::SwingAccessor;
using $SwingAccessor$UIDefaultsAccessor = ::sun::swing::SwingAccessor$UIDefaultsAccessor;
using $SwingUtilities2 = ::sun::swing::SwingUtilities2;

namespace com {
	namespace sun {
		namespace java {
			namespace swing {
				namespace plaf {
					namespace motif {

$NamedAttribute MotifLookAndFeel_Attribute_var$0[] = {
	{"since", 's', "13"},
	{"forRemoval", 'Z', "true"},
	{}
};

$CompoundAttribute _MotifLookAndFeel_Annotations_[] = {
	{"Ljava/lang/Deprecated;", MotifLookAndFeel_Attribute_var$0},
	{}
};

$MethodInfo _MotifLookAndFeel_MethodInfo_[] = {
	{"<init>", "()V", nullptr, $PUBLIC, $method(MotifLookAndFeel, init$, void)},
	{"getDescription", "()Ljava/lang/String;", nullptr, $PUBLIC, $virtualMethod(MotifLookAndFeel, getDescription, $String*)},
	{"getID", "()Ljava/lang/String;", nullptr, $PUBLIC, $virtualMethod(MotifLookAndFeel, getID, $String*)},
	{"getName", "()Ljava/lang/String;", nullptr, $PUBLIC, $virtualMethod(MotifLookAndFeel, getName, $String*)},
	{"initClassDefaults", "(Ljavax/swing/UIDefaults;)V", nullptr, $PROTECTED, $virtualMethod(MotifLookAndFeel, initClassDefaults, void, $UIDefaults*)},
	{"initComponentDefaults", "(Ljavax/swing/UIDefaults;)V", nullptr, $PROTECTED, $virtualMethod(MotifLookAndFeel, initComponentDefaults, void, $UIDefaults*)},
	{"initResourceBundle", "(Ljavax/swing/UIDefaults;)V", nullptr, $PRIVATE, $method(MotifLookAndFeel, initResourceBundle, void, $UIDefaults*)},
	{"initSystemColorDefaults", "(Ljavax/swing/UIDefaults;)V", nullptr, $PROTECTED, $virtualMethod(MotifLookAndFeel, initSystemColorDefaults, void, $UIDefaults*)},
	{"isNativeLookAndFeel", "()Z", nullptr, $PUBLIC, $virtualMethod(MotifLookAndFeel, isNativeLookAndFeel, bool)},
	{"isSupportedLookAndFeel", "()Z", nullptr, $PUBLIC, $virtualMethod(MotifLookAndFeel, isSupportedLookAndFeel, bool)},
	{}
};

$InnerClassInfo _MotifLookAndFeel_InnerClassesInfo_[] = {
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$12", nullptr, nullptr, 0},
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$11", nullptr, nullptr, 0},
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$10", nullptr, nullptr, 0},
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$9", nullptr, nullptr, 0},
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$8", nullptr, nullptr, 0},
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$7", nullptr, nullptr, 0},
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$6", nullptr, nullptr, 0},
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$5", nullptr, nullptr, 0},
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$4", nullptr, nullptr, 0},
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$3", nullptr, nullptr, 0},
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$2", nullptr, nullptr, 0},
	{"com.sun.java.swing.plaf.motif.MotifLookAndFeel$1", nullptr, nullptr, 0},
	{}
};

$ClassInfo _MotifLookAndFeel_ClassInfo_ = {
	$PUBLIC | $ACC_SUPER,
	"com.sun.java.swing.plaf.motif.MotifLookAndFeel",
	"javax.swing.plaf.basic.BasicLookAndFeel",
	nullptr,
	nullptr,
	_MotifLookAndFeel_MethodInfo_,
	nullptr,
	nullptr,
	_MotifLookAndFeel_InnerClassesInfo_,
	_MotifLookAndFeel_Annotations_,
	nullptr,
	"com.sun.java.swing.plaf.motif.MotifLookAndFeel$12,com.sun.java.swing.plaf.motif.MotifLookAndFeel$11,com.sun.java.swing.plaf.motif.MotifLookAndFeel$10,com.sun.java.swing.plaf.motif.MotifLookAndFeel$9,com.sun.java.swing.plaf.motif.MotifLookAndFeel$8,com.sun.java.swing.plaf.motif.MotifLookAndFeel$7,com.sun.java.swing.plaf.motif.MotifLookAndFeel$6,com.sun.java.swing.plaf.motif.MotifLookAndFeel$5,com.sun.java.swing.plaf.motif.MotifLookAndFeel$4,com.sun.java.swing.plaf.motif.MotifLookAndFeel$3,com.sun.java.swing.plaf.motif.MotifLookAndFeel$2,com.sun.java.swing.plaf.motif.MotifLookAndFeel$1"
};

$Object* allocate$MotifLookAndFeel($Class* clazz) {
	return $of($alloc(MotifLookAndFeel));
}

void MotifLookAndFeel::init$() {
	$BasicLookAndFeel::init$();
}

$String* MotifLookAndFeel::getName() {
	return "CDE/Motif"_s;
}

$String* MotifLookAndFeel::getID() {
	return "Motif"_s;
}

$String* MotifLookAndFeel::getDescription() {
	return "The CDE/Motif Look and Feel"_s;
}

bool MotifLookAndFeel::isNativeLookAndFeel() {
	return false;
}

bool MotifLookAndFeel::isSupportedLookAndFeel() {
	return true;
}

void MotifLookAndFeel::initSystemColorDefaults($UIDefaults* table) {
	$var($StringArray, defaultSystemColors, $new($StringArray, {
		"desktop"_s,
		"#005C5C"_s,
		"activeCaption"_s,
		"#000080"_s,
		"activeCaptionText"_s,
		"#FFFFFF"_s,
		"activeCaptionBorder"_s,
		"#B24D7A"_s,
		"inactiveCaption"_s,
		"#AEB2C3"_s,
		"inactiveCaptionText"_s,
		"#000000"_s,
		"inactiveCaptionBorder"_s,
		"#AEB2C3"_s,
		"window"_s,
		"#AEB2C3"_s,
		"windowBorder"_s,
		"#AEB2C3"_s,
		"windowText"_s,
		"#000000"_s,
		"menu"_s,
		"#AEB2C3"_s,
		"menuText"_s,
		"#000000"_s,
		"text"_s,
		"#FFF7E9"_s,
		"textText"_s,
		"#000000"_s,
		"textHighlight"_s,
		"#000000"_s,
		"textHighlightText"_s,
		"#FFF7E9"_s,
		"textInactiveText"_s,
		"#808080"_s,
		"control"_s,
		"#AEB2C3"_s,
		"controlText"_s,
		"#000000"_s,
		"controlHighlight"_s,
		"#DCDEE5"_s,
		"controlLtHighlight"_s,
		"#DCDEE5"_s,
		"controlShadow"_s,
		"#63656F"_s,
		"controlLightShadow"_s,
		"#9397A5"_s,
		"controlDkShadow"_s,
		"#000000"_s,
		"scrollbar"_s,
		"#AEB2C3"_s,
		"info"_s,
		"#FFF7E9"_s,
		"infoText"_s,
		"#000000"_s
	}));
	loadSystemColors(table, defaultSystemColors, false);
}

void MotifLookAndFeel::initClassDefaults($UIDefaults* table) {
	$useLocalCurrentObjectStackCache();
	$BasicLookAndFeel::initClassDefaults(table);
	$var($String, motifPackageName, "com.sun.java.swing.plaf.motif."_s);
	$var($ObjectArray, uiDefaults, $new($ObjectArray, {
		$of("ButtonUI"_s),
		$of($$str({motifPackageName, "MotifButtonUI"_s})),
		$of("CheckBoxUI"_s),
		$of($$str({motifPackageName, "MotifCheckBoxUI"_s})),
		$of("DirectoryPaneUI"_s),
		$of($$str({motifPackageName, "MotifDirectoryPaneUI"_s})),
		$of("FileChooserUI"_s),
		$of($$str({motifPackageName, "MotifFileChooserUI"_s})),
		$of("LabelUI"_s),
		$of($$str({motifPackageName, "MotifLabelUI"_s})),
		$of("MenuBarUI"_s),
		$of($$str({motifPackageName, "MotifMenuBarUI"_s})),
		$of("MenuUI"_s),
		$of($$str({motifPackageName, "MotifMenuUI"_s})),
		$of("MenuItemUI"_s),
		$of($$str({motifPackageName, "MotifMenuItemUI"_s})),
		$of("CheckBoxMenuItemUI"_s),
		$of($$str({motifPackageName, "MotifCheckBoxMenuItemUI"_s})),
		$of("RadioButtonMenuItemUI"_s),
		$of($$str({motifPackageName, "MotifRadioButtonMenuItemUI"_s})),
		$of("RadioButtonUI"_s),
		$of($$str({motifPackageName, "MotifRadioButtonUI"_s})),
		$of("ToggleButtonUI"_s),
		$of($$str({motifPackageName, "MotifToggleButtonUI"_s})),
		$of("PopupMenuUI"_s),
		$of($$str({motifPackageName, "MotifPopupMenuUI"_s})),
		$of("ProgressBarUI"_s),
		$of($$str({motifPackageName, "MotifProgressBarUI"_s})),
		$of("ScrollBarUI"_s),
		$of($$str({motifPackageName, "MotifScrollBarUI"_s})),
		$of("ScrollPaneUI"_s),
		$of($$str({motifPackageName, "MotifScrollPaneUI"_s})),
		$of("SliderUI"_s),
		$of($$str({motifPackageName, "MotifSliderUI"_s})),
		$of("SplitPaneUI"_s),
		$of($$str({motifPackageName, "MotifSplitPaneUI"_s})),
		$of("TabbedPaneUI"_s),
		$of($$str({motifPackageName, "MotifTabbedPaneUI"_s})),
		$of("TextAreaUI"_s),
		$of($$str({motifPackageName, "MotifTextAreaUI"_s})),
		$of("TextFieldUI"_s),
		$of($$str({motifPackageName, "MotifTextFieldUI"_s})),
		$of("PasswordFieldUI"_s),
		$of($$str({motifPackageName, "MotifPasswordFieldUI"_s})),
		$of("TextPaneUI"_s),
		$of($$str({motifPackageName, "MotifTextPaneUI"_s})),
		$of("EditorPaneUI"_s),
		$of($$str({motifPackageName, "MotifEditorPaneUI"_s})),
		$of("TreeUI"_s),
		$of($$str({motifPackageName, "MotifTreeUI"_s})),
		$of("InternalFrameUI"_s),
		$of($$str({motifPackageName, "MotifInternalFrameUI"_s})),
		$of("DesktopPaneUI"_s),
		$of($$str({motifPackageName, "MotifDesktopPaneUI"_s})),
		$of("SeparatorUI"_s),
		$of($$str({motifPackageName, "MotifSeparatorUI"_s})),
		$of("PopupMenuSeparatorUI"_s),
		$of($$str({motifPackageName, "MotifPopupMenuSeparatorUI"_s})),
		$of("OptionPaneUI"_s),
		$of($$str({motifPackageName, "MotifOptionPaneUI"_s})),
		$of("ComboBoxUI"_s),
		$of($$str({motifPackageName, "MotifComboBoxUI"_s})),
		$of("DesktopIconUI"_s),
		$of($$str({motifPackageName, "MotifDesktopIconUI"_s}))
	}));
	$nc(table)->putDefaults(uiDefaults);
}

void MotifLookAndFeel::initResourceBundle($UIDefaults* table) {
	$nc($($SwingAccessor::getUIDefaultsAccessor()))->addInternalBundle(table, "com.sun.java.swing.plaf.motif.resources.motif"_s);
}

void MotifLookAndFeel::initComponentDefaults($UIDefaults* table) {
	$useLocalCurrentObjectStackCache();
	$BasicLookAndFeel::initComponentDefaults(table);
	initResourceBundle(table);
	$init($Font);
	$var($FontUIResource, dialogPlain12, $new($FontUIResource, $Font::DIALOG, $Font::PLAIN, 12));
	$var($FontUIResource, serifPlain12, $new($FontUIResource, $Font::SERIF, $Font::PLAIN, 12));
	$var($FontUIResource, sansSerifPlain12, $new($FontUIResource, $Font::SANS_SERIF, $Font::PLAIN, 12));
	$var($FontUIResource, monospacedPlain12, $new($FontUIResource, $Font::MONOSPACED, $Font::PLAIN, 12));
	$init($Color);
	$var($ColorUIResource, red, $new($ColorUIResource, $Color::red));
	$var($ColorUIResource, black, $new($ColorUIResource, $Color::black));
	$var($ColorUIResource, white, $new($ColorUIResource, $Color::white));
	$var($ColorUIResource, lightGray, $new($ColorUIResource, $Color::lightGray));
	$var($ColorUIResource, controlDarker, $new($ColorUIResource, 147, 151, 165));
	$var($ColorUIResource, scrollBarTrack, controlDarker);
	$var($ColorUIResource, menuItemPressedBackground, $new($ColorUIResource, 165, 165, 165));
	$var($ColorUIResource, menuItemPressedForeground, $new($ColorUIResource, 0, 0, 0));
	$var($Color, var$0, $nc(table)->getColor("controlShadow"_s));
	$var($Border, loweredBevelBorder, $new($MotifBorders$BevelBorder, false, var$0, $(table->getColor("controlLtHighlight"_s))));
	$var($Color, var$1, $nc(table)->getColor("controlShadow"_s));
	$var($Border, raisedBevelBorder, $new($MotifBorders$BevelBorder, true, var$1, $(table->getColor("controlLtHighlight"_s))));
	$var($Border, marginBorder, $new($BasicBorders$MarginBorder));
	$var($Color, var$2, $nc(table)->getColor("control"_s));
	$var($Border, focusBorder, $new($MotifBorders$FocusBorder, var$2, $(table->getColor("activeCaptionBorder"_s))));
	$var($Border, focusBevelBorder, $new($BorderUIResource$CompoundBorderUIResource, focusBorder, loweredBevelBorder));
	$var($Border, comboBoxBorder, $new($BorderUIResource$CompoundBorderUIResource, focusBorder, raisedBevelBorder));
	$var($Color, var$3, $nc(table)->getColor("Button.shadow"_s));
	$var($Color, var$4, table->getColor("Button.highlight"_s));
	$var($Color, var$5, table->getColor("Button.darkShadow"_s));
	$var($Border, buttonBorder, $new($BorderUIResource$CompoundBorderUIResource, $$new($MotifBorders$ButtonBorder, var$3, var$4, var$5, $(table->getColor("activeCaptionBorder"_s))), marginBorder));
	$var($Color, var$6, $nc(table)->getColor("ToggleButton.shadow"_s));
	$var($Color, var$7, table->getColor("ToggleButton.highlight"_s));
	$var($Color, var$8, table->getColor("ToggleButton.darkShadow"_s));
	$var($Border, toggleButtonBorder, $new($BorderUIResource$CompoundBorderUIResource, $$new($MotifBorders$ToggleButtonBorder, var$6, var$7, var$8, $(table->getColor("activeCaptionBorder"_s))), marginBorder));
	$var($Border, textFieldBorder, $new($BorderUIResource$CompoundBorderUIResource, focusBevelBorder, marginBorder));
	$var($Font, var$9, $nc(table)->getFont("PopupMenu.font"_s));
	$var($Color, var$10, table->getColor("PopupMenu.background"_s));
	$var($Color, var$11, table->getColor("PopupMenu.foreground"_s));
	$var($Color, var$12, table->getColor("controlShadow"_s));
	$var($Border, popupMenuBorder, $new($BorderUIResource$CompoundBorderUIResource, raisedBevelBorder, $$new($MotifBorders$MotifPopupMenuBorder, var$9, var$10, var$11, var$12, $(table->getColor("controlLtHighlight"_s)))));
	$var($Object, menuItemCheckIcon, $new($MotifLookAndFeel$1, this));
	$var($Object, menuItemArrowIcon, $new($MotifLookAndFeel$2, this));
	$var($Object, menuArrowIcon, $new($MotifLookAndFeel$3, this));
	$var($Object, checkBoxIcon, $new($MotifLookAndFeel$4, this));
	$var($Object, radioButtonIcon, $new($MotifLookAndFeel$5, this));
	$var($Object, unselectedTabBackground, $new($MotifLookAndFeel$6, this));
	$var($Object, unselectedTabForeground, $new($MotifLookAndFeel$7, this));
	$var($Object, unselectedTabShadow, $new($MotifLookAndFeel$8, this));
	$var($Object, unselectedTabHighlight, $new($MotifLookAndFeel$9, this));
	$init($DefaultEditorKit);
	$init($JTextField);
	$var($Object, fieldInputMap, $new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
		$of("COPY"_s),
		$of($DefaultEditorKit::copyAction),
		$of("PASTE"_s),
		$of($DefaultEditorKit::pasteAction),
		$of("CUT"_s),
		$of($DefaultEditorKit::cutAction),
		$of("control INSERT"_s),
		$of($DefaultEditorKit::copyAction),
		$of("shift INSERT"_s),
		$of($DefaultEditorKit::pasteAction),
		$of("shift DELETE"_s),
		$of($DefaultEditorKit::cutAction),
		$of("control F"_s),
		$of($DefaultEditorKit::forwardAction),
		$of("control B"_s),
		$of($DefaultEditorKit::backwardAction),
		$of("control D"_s),
		$of($DefaultEditorKit::deleteNextCharAction),
		$of("BACK_SPACE"_s),
		$of($DefaultEditorKit::deletePrevCharAction),
		$of("shift BACK_SPACE"_s),
		$of($DefaultEditorKit::deletePrevCharAction),
		$of("ctrl H"_s),
		$of($DefaultEditorKit::deletePrevCharAction),
		$of("DELETE"_s),
		$of($DefaultEditorKit::deleteNextCharAction),
		$of("ctrl DELETE"_s),
		$of($DefaultEditorKit::deleteNextWordAction),
		$of("ctrl BACK_SPACE"_s),
		$of($DefaultEditorKit::deletePrevWordAction),
		$of("RIGHT"_s),
		$of($DefaultEditorKit::forwardAction),
		$of("LEFT"_s),
		$of($DefaultEditorKit::backwardAction),
		$of("KP_RIGHT"_s),
		$of($DefaultEditorKit::forwardAction),
		$of("KP_LEFT"_s),
		$of($DefaultEditorKit::backwardAction),
		$of("shift LEFT"_s),
		$of($DefaultEditorKit::selectionBackwardAction),
		$of("shift RIGHT"_s),
		$of($DefaultEditorKit::selectionForwardAction),
		$of("control LEFT"_s),
		$of($DefaultEditorKit::previousWordAction),
		$of("control RIGHT"_s),
		$of($DefaultEditorKit::nextWordAction),
		$of("control shift LEFT"_s),
		$of($DefaultEditorKit::selectionPreviousWordAction),
		$of("control shift RIGHT"_s),
		$of($DefaultEditorKit::selectionNextWordAction),
		$of("control SLASH"_s),
		$of($DefaultEditorKit::selectAllAction),
		$of("HOME"_s),
		$of($DefaultEditorKit::beginLineAction),
		$of("END"_s),
		$of($DefaultEditorKit::endLineAction),
		$of("shift HOME"_s),
		$of($DefaultEditorKit::selectionBeginLineAction),
		$of("shift END"_s),
		$of($DefaultEditorKit::selectionEndLineAction),
		$of("control BACK_SLASH"_s),
		$of("unselect"_s),
		$of("ENTER"_s),
		$of($JTextField::notifyAction),
		$of("control shift O"_s),
		$of("toggle-componentOrientation"_s)
	})));
	$var($Object, passwordInputMap, $new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
		$of("COPY"_s),
		$of($DefaultEditorKit::copyAction),
		$of("PASTE"_s),
		$of($DefaultEditorKit::pasteAction),
		$of("CUT"_s),
		$of($DefaultEditorKit::cutAction),
		$of("control INSERT"_s),
		$of($DefaultEditorKit::copyAction),
		$of("shift INSERT"_s),
		$of($DefaultEditorKit::pasteAction),
		$of("shift DELETE"_s),
		$of($DefaultEditorKit::cutAction),
		$of("control F"_s),
		$of($DefaultEditorKit::forwardAction),
		$of("control B"_s),
		$of($DefaultEditorKit::backwardAction),
		$of("control D"_s),
		$of($DefaultEditorKit::deleteNextCharAction),
		$of("BACK_SPACE"_s),
		$of($DefaultEditorKit::deletePrevCharAction),
		$of("shift BACK_SPACE"_s),
		$of($DefaultEditorKit::deletePrevCharAction),
		$of("ctrl H"_s),
		$of($DefaultEditorKit::deletePrevCharAction),
		$of("DELETE"_s),
		$of($DefaultEditorKit::deleteNextCharAction),
		$of("RIGHT"_s),
		$of($DefaultEditorKit::forwardAction),
		$of("LEFT"_s),
		$of($DefaultEditorKit::backwardAction),
		$of("KP_RIGHT"_s),
		$of($DefaultEditorKit::forwardAction),
		$of("KP_LEFT"_s),
		$of($DefaultEditorKit::backwardAction),
		$of("shift LEFT"_s),
		$of($DefaultEditorKit::selectionBackwardAction),
		$of("shift RIGHT"_s),
		$of($DefaultEditorKit::selectionForwardAction),
		$of("control LEFT"_s),
		$of($DefaultEditorKit::beginLineAction),
		$of("control RIGHT"_s),
		$of($DefaultEditorKit::endLineAction),
		$of("control shift LEFT"_s),
		$of($DefaultEditorKit::selectionBeginLineAction),
		$of("control shift RIGHT"_s),
		$of($DefaultEditorKit::selectionEndLineAction),
		$of("control SLASH"_s),
		$of($DefaultEditorKit::selectAllAction),
		$of("HOME"_s),
		$of($DefaultEditorKit::beginLineAction),
		$of("END"_s),
		$of($DefaultEditorKit::endLineAction),
		$of("shift HOME"_s),
		$of($DefaultEditorKit::selectionBeginLineAction),
		$of("shift END"_s),
		$of($DefaultEditorKit::selectionEndLineAction),
		$of("control BACK_SLASH"_s),
		$of("unselect"_s),
		$of("ENTER"_s),
		$of($JTextField::notifyAction),
		$of("control shift O"_s),
		$of("toggle-componentOrientation"_s)
	})));
	$var($Object, multilineInputMap, $new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
		$of("COPY"_s),
		$of($DefaultEditorKit::copyAction),
		$of("PASTE"_s),
		$of($DefaultEditorKit::pasteAction),
		$of("CUT"_s),
		$of($DefaultEditorKit::cutAction),
		$of("control INSERT"_s),
		$of($DefaultEditorKit::copyAction),
		$of("shift INSERT"_s),
		$of($DefaultEditorKit::pasteAction),
		$of("shift DELETE"_s),
		$of($DefaultEditorKit::cutAction),
		$of("control F"_s),
		$of($DefaultEditorKit::forwardAction),
		$of("control B"_s),
		$of($DefaultEditorKit::backwardAction),
		$of("control D"_s),
		$of($DefaultEditorKit::deleteNextCharAction),
		$of("BACK_SPACE"_s),
		$of($DefaultEditorKit::deletePrevCharAction),
		$of("shift BACK_SPACE"_s),
		$of($DefaultEditorKit::deletePrevCharAction),
		$of("ctrl H"_s),
		$of($DefaultEditorKit::deletePrevCharAction),
		$of("DELETE"_s),
		$of($DefaultEditorKit::deleteNextCharAction),
		$of("ctrl DELETE"_s),
		$of($DefaultEditorKit::deleteNextWordAction),
		$of("ctrl BACK_SPACE"_s),
		$of($DefaultEditorKit::deletePrevWordAction),
		$of("RIGHT"_s),
		$of($DefaultEditorKit::forwardAction),
		$of("LEFT"_s),
		$of($DefaultEditorKit::backwardAction),
		$of("KP_RIGHT"_s),
		$of($DefaultEditorKit::forwardAction),
		$of("KP_LEFT"_s),
		$of($DefaultEditorKit::backwardAction),
		$of("shift LEFT"_s),
		$of($DefaultEditorKit::selectionBackwardAction),
		$of("shift RIGHT"_s),
		$of($DefaultEditorKit::selectionForwardAction),
		$of("control LEFT"_s),
		$of($DefaultEditorKit::previousWordAction),
		$of("control RIGHT"_s),
		$of($DefaultEditorKit::nextWordAction),
		$of("control shift LEFT"_s),
		$of($DefaultEditorKit::selectionPreviousWordAction),
		$of("control shift RIGHT"_s),
		$of($DefaultEditorKit::selectionNextWordAction),
		$of("control SLASH"_s),
		$of($DefaultEditorKit::selectAllAction),
		$of("HOME"_s),
		$of($DefaultEditorKit::beginLineAction),
		$of("END"_s),
		$of($DefaultEditorKit::endLineAction),
		$of("shift HOME"_s),
		$of($DefaultEditorKit::selectionBeginLineAction),
		$of("shift END"_s),
		$of($DefaultEditorKit::selectionEndLineAction),
		$of("control N"_s),
		$of($DefaultEditorKit::downAction),
		$of("control P"_s),
		$of($DefaultEditorKit::upAction),
		$of("UP"_s),
		$of($DefaultEditorKit::upAction),
		$of("DOWN"_s),
		$of($DefaultEditorKit::downAction),
		$of("PAGE_UP"_s),
		$of($DefaultEditorKit::pageUpAction),
		$of("PAGE_DOWN"_s),
		$of($DefaultEditorKit::pageDownAction),
		$of("shift PAGE_UP"_s),
		$of("selection-page-up"_s),
		$of("shift PAGE_DOWN"_s),
		$of("selection-page-down"_s),
		$of("ctrl shift PAGE_UP"_s),
		$of("selection-page-left"_s),
		$of("ctrl shift PAGE_DOWN"_s),
		$of("selection-page-right"_s),
		$of("shift UP"_s),
		$of($DefaultEditorKit::selectionUpAction),
		$of("shift DOWN"_s),
		$of($DefaultEditorKit::selectionDownAction),
		$of("ENTER"_s),
		$of($DefaultEditorKit::insertBreakAction),
		$of("TAB"_s),
		$of($DefaultEditorKit::insertTabAction),
		$of("control BACK_SLASH"_s),
		$of("unselect"_s),
		$of("control HOME"_s),
		$of($DefaultEditorKit::beginAction),
		$of("control END"_s),
		$of($DefaultEditorKit::endAction),
		$of("control shift HOME"_s),
		$of($DefaultEditorKit::selectionBeginAction),
		$of("control shift END"_s),
		$of($DefaultEditorKit::selectionEndAction),
		$of("control T"_s),
		$of("next-link-action"_s),
		$of("control shift T"_s),
		$of("previous-link-action"_s),
		$of("control SPACE"_s),
		$of("activate-link-action"_s),
		$of("control shift O"_s),
		$of("toggle-componentOrientation"_s)
	})));
	$var($Object, treeOpenIcon, $SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/TreeOpen.gif"_s));
	$var($Object, treeClosedIcon, $SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/TreeClosed.gif"_s));
	$var($Object, treeLeafIcon, $new($MotifLookAndFeel$10, this));
	$var($Object, treeExpandedIcon, $new($MotifLookAndFeel$11, this));
	$var($Object, treeCollapsedIcon, $new($MotifLookAndFeel$12, this));
	$var($Color, var$13, $nc(table)->getColor("MenuBar.shadow"_s));
	$var($Color, var$14, table->getColor("MenuBar.highlight"_s));
	$var($Color, var$15, table->getColor("MenuBar.darkShadow"_s));
	$var($Border, menuBarBorder, $new($MotifBorders$MenuBarBorder, var$13, var$14, var$15, $(table->getColor("activeCaptionBorder"_s))));
	$var($Border, menuMarginBorder, $new($BorderUIResource$CompoundBorderUIResource, loweredBevelBorder, marginBorder));
	$var($Border, focusCellHighlightBorder, $new($BorderUIResource$LineBorderUIResource, $($nc(table)->getColor("activeCaptionBorder"_s))));
	$var($Object, sliderFocusInsets, $new($InsetsUIResource, 0, 0, 0, 0));
	$var($Object, tabbedPaneTabInsets, $new($InsetsUIResource, 3, 4, 3, 4));
	$var($Object, tabbedPaneTabPadInsets, $new($InsetsUIResource, 3, 0, 1, 0));
	$var($Object, tabbedPaneTabAreaInsets, $new($InsetsUIResource, 4, 2, 0, 8));
	$var($Object, tabbedPaneContentBorderInsets, $new($InsetsUIResource, 2, 2, 2, 2));
	$var($Object, optionPaneBorder, $new($BorderUIResource$EmptyBorderUIResource, 10, 0, 0, 0));
	$var($Object, optionPaneButtonAreaBorder, $new($BorderUIResource$EmptyBorderUIResource, 10, 10, 10, 10));
	$var($Object, optionPaneMessageAreaBorder, $new($BorderUIResource$EmptyBorderUIResource, 10, 10, 12, 10));
	int32_t metaMask = $KeyEvent::META_MASK;
	$init($Boolean);
	$var($ObjectArray, defaults, $new($ObjectArray, {
		$of("Desktop.background"_s),
		$($nc(table)->get("desktop"_s)),
		$of("Desktop.ancestorInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("ctrl F5"_s),
			$of("restore"_s),
			$of("ctrl F4"_s),
			$of("close"_s),
			$of("ctrl F7"_s),
			$of("move"_s),
			$of("ctrl F8"_s),
			$of("resize"_s),
			$of("RIGHT"_s),
			$of("right"_s),
			$of("KP_RIGHT"_s),
			$of("right"_s),
			$of("shift RIGHT"_s),
			$of("shrinkRight"_s),
			$of("shift KP_RIGHT"_s),
			$of("shrinkRight"_s),
			$of("LEFT"_s),
			$of("left"_s),
			$of("KP_LEFT"_s),
			$of("left"_s),
			$of("shift LEFT"_s),
			$of("shrinkLeft"_s),
			$of("shift KP_LEFT"_s),
			$of("shrinkLeft"_s),
			$of("UP"_s),
			$of("up"_s),
			$of("KP_UP"_s),
			$of("up"_s),
			$of("shift UP"_s),
			$of("shrinkUp"_s),
			$of("shift KP_UP"_s),
			$of("shrinkUp"_s),
			$of("DOWN"_s),
			$of("down"_s),
			$of("KP_DOWN"_s),
			$of("down"_s),
			$of("shift DOWN"_s),
			$of("shrinkDown"_s),
			$of("shift KP_DOWN"_s),
			$of("shrinkDown"_s),
			$of("ESCAPE"_s),
			$of("escape"_s),
			$of("ctrl F9"_s),
			$of("minimize"_s),
			$of("ctrl F10"_s),
			$of("maximize"_s),
			$of("ctrl F6"_s),
			$of("selectNextFrame"_s),
			$of("ctrl TAB"_s),
			$of("selectNextFrame"_s),
			$of("ctrl alt F6"_s),
			$of("selectNextFrame"_s),
			$of("shift ctrl alt F6"_s),
			$of("selectPreviousFrame"_s),
			$of("ctrl F12"_s),
			$of("navigateNext"_s),
			$of("shift ctrl F12"_s),
			$of("navigatePrevious"_s)
		}))),
		$of("Panel.background"_s),
		$(table->get("control"_s)),
		$of("Panel.foreground"_s),
		$(table->get("textText"_s)),
		$of("Panel.font"_s),
		$of(dialogPlain12),
		$of("ProgressBar.font"_s),
		$of(dialogPlain12),
		$of("ProgressBar.foreground"_s),
		$of(controlDarker),
		$of("ProgressBar.background"_s),
		$(table->get("control"_s)),
		$of("ProgressBar.selectionForeground"_s),
		$(table->get("control"_s)),
		$of("ProgressBar.selectionBackground"_s),
		$(table->get("controlText"_s)),
		$of("ProgressBar.border"_s),
		$of(loweredBevelBorder),
		$of("ProgressBar.cellLength"_s),
		$($of($Integer::valueOf(6))),
		$of("ProgressBar.cellSpacing"_s),
		$($of($Integer::valueOf(0))),
		$of("Button.margin"_s),
		$of($$new($InsetsUIResource, 2, 4, 2, 4)),
		$of("Button.border"_s),
		$of(buttonBorder),
		$of("Button.background"_s),
		$(table->get("control"_s)),
		$of("Button.foreground"_s),
		$(table->get("controlText"_s)),
		$of("Button.select"_s),
		$(table->get("controlLightShadow"_s)),
		$of("Button.font"_s),
		$of(dialogPlain12),
		$of("Button.focusInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("SPACE"_s),
			$of("pressed"_s),
			$of("released SPACE"_s),
			$of("released"_s)
		}))),
		$of("CheckBox.textIconGap"_s),
		$($of($Integer::valueOf(8))),
		$of("CheckBox.margin"_s),
		$of($$new($InsetsUIResource, 4, 2, 4, 2)),
		$of("CheckBox.icon"_s),
		checkBoxIcon,
		$of("CheckBox.focus"_s),
		$(table->get("activeCaptionBorder"_s)),
		$of("CheckBox.focusInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("SPACE"_s),
			$of("pressed"_s),
			$of("released SPACE"_s),
			$of("released"_s)
		}))),
		$of("RadioButton.margin"_s),
		$of($$new($InsetsUIResource, 4, 2, 4, 2)),
		$of("RadioButton.textIconGap"_s),
		$($of($Integer::valueOf(8))),
		$of("RadioButton.background"_s),
		$(table->get("control"_s)),
		$of("RadioButton.foreground"_s),
		$(table->get("controlText"_s)),
		$of("RadioButton.icon"_s),
		radioButtonIcon,
		$of("RadioButton.focus"_s),
		$(table->get("activeCaptionBorder"_s)),
		$of("RadioButton.icon"_s),
		radioButtonIcon,
		$of("RadioButton.focusInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("SPACE"_s),
			$of("pressed"_s),
			$of("released SPACE"_s),
			$of("released"_s)
		}))),
		$of("ToggleButton.border"_s),
		$of(toggleButtonBorder),
		$of("ToggleButton.background"_s),
		$(table->get("control"_s)),
		$of("ToggleButton.foreground"_s),
		$(table->get("controlText"_s)),
		$of("ToggleButton.focus"_s),
		$(table->get("controlText"_s)),
		$of("ToggleButton.select"_s),
		$(table->get("controlLightShadow"_s)),
		$of("ToggleButton.focusInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("SPACE"_s),
			$of("pressed"_s),
			$of("released SPACE"_s),
			$of("released"_s)
		}))),
		$of("Menu.border"_s),
		$of(menuMarginBorder),
		$of("Menu.font"_s),
		$of(dialogPlain12),
		$of("Menu.acceleratorFont"_s),
		$of(dialogPlain12),
		$of("Menu.acceleratorSelectionForeground"_s),
		$of(menuItemPressedForeground),
		$of("Menu.foreground"_s),
		$(table->get("menuText"_s)),
		$of("Menu.background"_s),
		$(table->get("menu"_s)),
		$of("Menu.selectionForeground"_s),
		$of(menuItemPressedForeground),
		$of("Menu.selectionBackground"_s),
		$of(menuItemPressedBackground),
		$of("Menu.checkIcon"_s),
		menuItemCheckIcon,
		$of("Menu.arrowIcon"_s),
		menuArrowIcon,
		$of("Menu.menuPopupOffsetX"_s),
		$($of($Integer::valueOf(0))),
		$of("Menu.menuPopupOffsetY"_s),
		$($of($Integer::valueOf(0))),
		$of("Menu.submenuPopupOffsetX"_s),
		$($of($Integer::valueOf(-2))),
		$of("Menu.submenuPopupOffsetY"_s),
		$($of($Integer::valueOf(3))),
		$of("Menu.shortcutKeys"_s),
		$of($$new($ints, {
			$SwingUtilities2::getSystemMnemonicKeyMask(),
			metaMask,
			$SwingUtilities2::setAltGraphMask($SwingUtilities2::getSystemMnemonicKeyMask())
		})),
		$of("Menu.cancelMode"_s),
		$of("hideMenuTree"_s),
		$of("MenuBar.border"_s),
		$of(menuBarBorder),
		$of("MenuBar.background"_s),
		$(table->get("menu"_s)),
		$of("MenuBar.foreground"_s),
		$(table->get("menuText"_s)),
		$of("MenuBar.font"_s),
		$of(dialogPlain12),
		$of("MenuBar.windowBindings"_s),
		$of($$new($ObjectArray, {
			$of("F10"_s),
			$of("takeFocus"_s)
		})),
		$of("MenuItem.border"_s),
		$of(menuMarginBorder),
		$of("MenuItem.font"_s),
		$of(dialogPlain12),
		$of("MenuItem.acceleratorFont"_s),
		$of(dialogPlain12),
		$of("MenuItem.acceleratorSelectionForeground"_s),
		$of(menuItemPressedForeground),
		$of("MenuItem.foreground"_s),
		$(table->get("menuText"_s)),
		$of("MenuItem.background"_s),
		$(table->get("menu"_s)),
		$of("MenuItem.selectionForeground"_s),
		$of(menuItemPressedForeground),
		$of("MenuItem.selectionBackground"_s),
		$of(menuItemPressedBackground),
		$of("MenuItem.checkIcon"_s),
		menuItemCheckIcon,
		$of("MenuItem.arrowIcon"_s),
		menuItemArrowIcon,
		$of("RadioButtonMenuItem.border"_s),
		$of(menuMarginBorder),
		$of("RadioButtonMenuItem.font"_s),
		$of(dialogPlain12),
		$of("RadioButtonMenuItem.acceleratorFont"_s),
		$of(dialogPlain12),
		$of("RadioButtonMenuItem.acceleratorSelectionForeground"_s),
		$of(menuItemPressedForeground),
		$of("RadioButtonMenuItem.foreground"_s),
		$(table->get("menuText"_s)),
		$of("RadioButtonMenuItem.background"_s),
		$(table->get("menu"_s)),
		$of("RadioButtonMenuItem.selectionForeground"_s),
		$of(menuItemPressedForeground),
		$of("RadioButtonMenuItem.selectionBackground"_s),
		$of(menuItemPressedBackground),
		$of("RadioButtonMenuItem.checkIcon"_s),
		radioButtonIcon,
		$of("RadioButtonMenuItem.arrowIcon"_s),
		menuItemArrowIcon,
		$of("CheckBoxMenuItem.border"_s),
		$of(menuMarginBorder),
		$of("CheckBoxMenuItem.font"_s),
		$of(dialogPlain12),
		$of("CheckBoxMenuItem.acceleratorFont"_s),
		$of(dialogPlain12),
		$of("CheckBoxMenuItem.acceleratorSelectionForeground"_s),
		$of(menuItemPressedForeground),
		$of("CheckBoxMenuItem.foreground"_s),
		$(table->get("menuText"_s)),
		$of("CheckBoxMenuItem.background"_s),
		$(table->get("menu"_s)),
		$of("CheckBoxMenuItem.selectionForeground"_s),
		$of(menuItemPressedForeground),
		$of("CheckBoxMenuItem.selectionBackground"_s),
		$of(menuItemPressedBackground),
		$of("CheckBoxMenuItem.checkIcon"_s),
		checkBoxIcon,
		$of("CheckBoxMenuItem.arrowIcon"_s),
		menuItemArrowIcon,
		$of("PopupMenu.background"_s),
		$(table->get("menu"_s)),
		$of("PopupMenu.border"_s),
		$of(popupMenuBorder),
		$of("PopupMenu.foreground"_s),
		$(table->get("menuText"_s)),
		$of("PopupMenu.font"_s),
		$of(dialogPlain12),
		$of("PopupMenu.consumeEventOnClose"_s),
		$of($Boolean::FALSE),
		$of("Label.font"_s),
		$of(dialogPlain12),
		$of("Label.background"_s),
		$(table->get("control"_s)),
		$of("Label.foreground"_s),
		$(table->get("controlText"_s)),
		$of("Separator.shadow"_s),
		$(table->get("controlShadow"_s)),
		$of("Separator.highlight"_s),
		$(table->get("controlLtHighlight"_s)),
		$of("Separator.background"_s),
		$(table->get("controlLtHighlight"_s)),
		$of("Separator.foreground"_s),
		$(table->get("controlShadow"_s)),
		$of("List.focusCellHighlightBorder"_s),
		$of(focusCellHighlightBorder),
		$of("List.focusInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("COPY"_s),
			$of("copy"_s),
			$of("PASTE"_s),
			$of("paste"_s),
			$of("CUT"_s),
			$of("cut"_s),
			$of("control INSERT"_s),
			$of("copy"_s),
			$of("shift INSERT"_s),
			$of("paste"_s),
			$of("shift DELETE"_s),
			$of("cut"_s),
			$of("UP"_s),
			$of("selectPreviousRow"_s),
			$of("KP_UP"_s),
			$of("selectPreviousRow"_s),
			$of("shift UP"_s),
			$of("selectPreviousRowExtendSelection"_s),
			$of("shift KP_UP"_s),
			$of("selectPreviousRowExtendSelection"_s),
			$of("ctrl shift UP"_s),
			$of("selectPreviousRowExtendSelection"_s),
			$of("ctrl shift KP_UP"_s),
			$of("selectPreviousRowExtendSelection"_s),
			$of("ctrl UP"_s),
			$of("selectPreviousRowChangeLead"_s),
			$of("ctrl KP_UP"_s),
			$of("selectPreviousRowChangeLead"_s),
			$of("DOWN"_s),
			$of("selectNextRow"_s),
			$of("KP_DOWN"_s),
			$of("selectNextRow"_s),
			$of("shift DOWN"_s),
			$of("selectNextRowExtendSelection"_s),
			$of("shift KP_DOWN"_s),
			$of("selectNextRowExtendSelection"_s),
			$of("ctrl shift DOWN"_s),
			$of("selectNextRowExtendSelection"_s),
			$of("ctrl shift KP_DOWN"_s),
			$of("selectNextRowExtendSelection"_s),
			$of("ctrl DOWN"_s),
			$of("selectNextRowChangeLead"_s),
			$of("ctrl KP_DOWN"_s),
			$of("selectNextRowChangeLead"_s),
			$of("LEFT"_s),
			$of("selectPreviousColumn"_s),
			$of("KP_LEFT"_s),
			$of("selectPreviousColumn"_s),
			$of("shift LEFT"_s),
			$of("selectPreviousColumnExtendSelection"_s),
			$of("shift KP_LEFT"_s),
			$of("selectPreviousColumnExtendSelection"_s),
			$of("ctrl shift LEFT"_s),
			$of("selectPreviousColumnExtendSelection"_s),
			$of("ctrl shift KP_LEFT"_s),
			$of("selectPreviousColumnExtendSelection"_s),
			$of("ctrl LEFT"_s),
			$of("selectPreviousColumnChangeLead"_s),
			$of("ctrl KP_LEFT"_s),
			$of("selectPreviousColumnChangeLead"_s),
			$of("RIGHT"_s),
			$of("selectNextColumn"_s),
			$of("KP_RIGHT"_s),
			$of("selectNextColumn"_s),
			$of("shift RIGHT"_s),
			$of("selectNextColumnExtendSelection"_s),
			$of("shift KP_RIGHT"_s),
			$of("selectNextColumnExtendSelection"_s),
			$of("ctrl shift RIGHT"_s),
			$of("selectNextColumnExtendSelection"_s),
			$of("ctrl shift KP_RIGHT"_s),
			$of("selectNextColumnExtendSelection"_s),
			$of("ctrl RIGHT"_s),
			$of("selectNextColumnChangeLead"_s),
			$of("ctrl KP_RIGHT"_s),
			$of("selectNextColumnChangeLead"_s),
			$of("HOME"_s),
			$of("selectFirstRow"_s),
			$of("shift HOME"_s),
			$of("selectFirstRowExtendSelection"_s),
			$of("ctrl shift HOME"_s),
			$of("selectFirstRowExtendSelection"_s),
			$of("ctrl HOME"_s),
			$of("selectFirstRowChangeLead"_s),
			$of("END"_s),
			$of("selectLastRow"_s),
			$of("shift END"_s),
			$of("selectLastRowExtendSelection"_s),
			$of("ctrl shift END"_s),
			$of("selectLastRowExtendSelection"_s),
			$of("ctrl END"_s),
			$of("selectLastRowChangeLead"_s),
			$of("PAGE_UP"_s),
			$of("scrollUp"_s),
			$of("shift PAGE_UP"_s),
			$of("scrollUpExtendSelection"_s),
			$of("ctrl shift PAGE_UP"_s),
			$of("scrollUpExtendSelection"_s),
			$of("ctrl PAGE_UP"_s),
			$of("scrollUpChangeLead"_s),
			$of("PAGE_DOWN"_s),
			$of("scrollDown"_s),
			$of("shift PAGE_DOWN"_s),
			$of("scrollDownExtendSelection"_s),
			$of("ctrl shift PAGE_DOWN"_s),
			$of("scrollDownExtendSelection"_s),
			$of("ctrl PAGE_DOWN"_s),
			$of("scrollDownChangeLead"_s),
			$of("ctrl A"_s),
			$of("selectAll"_s),
			$of("ctrl SLASH"_s),
			$of("selectAll"_s),
			$of("ctrl BACK_SLASH"_s),
			$of("clearSelection"_s),
			$of("SPACE"_s),
			$of("addToSelection"_s),
			$of("ctrl SPACE"_s),
			$of("toggleAndAnchor"_s),
			$of("shift SPACE"_s),
			$of("extendTo"_s),
			$of("ctrl shift SPACE"_s),
			$of("moveSelectionTo"_s)
		}))),
		$of("DesktopIcon.icon"_s),
		$($SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/DesktopIcon.gif"_s)),
		$of("DesktopIcon.border"_s),
		($Object*)nullptr,
		$of("DesktopIcon.windowBindings"_s),
		$of($$new($ObjectArray, {
			$of("ESCAPE"_s),
			$of("hideSystemMenu"_s)
		})),
		$of("InternalFrame.activeTitleBackground"_s),
		$(table->get("activeCaptionBorder"_s)),
		$of("InternalFrame.inactiveTitleBackground"_s),
		$(table->get("inactiveCaptionBorder"_s)),
		$of("InternalFrame.windowBindings"_s),
		$of($$new($ObjectArray, {
			$of("shift ESCAPE"_s),
			$of("showSystemMenu"_s),
			$of("ctrl SPACE"_s),
			$of("showSystemMenu"_s),
			$of("ESCAPE"_s),
			$of("hideSystemMenu"_s)
		})),
		$of("ScrollBar.background"_s),
		$of(scrollBarTrack),
		$of("ScrollBar.foreground"_s),
		$(table->get("control"_s)),
		$of("ScrollBar.track"_s),
		$of(scrollBarTrack),
		$of("ScrollBar.trackHighlight"_s),
		$(table->get("controlDkShadow"_s)),
		$of("ScrollBar.thumb"_s),
		$(table->get("control"_s)),
		$of("ScrollBar.thumbHighlight"_s),
		$(table->get("controlHighlight"_s)),
		$of("ScrollBar.thumbDarkShadow"_s),
		$(table->get("controlDkShadow"_s)),
		$of("ScrollBar.thumbShadow"_s),
		$(table->get("controlShadow"_s)),
		$of("ScrollBar.border"_s),
		$of(loweredBevelBorder),
		$of("ScrollBar.allowsAbsolutePositioning"_s),
		$of($Boolean::TRUE),
		$of("ScrollBar.ancestorInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("RIGHT"_s),
			$of("positiveUnitIncrement"_s),
			$of("KP_RIGHT"_s),
			$of("positiveUnitIncrement"_s),
			$of("DOWN"_s),
			$of("positiveUnitIncrement"_s),
			$of("KP_DOWN"_s),
			$of("positiveUnitIncrement"_s),
			$of("PAGE_DOWN"_s),
			$of("positiveBlockIncrement"_s),
			$of("ctrl PAGE_DOWN"_s),
			$of("positiveBlockIncrement"_s),
			$of("LEFT"_s),
			$of("negativeUnitIncrement"_s),
			$of("KP_LEFT"_s),
			$of("negativeUnitIncrement"_s),
			$of("UP"_s),
			$of("negativeUnitIncrement"_s),
			$of("KP_UP"_s),
			$of("negativeUnitIncrement"_s),
			$of("PAGE_UP"_s),
			$of("negativeBlockIncrement"_s),
			$of("ctrl PAGE_UP"_s),
			$of("negativeBlockIncrement"_s),
			$of("HOME"_s),
			$of("minScroll"_s),
			$of("END"_s),
			$of("maxScroll"_s)
		}))),
		$of("ScrollPane.font"_s),
		$of(dialogPlain12),
		$of("ScrollPane.background"_s),
		$(table->get("control"_s)),
		$of("ScrollPane.foreground"_s),
		$(table->get("controlText"_s)),
		$of("ScrollPane.border"_s),
		($Object*)nullptr,
		$of("ScrollPane.viewportBorder"_s),
		$of(loweredBevelBorder),
		$of("ScrollPane.ancestorInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("RIGHT"_s),
			$of("unitScrollRight"_s),
			$of("KP_RIGHT"_s),
			$of("unitScrollRight"_s),
			$of("DOWN"_s),
			$of("unitScrollDown"_s),
			$of("KP_DOWN"_s),
			$of("unitScrollDown"_s),
			$of("LEFT"_s),
			$of("unitScrollLeft"_s),
			$of("KP_LEFT"_s),
			$of("unitScrollLeft"_s),
			$of("UP"_s),
			$of("unitScrollUp"_s),
			$of("KP_UP"_s),
			$of("unitScrollUp"_s),
			$of("PAGE_UP"_s),
			$of("scrollUp"_s),
			$of("PAGE_DOWN"_s),
			$of("scrollDown"_s),
			$of("ctrl PAGE_UP"_s),
			$of("scrollLeft"_s),
			$of("ctrl PAGE_DOWN"_s),
			$of("scrollRight"_s),
			$of("ctrl HOME"_s),
			$of("scrollHome"_s),
			$of("ctrl END"_s),
			$of("scrollEnd"_s)
		}))),
		$of("Slider.font"_s),
		$of(dialogPlain12),
		$of("Slider.border"_s),
		$of(focusBevelBorder),
		$of("Slider.foreground"_s),
		$(table->get("control"_s)),
		$of("Slider.background"_s),
		$of(controlDarker),
		$of("Slider.highlight"_s),
		$(table->get("controlHighlight"_s)),
		$of("Slider.shadow"_s),
		$(table->get("controlShadow"_s)),
		$of("Slider.focus"_s),
		$(table->get("controlDkShadow"_s)),
		$of("Slider.focusInsets"_s),
		sliderFocusInsets,
		$of("Slider.focusInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("RIGHT"_s),
			$of("positiveUnitIncrement"_s),
			$of("KP_RIGHT"_s),
			$of("positiveUnitIncrement"_s),
			$of("DOWN"_s),
			$of("negativeUnitIncrement"_s),
			$of("KP_DOWN"_s),
			$of("negativeUnitIncrement"_s),
			$of("ctrl PAGE_DOWN"_s),
			$of("negativeBlockIncrement"_s),
			$of("LEFT"_s),
			$of("negativeUnitIncrement"_s),
			$of("KP_LEFT"_s),
			$of("negativeUnitIncrement"_s),
			$of("UP"_s),
			$of("positiveUnitIncrement"_s),
			$of("KP_UP"_s),
			$of("positiveUnitIncrement"_s),
			$of("ctrl PAGE_UP"_s),
			$of("positiveBlockIncrement"_s),
			$of("HOME"_s),
			$of("minScroll"_s),
			$of("END"_s),
			$of("maxScroll"_s)
		}))),
		$of("Spinner.ancestorInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("UP"_s),
			$of("increment"_s),
			$of("KP_UP"_s),
			$of("increment"_s),
			$of("DOWN"_s),
			$of("decrement"_s),
			$of("KP_DOWN"_s),
			$of("decrement"_s)
		}))),
		$of("Spinner.border"_s),
		$of(textFieldBorder),
		$of("SplitPane.background"_s),
		$(table->get("control"_s)),
		$of("SplitPane.highlight"_s),
		$(table->get("controlHighlight"_s)),
		$of("SplitPane.shadow"_s),
		$(table->get("controlShadow"_s)),
		$of("SplitPane.dividerSize"_s),
		$($of($Integer::valueOf(20))),
		$of("SplitPane.activeThumb"_s),
		$(table->get("activeCaptionBorder"_s)),
		$of("SplitPane.ancestorInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("UP"_s),
			$of("negativeIncrement"_s),
			$of("DOWN"_s),
			$of("positiveIncrement"_s),
			$of("LEFT"_s),
			$of("negativeIncrement"_s),
			$of("RIGHT"_s),
			$of("positiveIncrement"_s),
			$of("KP_UP"_s),
			$of("negativeIncrement"_s),
			$of("KP_DOWN"_s),
			$of("positiveIncrement"_s),
			$of("KP_LEFT"_s),
			$of("negativeIncrement"_s),
			$of("KP_RIGHT"_s),
			$of("positiveIncrement"_s),
			$of("HOME"_s),
			$of("selectMin"_s),
			$of("END"_s),
			$of("selectMax"_s),
			$of("F8"_s),
			$of("startResize"_s),
			$of("F6"_s),
			$of("toggleFocus"_s),
			$of("ctrl TAB"_s),
			$of("focusOutForward"_s),
			$of("ctrl shift TAB"_s),
			$of("focusOutBackward"_s)
		}))),
		$of("TabbedPane.font"_s),
		$of(dialogPlain12),
		$of("TabbedPane.background"_s),
		$(table->get("control"_s)),
		$of("TabbedPane.foreground"_s),
		$(table->get("controlText"_s)),
		$of("TabbedPane.light"_s),
		$(table->get("controlHighlight"_s)),
		$of("TabbedPane.highlight"_s),
		$(table->get("controlLtHighlight"_s)),
		$of("TabbedPane.shadow"_s),
		$(table->get("controlShadow"_s)),
		$of("TabbedPane.darkShadow"_s),
		$(table->get("controlShadow"_s)),
		$of("TabbedPane.unselectedTabBackground"_s),
		unselectedTabBackground,
		$of("TabbedPane.unselectedTabForeground"_s),
		unselectedTabForeground,
		$of("TabbedPane.unselectedTabHighlight"_s),
		unselectedTabHighlight,
		$of("TabbedPane.unselectedTabShadow"_s),
		unselectedTabShadow,
		$of("TabbedPane.focus"_s),
		$(table->get("activeCaptionBorder"_s)),
		$of("TabbedPane.tabInsets"_s),
		tabbedPaneTabInsets,
		$of("TabbedPane.selectedTabPadInsets"_s),
		tabbedPaneTabPadInsets,
		$of("TabbedPane.tabAreaInsets"_s),
		tabbedPaneTabAreaInsets,
		$of("TabbedPane.contentBorderInsets"_s),
		tabbedPaneContentBorderInsets,
		$of("TabbedPane.focusInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("RIGHT"_s),
			$of("navigateRight"_s),
			$of("KP_RIGHT"_s),
			$of("navigateRight"_s),
			$of("LEFT"_s),
			$of("navigateLeft"_s),
			$of("KP_LEFT"_s),
			$of("navigateLeft"_s),
			$of("UP"_s),
			$of("navigateUp"_s),
			$of("KP_UP"_s),
			$of("navigateUp"_s),
			$of("DOWN"_s),
			$of("navigateDown"_s),
			$of("KP_DOWN"_s),
			$of("navigateDown"_s),
			$of("ctrl DOWN"_s),
			$of("requestFocusForVisibleComponent"_s),
			$of("ctrl KP_DOWN"_s),
			$of("requestFocusForVisibleComponent"_s)
		}))),
		$of("TabbedPane.ancestorInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("ctrl PAGE_DOWN"_s),
			$of("navigatePageDown"_s),
			$of("ctrl PAGE_UP"_s),
			$of("navigatePageUp"_s),
			$of("ctrl UP"_s),
			$of("requestFocus"_s),
			$of("ctrl KP_UP"_s),
			$of("requestFocus"_s)
		}))),
		$of("Tree.background"_s),
		$of(controlDarker),
		$of("Tree.hash"_s),
		$(table->get("controlDkShadow"_s)),
		$of("Tree.iconShadow"_s),
		$(table->get("controlShadow"_s)),
		$of("Tree.iconHighlight"_s),
		$(table->get("controlHighlight"_s)),
		$of("Tree.iconBackground"_s),
		$(table->get("control"_s)),
		$of("Tree.iconForeground"_s),
		$(table->get("controlShadow"_s)),
		$of("Tree.textBackground"_s),
		$of(controlDarker),
		$of("Tree.textForeground"_s),
		$(table->get("textText"_s)),
		$of("Tree.selectionBackground"_s),
		$(table->get("text"_s)),
		$of("Tree.selectionForeground"_s),
		$(table->get("textText"_s)),
		$of("Tree.selectionBorderColor"_s),
		$(table->get("activeCaptionBorder"_s)),
		$of("Tree.openIcon"_s),
		treeOpenIcon,
		$of("Tree.closedIcon"_s),
		treeClosedIcon,
		$of("Tree.leafIcon"_s),
		treeLeafIcon,
		$of("Tree.expandedIcon"_s),
		treeExpandedIcon,
		$of("Tree.collapsedIcon"_s),
		treeCollapsedIcon,
		$of("Tree.editorBorder"_s),
		$of(focusBorder),
		$of("Tree.editorBorderSelectionColor"_s),
		$(table->get("activeCaptionBorder"_s)),
		$of("Tree.rowHeight"_s),
		$($of($Integer::valueOf(18))),
		$of("Tree.drawsFocusBorderAroundIcon"_s),
		$of($Boolean::TRUE),
		$of("Tree.focusInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("COPY"_s),
			$of("copy"_s),
			$of("PASTE"_s),
			$of("paste"_s),
			$of("CUT"_s),
			$of("cut"_s),
			$of("control INSERT"_s),
			$of("copy"_s),
			$of("shift INSERT"_s),
			$of("paste"_s),
			$of("shift DELETE"_s),
			$of("cut"_s),
			$of("UP"_s),
			$of("selectPrevious"_s),
			$of("KP_UP"_s),
			$of("selectPrevious"_s),
			$of("shift UP"_s),
			$of("selectPreviousExtendSelection"_s),
			$of("shift KP_UP"_s),
			$of("selectPreviousExtendSelection"_s),
			$of("ctrl shift UP"_s),
			$of("selectPreviousExtendSelection"_s),
			$of("ctrl shift KP_UP"_s),
			$of("selectPreviousExtendSelection"_s),
			$of("ctrl UP"_s),
			$of("selectPreviousChangeLead"_s),
			$of("ctrl KP_UP"_s),
			$of("selectPreviousChangeLead"_s),
			$of("DOWN"_s),
			$of("selectNext"_s),
			$of("KP_DOWN"_s),
			$of("selectNext"_s),
			$of("shift DOWN"_s),
			$of("selectNextExtendSelection"_s),
			$of("shift KP_DOWN"_s),
			$of("selectNextExtendSelection"_s),
			$of("ctrl shift DOWN"_s),
			$of("selectNextExtendSelection"_s),
			$of("ctrl shift KP_DOWN"_s),
			$of("selectNextExtendSelection"_s),
			$of("ctrl DOWN"_s),
			$of("selectNextChangeLead"_s),
			$of("ctrl KP_DOWN"_s),
			$of("selectNextChangeLead"_s),
			$of("RIGHT"_s),
			$of("selectChild"_s),
			$of("KP_RIGHT"_s),
			$of("selectChild"_s),
			$of("LEFT"_s),
			$of("selectParent"_s),
			$of("KP_LEFT"_s),
			$of("selectParent"_s),
			$of("PAGE_UP"_s),
			$of("scrollUpChangeSelection"_s),
			$of("shift PAGE_UP"_s),
			$of("scrollUpExtendSelection"_s),
			$of("ctrl shift PAGE_UP"_s),
			$of("scrollUpExtendSelection"_s),
			$of("ctrl PAGE_UP"_s),
			$of("scrollUpChangeLead"_s),
			$of("PAGE_DOWN"_s),
			$of("scrollDownChangeSelection"_s),
			$of("shift PAGE_DOWN"_s),
			$of("scrollDownExtendSelection"_s),
			$of("ctrl shift PAGE_DOWN"_s),
			$of("scrollDownExtendSelection"_s),
			$of("ctrl PAGE_DOWN"_s),
			$of("scrollDownChangeLead"_s),
			$of("HOME"_s),
			$of("selectFirst"_s),
			$of("shift HOME"_s),
			$of("selectFirstExtendSelection"_s),
			$of("ctrl shift HOME"_s),
			$of("selectFirstExtendSelection"_s),
			$of("ctrl HOME"_s),
			$of("selectFirstChangeLead"_s),
			$of("END"_s),
			$of("selectLast"_s),
			$of("shift END"_s),
			$of("selectLastExtendSelection"_s),
			$of("ctrl shift END"_s),
			$of("selectLastExtendSelection"_s),
			$of("ctrl END"_s),
			$of("selectLastChangeLead"_s),
			$of("F2"_s),
			$of("startEditing"_s),
			$of("ctrl A"_s),
			$of("selectAll"_s),
			$of("ctrl SLASH"_s),
			$of("selectAll"_s),
			$of("ctrl BACK_SLASH"_s),
			$of("clearSelection"_s),
			$of("ctrl LEFT"_s),
			$of("scrollLeft"_s),
			$of("ctrl KP_LEFT"_s),
			$of("scrollLeft"_s),
			$of("ctrl RIGHT"_s),
			$of("scrollRight"_s),
			$of("ctrl KP_RIGHT"_s),
			$of("scrollRight"_s),
			$of("SPACE"_s),
			$of("addToSelection"_s),
			$of("ctrl SPACE"_s),
			$of("toggleAndAnchor"_s),
			$of("shift SPACE"_s),
			$of("extendTo"_s),
			$of("ctrl shift SPACE"_s),
			$of("moveSelectionTo"_s)
		}))),
		$of("Tree.ancestorInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("ESCAPE"_s),
			$of("cancel"_s)
		}))),
		$of("Table.focusCellHighlightBorder"_s),
		$of(focusCellHighlightBorder),
		$of("Table.scrollPaneBorder"_s),
		($Object*)nullptr,
		$of("Table.dropLineShortColor"_s),
		$(table->get("activeCaptionBorder"_s)),
		$of("Table.ancestorInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("COPY"_s),
			$of("copy"_s),
			$of("PASTE"_s),
			$of("paste"_s),
			$of("CUT"_s),
			$of("cut"_s),
			$of("control INSERT"_s),
			$of("copy"_s),
			$of("shift INSERT"_s),
			$of("paste"_s),
			$of("shift DELETE"_s),
			$of("cut"_s),
			$of("RIGHT"_s),
			$of("selectNextColumn"_s),
			$of("KP_RIGHT"_s),
			$of("selectNextColumn"_s),
			$of("shift RIGHT"_s),
			$of("selectNextColumnExtendSelection"_s),
			$of("shift KP_RIGHT"_s),
			$of("selectNextColumnExtendSelection"_s),
			$of("ctrl shift RIGHT"_s),
			$of("selectNextColumnExtendSelection"_s),
			$of("ctrl shift KP_RIGHT"_s),
			$of("selectNextColumnExtendSelection"_s),
			$of("ctrl RIGHT"_s),
			$of("selectNextColumnChangeLead"_s),
			$of("ctrl KP_RIGHT"_s),
			$of("selectNextColumnChangeLead"_s),
			$of("LEFT"_s),
			$of("selectPreviousColumn"_s),
			$of("KP_LEFT"_s),
			$of("selectPreviousColumn"_s),
			$of("shift LEFT"_s),
			$of("selectPreviousColumnExtendSelection"_s),
			$of("shift KP_LEFT"_s),
			$of("selectPreviousColumnExtendSelection"_s),
			$of("ctrl shift LEFT"_s),
			$of("selectPreviousColumnExtendSelection"_s),
			$of("ctrl shift KP_LEFT"_s),
			$of("selectPreviousColumnExtendSelection"_s),
			$of("ctrl LEFT"_s),
			$of("selectPreviousColumnChangeLead"_s),
			$of("ctrl KP_LEFT"_s),
			$of("selectPreviousColumnChangeLead"_s),
			$of("DOWN"_s),
			$of("selectNextRow"_s),
			$of("KP_DOWN"_s),
			$of("selectNextRow"_s),
			$of("shift DOWN"_s),
			$of("selectNextRowExtendSelection"_s),
			$of("shift KP_DOWN"_s),
			$of("selectNextRowExtendSelection"_s),
			$of("ctrl shift DOWN"_s),
			$of("selectNextRowExtendSelection"_s),
			$of("ctrl shift KP_DOWN"_s),
			$of("selectNextRowExtendSelection"_s),
			$of("ctrl DOWN"_s),
			$of("selectNextRowChangeLead"_s),
			$of("ctrl KP_DOWN"_s),
			$of("selectNextRowChangeLead"_s),
			$of("UP"_s),
			$of("selectPreviousRow"_s),
			$of("KP_UP"_s),
			$of("selectPreviousRow"_s),
			$of("shift UP"_s),
			$of("selectPreviousRowExtendSelection"_s),
			$of("shift KP_UP"_s),
			$of("selectPreviousRowExtendSelection"_s),
			$of("ctrl shift UP"_s),
			$of("selectPreviousRowExtendSelection"_s),
			$of("ctrl shift KP_UP"_s),
			$of("selectPreviousRowExtendSelection"_s),
			$of("ctrl UP"_s),
			$of("selectPreviousRowChangeLead"_s),
			$of("ctrl KP_UP"_s),
			$of("selectPreviousRowChangeLead"_s),
			$of("HOME"_s),
			$of("selectFirstColumn"_s),
			$of("shift HOME"_s),
			$of("selectFirstColumnExtendSelection"_s),
			$of("ctrl shift HOME"_s),
			$of("selectFirstRowExtendSelection"_s),
			$of("ctrl HOME"_s),
			$of("selectFirstRow"_s),
			$of("END"_s),
			$of("selectLastColumn"_s),
			$of("shift END"_s),
			$of("selectLastColumnExtendSelection"_s),
			$of("ctrl shift END"_s),
			$of("selectLastRowExtendSelection"_s),
			$of("ctrl END"_s),
			$of("selectLastRow"_s),
			$of("PAGE_UP"_s),
			$of("scrollUpChangeSelection"_s),
			$of("shift PAGE_UP"_s),
			$of("scrollUpExtendSelection"_s),
			$of("ctrl shift PAGE_UP"_s),
			$of("scrollLeftExtendSelection"_s),
			$of("ctrl PAGE_UP"_s),
			$of("scrollLeftChangeSelection"_s),
			$of("PAGE_DOWN"_s),
			$of("scrollDownChangeSelection"_s),
			$of("shift PAGE_DOWN"_s),
			$of("scrollDownExtendSelection"_s),
			$of("ctrl shift PAGE_DOWN"_s),
			$of("scrollRightExtendSelection"_s),
			$of("ctrl PAGE_DOWN"_s),
			$of("scrollRightChangeSelection"_s),
			$of("TAB"_s),
			$of("selectNextColumnCell"_s),
			$of("shift TAB"_s),
			$of("selectPreviousColumnCell"_s),
			$of("ENTER"_s),
			$of("selectNextRowCell"_s),
			$of("shift ENTER"_s),
			$of("selectPreviousRowCell"_s),
			$of("ctrl A"_s),
			$of("selectAll"_s),
			$of("ctrl SLASH"_s),
			$of("selectAll"_s),
			$of("ctrl BACK_SLASH"_s),
			$of("clearSelection"_s),
			$of("ESCAPE"_s),
			$of("cancel"_s),
			$of("F2"_s),
			$of("startEditing"_s),
			$of("SPACE"_s),
			$of("addToSelection"_s),
			$of("ctrl SPACE"_s),
			$of("toggleAndAnchor"_s),
			$of("shift SPACE"_s),
			$of("extendTo"_s),
			$of("ctrl shift SPACE"_s),
			$of("moveSelectionTo"_s),
			$of("F8"_s),
			$of("focusHeader"_s)
		}))),
		$of("FormattedTextField.focusInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("ctrl C"_s),
			$of($DefaultEditorKit::copyAction),
			$of("ctrl V"_s),
			$of($DefaultEditorKit::pasteAction),
			$of("ctrl X"_s),
			$of($DefaultEditorKit::cutAction),
			$of("COPY"_s),
			$of($DefaultEditorKit::copyAction),
			$of("PASTE"_s),
			$of($DefaultEditorKit::pasteAction),
			$of("CUT"_s),
			$of($DefaultEditorKit::cutAction),
			$of("shift LEFT"_s),
			$of($DefaultEditorKit::selectionBackwardAction),
			$of("shift KP_LEFT"_s),
			$of($DefaultEditorKit::selectionBackwardAction),
			$of("shift RIGHT"_s),
			$of($DefaultEditorKit::selectionForwardAction),
			$of("shift KP_RIGHT"_s),
			$of($DefaultEditorKit::selectionForwardAction),
			$of("ctrl LEFT"_s),
			$of($DefaultEditorKit::previousWordAction),
			$of("ctrl KP_LEFT"_s),
			$of($DefaultEditorKit::previousWordAction),
			$of("ctrl RIGHT"_s),
			$of($DefaultEditorKit::nextWordAction),
			$of("ctrl KP_RIGHT"_s),
			$of($DefaultEditorKit::nextWordAction),
			$of("ctrl shift LEFT"_s),
			$of($DefaultEditorKit::selectionPreviousWordAction),
			$of("ctrl shift KP_LEFT"_s),
			$of($DefaultEditorKit::selectionPreviousWordAction),
			$of("ctrl shift RIGHT"_s),
			$of($DefaultEditorKit::selectionNextWordAction),
			$of("ctrl shift KP_RIGHT"_s),
			$of($DefaultEditorKit::selectionNextWordAction),
			$of("ctrl A"_s),
			$of($DefaultEditorKit::selectAllAction),
			$of("HOME"_s),
			$of($DefaultEditorKit::beginLineAction),
			$of("END"_s),
			$of($DefaultEditorKit::endLineAction),
			$of("shift HOME"_s),
			$of($DefaultEditorKit::selectionBeginLineAction),
			$of("shift END"_s),
			$of($DefaultEditorKit::selectionEndLineAction),
			$of("BACK_SPACE"_s),
			$of($DefaultEditorKit::deletePrevCharAction),
			$of("shift BACK_SPACE"_s),
			$of($DefaultEditorKit::deletePrevCharAction),
			$of("ctrl H"_s),
			$of($DefaultEditorKit::deletePrevCharAction),
			$of("DELETE"_s),
			$of($DefaultEditorKit::deleteNextCharAction),
			$of("ctrl DELETE"_s),
			$of($DefaultEditorKit::deleteNextWordAction),
			$of("ctrl BACK_SPACE"_s),
			$of($DefaultEditorKit::deletePrevWordAction),
			$of("RIGHT"_s),
			$of($DefaultEditorKit::forwardAction),
			$of("LEFT"_s),
			$of($DefaultEditorKit::backwardAction),
			$of("KP_RIGHT"_s),
			$of($DefaultEditorKit::forwardAction),
			$of("KP_LEFT"_s),
			$of($DefaultEditorKit::backwardAction),
			$of("ENTER"_s),
			$of($JTextField::notifyAction),
			$of("ctrl BACK_SLASH"_s),
			$of("unselect"_s),
			$of("control shift O"_s),
			$of("toggle-componentOrientation"_s),
			$of("ESCAPE"_s),
			$of("reset-field-edit"_s),
			$of("UP"_s),
			$of("increment"_s),
			$of("KP_UP"_s),
			$of("increment"_s),
			$of("DOWN"_s),
			$of("decrement"_s),
			$of("KP_DOWN"_s),
			$of("decrement"_s)
		}))),
		$of("ToolBar.ancestorInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("UP"_s),
			$of("navigateUp"_s),
			$of("KP_UP"_s),
			$of("navigateUp"_s),
			$of("DOWN"_s),
			$of("navigateDown"_s),
			$of("KP_DOWN"_s),
			$of("navigateDown"_s),
			$of("LEFT"_s),
			$of("navigateLeft"_s),
			$of("KP_LEFT"_s),
			$of("navigateLeft"_s),
			$of("RIGHT"_s),
			$of("navigateRight"_s),
			$of("KP_RIGHT"_s),
			$of("navigateRight"_s)
		}))),
		$of("ComboBox.control"_s),
		$(table->get("control"_s)),
		$of("ComboBox.controlForeground"_s),
		$of(black),
		$of("ComboBox.background"_s),
		$(table->get("window"_s)),
		$of("ComboBox.foreground"_s),
		$of(black),
		$of("ComboBox.border"_s),
		$of(comboBoxBorder),
		$of("ComboBox.selectionBackground"_s),
		$of(black),
		$of("ComboBox.selectionForeground"_s),
		$(table->get("text"_s)),
		$of("ComboBox.disabledBackground"_s),
		$(table->get("control"_s)),
		$of("ComboBox.disabledForeground"_s),
		$(table->get("textInactiveText"_s)),
		$of("ComboBox.font"_s),
		$of(dialogPlain12),
		$of("ComboBox.ancestorInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("ESCAPE"_s),
			$of("hidePopup"_s),
			$of("PAGE_UP"_s),
			$of("pageUpPassThrough"_s),
			$of("PAGE_DOWN"_s),
			$of("pageDownPassThrough"_s),
			$of("HOME"_s),
			$of("homePassThrough"_s),
			$of("END"_s),
			$of("endPassThrough"_s),
			$of("DOWN"_s),
			$of("selectNext"_s),
			$of("KP_DOWN"_s),
			$of("selectNext"_s),
			$of("UP"_s),
			$of("selectPrevious"_s),
			$of("KP_UP"_s),
			$of("selectPrevious"_s),
			$of("SPACE"_s),
			$of("spacePopup"_s),
			$of("ENTER"_s),
			$of("enterPressed"_s)
		}))),
		$of("TextField.caretForeground"_s),
		$of(black),
		$of("TextField.caretBlinkRate"_s),
		$($of($Integer::valueOf(500))),
		$of("TextField.inactiveForeground"_s),
		$(table->get("textInactiveText"_s)),
		$of("TextField.selectionBackground"_s),
		$(table->get("textHighlight"_s)),
		$of("TextField.selectionForeground"_s),
		$(table->get("textHighlightText"_s)),
		$of("TextField.background"_s),
		$(table->get("window"_s)),
		$of("TextField.foreground"_s),
		$(table->get("textText"_s)),
		$of("TextField.font"_s),
		$of(sansSerifPlain12),
		$of("TextField.border"_s),
		$of(textFieldBorder),
		$of("TextField.focusInputMap"_s),
		fieldInputMap,
		$of("PasswordField.caretForeground"_s),
		$of(black),
		$of("PasswordField.caretBlinkRate"_s),
		$($of($Integer::valueOf(500))),
		$of("PasswordField.inactiveForeground"_s),
		$(table->get("textInactiveText"_s)),
		$of("PasswordField.selectionBackground"_s),
		$(table->get("textHighlight"_s)),
		$of("PasswordField.selectionForeground"_s),
		$(table->get("textHighlightText"_s)),
		$of("PasswordField.background"_s),
		$(table->get("window"_s)),
		$of("PasswordField.foreground"_s),
		$(table->get("textText"_s)),
		$of("PasswordField.font"_s),
		$of(monospacedPlain12),
		$of("PasswordField.border"_s),
		$of(textFieldBorder),
		$of("PasswordField.focusInputMap"_s),
		passwordInputMap,
		$of("TextArea.caretForeground"_s),
		$of(black),
		$of("TextArea.caretBlinkRate"_s),
		$($of($Integer::valueOf(500))),
		$of("TextArea.inactiveForeground"_s),
		$(table->get("textInactiveText"_s)),
		$of("TextArea.selectionBackground"_s),
		$(table->get("textHighlight"_s)),
		$of("TextArea.selectionForeground"_s),
		$(table->get("textHighlightText"_s)),
		$of("TextArea.background"_s),
		$(table->get("window"_s)),
		$of("TextArea.foreground"_s),
		$(table->get("textText"_s)),
		$of("TextArea.font"_s),
		$of(monospacedPlain12),
		$of("TextArea.border"_s),
		$of(marginBorder),
		$of("TextArea.focusInputMap"_s),
		multilineInputMap,
		$of("TextPane.caretForeground"_s),
		$of(black),
		$of("TextPane.caretBlinkRate"_s),
		$($of($Integer::valueOf(500))),
		$of("TextPane.inactiveForeground"_s),
		$(table->get("textInactiveText"_s)),
		$of("TextPane.selectionBackground"_s),
		$of(lightGray),
		$of("TextPane.selectionForeground"_s),
		$(table->get("textHighlightText"_s)),
		$of("TextPane.background"_s),
		$of(white),
		$of("TextPane.foreground"_s),
		$(table->get("textText"_s)),
		$of("TextPane.font"_s),
		$of(serifPlain12),
		$of("TextPane.border"_s),
		$of(marginBorder),
		$of("TextPane.focusInputMap"_s),
		multilineInputMap,
		$of("EditorPane.caretForeground"_s),
		$of(red),
		$of("EditorPane.caretBlinkRate"_s),
		$($of($Integer::valueOf(500))),
		$of("EditorPane.inactiveForeground"_s),
		$(table->get("textInactiveText"_s)),
		$of("EditorPane.selectionBackground"_s),
		$of(lightGray),
		$of("EditorPane.selectionForeground"_s),
		$(table->get("textHighlightText"_s)),
		$of("EditorPane.background"_s),
		$of(white),
		$of("EditorPane.foreground"_s),
		$(table->get("textText"_s)),
		$of("EditorPane.font"_s),
		$of(serifPlain12),
		$of("EditorPane.border"_s),
		$of(marginBorder),
		$of("EditorPane.focusInputMap"_s),
		multilineInputMap,
		$of("FileChooser.ancestorInputMap"_s),
		$of($$new($UIDefaults$LazyInputMap, $$new($ObjectArray, {
			$of("ESCAPE"_s),
			$of("cancelSelection"_s)
		}))),
		$of("ToolTip.border"_s),
		$of(raisedBevelBorder),
		$of("ToolTip.background"_s),
		$(table->get("info"_s)),
		$of("ToolTip.foreground"_s),
		$(table->get("infoText"_s)),
		$of("PopupMenu.selectedWindowInputMapBindings"_s),
		$of($$new($ObjectArray, {
			$of("ESCAPE"_s),
			$of("cancel"_s),
			$of("TAB"_s),
			$of("cancel"_s),
			$of("shift TAB"_s),
			$of("cancel"_s),
			$of("DOWN"_s),
			$of("selectNext"_s),
			$of("KP_DOWN"_s),
			$of("selectNext"_s),
			$of("UP"_s),
			$of("selectPrevious"_s),
			$of("KP_UP"_s),
			$of("selectPrevious"_s),
			$of("LEFT"_s),
			$of("selectParent"_s),
			$of("KP_LEFT"_s),
			$of("selectParent"_s),
			$of("RIGHT"_s),
			$of("selectChild"_s),
			$of("KP_RIGHT"_s),
			$of("selectChild"_s),
			$of("ENTER"_s),
			$of("return"_s),
			$of("ctrl ENTER"_s),
			$of("return"_s),
			$of("SPACE"_s),
			$of("return"_s)
		})),
		$of("OptionPane.border"_s),
		optionPaneBorder,
		$of("OptionPane.messageAreaBorder"_s),
		optionPaneMessageAreaBorder,
		$of("OptionPane.buttonAreaBorder"_s),
		optionPaneButtonAreaBorder,
		$of("OptionPane.errorIcon"_s),
		$($SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/Error.gif"_s)),
		$of("OptionPane.informationIcon"_s),
		$($SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/Inform.gif"_s)),
		$of("OptionPane.warningIcon"_s),
		$($SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/Warn.gif"_s)),
		$of("OptionPane.questionIcon"_s),
		$($SwingUtilities2::makeIcon($of(this)->getClass(), MotifLookAndFeel::class$, "icons/Question.gif"_s)),
		$of("OptionPane.windowBindings"_s),
		$of($$new($ObjectArray, {
			$of("ESCAPE"_s),
			$of("close"_s)
		})),
		$of("RootPane.defaultButtonWindowKeyBindings"_s),
		$of($$new($ObjectArray, {
			$of("ENTER"_s),
			$of("press"_s),
			$of("released ENTER"_s),
			$of("release"_s),
			$of("ctrl ENTER"_s),
			$of("press"_s),
			$of("ctrl released ENTER"_s),
			$of("release"_s)
		}))
	}));
	table->putDefaults(defaults);
}

MotifLookAndFeel::MotifLookAndFeel() {
}

$Class* MotifLookAndFeel::load$($String* name, bool initialize) {
	$loadClass(MotifLookAndFeel, name, initialize, &_MotifLookAndFeel_ClassInfo_, allocate$MotifLookAndFeel);
	return class$;
}

$Class* MotifLookAndFeel::class$ = nullptr;

					} // motif
				} // plaf
			} // swing
		} // java
	} // sun
} // com