name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  PACKAGE_VERSION: 17.35-beta1

jobs:
  package-source-tar-gz:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - run: git clone --recursive https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}}

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-source.tar.gz
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}.tar.gz

  package-source-zip:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}}

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-source.zip
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}.zip

  build-linux-x86_64:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - run: git clone --recursive https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-linux-x86_64
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-linux-x86_64.tar.gz

  build-linux-x86_64-test:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - run: git clone --recursive https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=ON -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-linux-x86_64.test
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-linux-x86_64.tar.gz

  build-linux-x86_64-repo:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - run: git clone --recursive https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=ON -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-linux-x86_64.repo
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-linux-x86_64.repo.tar.gz

  build-macos-x86_64:
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-macos-x86_64
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-macos-x86_64.tar.gz

  build-macos-x86_64-test:
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=ON -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-macos-x86_64.test
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-macos-x86_64.tar.gz

  build-macos-x86_64-repo:
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=ON -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-macos-x86_64.repo
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-macos-x86_64.repo.tar.gz

  build-macos-aarch64:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-source
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}.tar.gz

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-macos-aarch64
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-macos-aarch64.tar.gz

  build-macos-aarch64-test:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=ON -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-macos-aarch64.test
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-macos-aarch64.tar.gz

  build-macos-aarch64-repo:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=ON -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-macos-aarch64.repo
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-macos-aarch64.repo.tar.gz

  build-windows-x86_64:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=OFF -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-windows-x86_64
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-windows-x86_64.zip

  build-windows-x86_64-test:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TEST=ON -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-windows-x86_64.test
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-windows-x86_64.zip

  build-windows-x86_64-repo:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DPACKAGE_VERSION:STRING=${{env.PACKAGE_VERSION}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_TO_REPO=ON -DBUILD_TEST=OFF -DJ=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: libjdk-${{env.PACKAGE_VERSION}}-windows-x86_64.repo
        path: ${{github.workspace}}/libjdk-${{env.PACKAGE_VERSION}}-windows-x86_64.repo.zip